argoproj-labs/argocd-operator

.osdk-scorecard.yaml, deploy/olm-catalog/argocd-operator/0.0.4/argocd-operator.v0.0.4.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.0.4/argoproj.io_argocds_crd.yaml, hack/bundle.sh
This PR adds the configuration to run the operator-sdk scorecard OLM tests. Additional fields have been added to the CSV to pass the tests.
=> Add OLM Scorecard Configuration 

docs/reference/argocd.md, pkg/controller/argocd/configmap.go
This PR addresses #41 adds the logic to update the `argocd-cm` ConfigMap when one of the corresponding properties on the `ArgoCD` CRD changes.
=> Update Argo ConfigMap when CRD Changes

deploy/argo-cd/argoproj.io_applications_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.6/argoproj.io_applications_crd.yaml, pkg/common/defaults.go
This PR updates the default version of Argo CD that is deployed to the upstream v1.5.1 release.
=> Update Argo CD to v1.5.1

build/util/Dockerfile, docs/reference/argocd.md, go.mod, go.sum, pkg/common/defaults.go
This PR updates the operator to use Argo CD v1.5.2, which addresses [CVE-2020-5260](http://cve.circl.lu/cve/CVE-2020-5260).
See the following for more information:
- https://github.com/git/git/security/advisories/GHSA-qm7j-c969-7j4q
- https://github.com/argoproj/argo-cd/releases/tag/v1.5.2
=> Update Operator to Use Argo CD v1.5.2

deploy/crds/argoproj.io_argocds_crd.yaml, docs/reference/argocd.md, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/apis/argoproj/v1alpha1/zz_generated.deepcopy.go, pkg/apis/argoproj/v1alpha1/zz_generated.openapi.go, pkg/controller/argocd/configmap.go
This PR addresses #55 to change the behaviour of the operator (and name) for the following properties.
- `Repositories` -> `InitialRepositories`
- `SSHKnownHosts` -> `InitialSSHKnownHosts`
- `TLS.Certs` -> `TLS.InitialCerts`
The operator will use the new properties to set the initial value for the corresponding keys in the Argo CD ConfigMaps and Secrets. Any changes to these properties on a CR once the cluster has been created will have no effect.
=> Only Initialize Repos, SSH Known Host and Certs

hack/cluster-clean.sh, pkg/controller/argocd/deployment.go, pkg/controller/argocd/secret.go, pkg/controller/argoutil/resource.go, tests/e2e/argocd-tests/02-ingress.yaml
This PR addresses #54 by renaming the cluster secret to "[CLUSTER NAME]-cluster" to avoid overwriting the internal Argo CD secret named `argocd-secret`.
=> Rename Cluster Secret to Avoid Name Collisions

deploy/role.yaml, pkg/controller/argocd/route.go, pkg/controller/argocd/secret.go
This PR addresses #56 by adding logic to set the host on Routes if present in the CR, as well as the necessary permission on the Role used by the operator.
=> Allow Override of Host on Routes

examples/argocd-oauth.yaml, pkg/controller/argocd/configmap.go
This PR attempts to address #47 by triggering a rollout of the Dex Deployment when the configuration changes. Triggering a rollout has the effect of "restarting" Dex and the new Pod(s) will use the updated configuration.
=> Trigger Rollout for Dex when Configuration Changes

examples/argocd-insights.yaml, examples/argocd-route.yaml, grafana/dashboards/argocd.json, pkg/controller/argocd/util.go
This PR addresses #64 to fix several dashboard metrics that are not working.
The initial ArgoCD Grafana dashboard had several values hard-coded and did not work if the ArgoCD custom resource was not named `argocd`. A new `argocd` variable was added to the dashboard that contains the name given to the ArgoCD resource. This variable is then used anywhere the name of a cluster resource is specified.
=> Update ArgoCD Dashboard to Use Cluster Name

.travis.yml
This PR updates the Travis CI build options to use the latest OS distribution, as well as go 1.13.
=> Update Travis CI Build Options

deploy/kustomization.yaml
Right now, the main way we have of deploying the operator assumes that everyone is going to be using OLM. While OLM is great, I think there are at least a pocket of folks who think of this as an overhead to getting things up and running (at least initially / during experimentation, etc.)
Since kustomize is already built into `kubectl` at this point, providing a `kustomization.yaml` would provide a low overhead for folks getting started. With this, now instead of having to apply each of the individual manifests, users can either use this as a remote base inside of kustomize, or just run ` kubectl apply -k .`  to get things running.
Likely need to get some documentation updated with this, but wanted to make sure this is something we'd like to include before moving forward.
=> Add basic kustomization

examples/argocd-oauth.yaml
This changes the oauth example CR to use the dex repo and version that the original PR was merged into.
=> Change oauth example to use supported version

docs/install/manual.md
We are creating minikube with the context name argocd, but while setting context we're giving minikube/argocd.
I understand that if the user didn't specify the cluster name, the default name is used - minikube.
But I think it is better go as per the flow. 
It might create confusion (especially for the one, who simply copy paste from the doc and execute :)).
=> Remove context: minikube

docs/reference/argocd.md
The dex Image moved to the Red Hat COP Repo. I believe @sabre1041 moved it a bit ago.
=> Updating to new version of the dex image

deploy/operator.yaml, docs/reference/argocdexport.md, pkg/common/defaults.go, version/version.go
This PR updates the operator to v0.0.9, which includes the following.
- Update Operator to Argo CD v1.5.5
- Add Support for Backups to an Azure Storage Container
- Add Support for Backups to a GCP Bucket
- Upgrade operator-sdk to v0.17.0
=> Release Operator v0.0.9

pkg/controller/argocd/ingress.go
- Adds a suffix of "server" to the ArgoServer ingress to be consistent with the route name and to match the expected name in getArgoServerURI()
argoproj-labs/argocd-operator#95
=> Updates ArgoServer ingress name to fix configmap issue

pkg/controller/argocd/ingress.go
- Updates ArgoServerIngress and ArgoServerGRPCIngress to use the result from getArgoServerHost() and getArgoServerGRPC(), respectively, for the TLS host
argoproj-labs/argocd-operator#96
=> Updates TLS logic for argo server ingresses

deploy/crds/argoproj.io_argocds_crd.yaml, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/apis/argoproj/v1alpha1/zz_generated.openapi.go, pkg/controller/argocd/status.go
This PR addresses #75 to add status values on the ArgoCD custom resource for all of the Argo CD components.
The status `Phase` value is used as an overall status for the cluster. When all of the components are in a `Running` status, the `Phase` is set to `Available`. This can be used to determine when the cluster is ready for action.
=> Add Status Values for All Argo CD Components

build/util/Dockerfile, deploy/operator.yaml, docs/reference/argocd.md, docs/reference/argocdexport.md, pkg/common/defaults.go, tests/e2e/argocd-tests/02-assert.yaml, tests/e2e/argocd-tests/02-ingress.yaml, version/version.go
This PR updates the operator to v0.0.10, which includes the following.
The ArgoCD custom resource has breaking changes to the Ingress and Route properties.
**Ingress:** The `Spec.Ingress` property has been removed from the ArgoCD custom resource. The `Spec.Grafana.Ingress`, `Spec.Prometheus.Ingress` and `Spec.Server.Ingress` properties have all been converted from a boolean value to an object that allows for more customization of the Ingress resource for those components that are managed by the operator. The following shows the old and new way of defining Ingress options.
**OLD**
``` yaml
kind: ArgoCD
metadata:
spec:
ingress:
host: myhost
path: /mypath
server:
grpc:
ingress: true
ingress: true
insecure: true
```
**NEW**
``` yaml …
```
=> Release Operator v0.0.10

docs/reference/argocd.md, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/common/defaults.go, pkg/common/keys.go, pkg/controller/argocd/configmap.go
Adds support for using the `repository.credentials` key, also called "credential templates" in Argo - very much implemented in the same way that `InitialRepositories` is.
=> Add support for using `repository.credentials`

docs/reference/argocd.md, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/controller/argocd/deployment.go
This adds the ability to specify mounting the serviceaccount token to the repo-server pod as well as specifying the serviceaccount it should run as. This can be done by adding the following to the ArgoCD CR:
```
...
spec:
repo:
mountsatoken: true
serviceaccount: argocd-application-controller
...
```
Resolves #110
=> Mount repo server token

build/util/Dockerfile, deploy/argo-cd/argoproj.io_applications_crd.yaml, docs/reference/argocd.md, pkg/common/defaults.go
This PR updates Argo CD to [v1.6.1](https://github.com/argoproj/argo-cd/releases/tag/v1.6.1).
=> Upgrade to Argo CD v1.6.1

kustomization.yaml
I have added this commit to enable others to reference Kustomize from the root directory. You can use my fork as an example by running `kustomize build https://github.com/jdbohrman/argocd-operator`.
=> Added kustomization in root dir referencing the deploy kustomization

deploy/olm-catalog/argocd-operator/0.0.12/argocd-operator.v.0.0.12.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.0.12/argoproj.io_applications_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.12/argoproj.io_appprojects_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.12/argoproj.io_argocdexports_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.12/argoproj.io_argocds_crd.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml, deploy/service_account.yaml, hack/cluster-clean.sh, pkg/controller/argocd/deployment.go
This PR addresses #124 as a workaround for the upstream OLM issue that prevents two or more ServiceAccounts from having Roles that are duplicates. This will eventually get fixed in OLM but for now the Redis StatefulSet and HA Proxy deployment can use the same ServiceAccount, as the permissions required are the same. This can be changed in the future if a need arises to have different Roles for the two components.
=> Share ServiceAcount for Redis Components

deploy/crds/argoproj.io_argocdexports_crd.yaml, deploy/crds/argoproj.io_argocds_crd.yaml, docs/reference/argocd.md, docs/usage/ha.md, hack/generate.sh, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/controller/argocd/util.go
This PR addresses #131 and adds properties for overriding the container image and tag for the Redis HAProxy component when run with HA mode enabled.
=> Add Properties for Redis HAProxy Component

deploy/crds/argoproj.io_argocds_crd.yaml, docs/reference/argocd.md, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/controller/argocd/configmap.go
resolves #82 
This modifies `initialSSHKnownHosts` to have two different keys:
```yaml
initialSSHKnownHosts:
excludedefaulthosts: false
keys: |
my-git.org: alkjasldkfjalskdfj
```
This allows users to either include/exclude the default ssh hosts that are included with ArgoCD by default. Previously if you wanted to provide your own set of keys, it would overwrite these default keys and you would be responsible for adding them back in if you wanted them.
Now the default behavior is if you don't exclude them, your specified keys will just be appended to the default keys.
=> Update InitialSSHKnownHosts handling

pkg/controller/argocd/argocd_controller.go, pkg/controller/argocd/argocd_controller_test.go
When an ArgoCD object is marked for deletion, it's continuing to be reconciled.
This means that it's triggering the creation of resources that should be deleted, and in turn, the objects are into a loop of delete and recreate, which it doesn't recover from.
Fixes #162
=> Don't rereconcile deleted ArgoCD objects.

go.mod, pkg/controller/argocd/route.go, pkg/controller/argocd/route_test.go, pkg/controller/argocd/status.go
This changes the behaviour of the route reconciliation to allow it to patch the route objects when the Insecure flag changes.
This also adds a simple test for this behaviour.
=> Fix for not updating when changing the ArgoCD resource.

pkg/controller/argocd/secret.go, pkg/controller/argocd/secret_test.go
This adds support for putting the CA generated into a key that can be picked up
by cert-utils-operator.
Fixes #166
=> Support cert-utils-operator with the CA generation.

pkg/common/defaults.go, pkg/controller/argocd/argocd_controller_test.go, pkg/controller/argocd/configmap.go, pkg/controller/argocd/configmap_test.go, pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go, pkg/controller/argocd/route_test.go, pkg/controller/argocd/testing.go
* Fix the repo-server deployment
This updates the repo server to have an emptyDir mounted /app/config/gpg/keys
This comes from this change https://github.com/argoproj/argo-cd/pull/4136/files
* Fix for argocd-controller.
This is arguably a bug in ArgoCD it's parsing an empty string into a
clearing of the map for resource customizations.
Add go-cmp to the dependencies.
This should fix #148
=> Changes to support ArgoCD v1.7.7.

pkg/controller/argocd/configmap.go, pkg/controller/argocd/configmap_test.go, pkg/controller/argocd/testing.go, pkg/controller/argoutil/resource.go
This fixes a reconciliation bug, where the TLS cert configmap wasn't updated on subsequent reconciliations.
Fixes: #122
=> Fix reconciliation of argocd-tls-certs-cm.

deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.0.14/argocd-operator.v0.0.14.clusterserviceversion.yaml, deploy/operator.yaml, deploy/registry/Dockerfile, pkg/common/defaults.go, version/version.go
This PR updates the operator to v0.0.14, which includes the following.
Enhancements
* #148 - Add support for Argo CD 1.7.
* #144 - Add option to control resync frequency for argocd application controller.
* #167 - Support cert-utils-operator with the CA generation.
Bug Fixes
* #122 - Fix reconciliation of argocd-tls-certs-cm.
* #151 - Fix for not updating when changing the ArgoCD resource
* #152 - Fix OLM version mismatch/initialSSHKnownHosts validation error.
* #162 - Don't rereconcile deleted ArgoCD objects.
Documentation
* #140 - Update example with how to enable Routes.
* #156 - Fix a mistake in the Routes documentation with password retrieval.
* #173 - Document a small nuanced issue with group mappings.
=> Release Operator v0.0.14

deploy/crds/argoproj.io_argocds_crd.yaml, docs/reference/argocd.md, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/apis/argoproj/v1alpha1/zz_generated.openapi.go, pkg/common/keys.go, pkg/controller/argocd/configmap.go, pkg/controller/argocd/configmap_test.go, tests/e2e/argocd-tests/04-assert.yaml, tests/e2e/argocd-tests/04-disable-admin.yaml
This PR addresses #158 by adding a new property to the ArgoCD custom resource to toggle the admin user. The `Spec.DisableAdmin` property **inversely** maps to the `admin.enabled` key in the `argocd-cm` ConfigMap. 
See: https://argoproj.github.io/argo-cd/operator-manual/user-management/#disable-admin-user
=> Add Property to Disable Admin User

docs/usage/basics.md
The example described the in the docs isn't working without adding `--namespace argocd` to the `port-forward` directive.
=> Fixed port-forward command

pkg/common/values.go, pkg/controller/argocd/configmap.go, pkg/controller/argocd/configmap_test.go
This adds support for creating an empty gpg-keys configmap.
=> Add support for creating an empty gpg-keys map.

pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go
This adds support for copying the proxy configuration from the running operator process into the deployments created by the operator.
It's case insensitive, and copies over the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` fields.
=> Add support for proxies in the repo-server deployment.

docs/reference/argocd.md
As per https://github.com/argoproj-labs/argocd-operator/blob/master/pkg/apis/argoproj/v1alpha1/argocd_types.go#L262, TLS key for `ArgoCDRouteSpec` should be lowercased (`tls` instead of `TLS`)
=> Fixed wrong `TLS` key example for server route

docs/reference/argocd.md, pkg/common/keys.go, pkg/controller/argocd/util.go, pkg/controller/argocd/util_test.go
This adds functionality for fetching the images from the configured environment variables for the operator process.
* ARGOCD_DEX_IMAGE
* ARGOCD_IMAGE
* ARGOCD_REDIS_HA_IMAGE
* ARGOCD_REDIS_IMAGE
* ARGOCD_GRAFANA_IMAGE
The resolution order for these images:
1. From the ArgoCD object configuration (there are spec entries for each image).
2. From the environment variables above.
3. From the hard-coded values in pkg/common/defaults.go
=> Add support for getting the images from the environment.

pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go
When rereconciling the init-container for the Dex pod, the image was not being
updated if it had changed.
Signed-off-by: Kevin McDermott <bigkevmcd@gmail.com>
Fixes: #211
=> Fix dex-pod init-container image during rereconciles.

pkg/controller/argocd/configmap.go, pkg/controller/argocd/configmap_test.go, pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go
This adds support for an env-var `DISABLE_DEX` which cause the deployment for Dex to be skipped, and no config to be set in the config map for Dex.
=> Support disabling the DEX server.

docs/contribute/development.md, hack/build.sh
This allows overriding the binary to be executed as `operator-sdk` to make it easier to support the older version that's needed to build this operator.
Setting `OPERATOR_SDK=/usr/local/bin/operator-sdk` will be picked up by the build script.
=> Allow override operator

pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go
This addresses a bug in the argocd-server deployment reconciliation, where it was not changing the command-line for the deployment when rereconciling the CR.
=> Fix argocd server insecure

.osdk-scorecard.yaml, deploy/olm-catalog/argocd-operator/0.0.15/argocd-operator.v0.0.15.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_applications_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_appprojects_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_argocdexports_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_argocds_crd.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml, docs/reference/argocdexport.md, version/version.go
This release enables all-namespace mode. Users can now install the Argo CD operator to watch all-namespaces and create instances in multiple namespaces.
*Release details:*
Features:
* Expose API/attribute to create ArgoCD for cluster config #225
* Create workload permission objects per instance of ArgoCD CR #199
* Run unit tests on GitHub actions #226
* Support disabling the DEX server. #218
* Add Property to Disable Admin User #184
* Add support for creating an empty gpg-keys map. #193
* Add support for proxies in the repo-server deployment. #194
* Add support for getting the images from the environment. #198
Bugs:
* Fix argocd server insecure #220
* Fix issue with replacing the resource configuration #187
* Fix dex-pod init-container image during rereconciles. #212
* Fix typos and …
=> Enable all-namespace installation mode

docs/usage/basics.md
This adds a small example of how to change the admin password for the
operator-installed argocd setup.
Fixes: #228
=> Improve documentation around changing admin password.

deploy/crds/argoproj.io_argocds_crd.yaml, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/controller/argocd/hooks_test.go, pkg/controller/argocd/testing.go, pkg/reconciler/openshift/clusterconfig_test.go, pkg/reconciler/openshift/openshift.go, pkg/reconciler/openshift/openshift_test.go
This commit Modifies the behaviour of https://github.com/argoproj-labs/argocd-operator/pull/225. 
What?
Cluster admin should set a env variable "ARGOCD_CLUSTER_CONFIG_NAMESPACES" with a list of namespaces(comma separated) where ArgoCD instance can manage cluster config resources. Users should request admin to get their namespaces added to the ARGOCD_CLUSTER_CONFIG_NAMESPACES env variable.
User cannot request for a ArgoCD instance without such privileges in  ARGOCD_CLUSTER_CONFIG_NAMESPACES. In such cases, corresponding namespace should be removed from the ARGOCD_CLUSTER_CONFIG_NAMESPACES env variable.
=> Set env var to configure ArgoCD for Cluster Config

pkg/controller/argocd/util.go, pkg/controller/argocd/util_test.go
This PR fixes the issue -> https://github.com/argoproj-labs/argocd-operator/issues/223
Allows user to provide an external hostname as redirect-url to argocd-server without enabling ingress/route. 
When user explicitly sets the field `server.host` with a value and chooses not to enable ingress/route for it, the `url` in `argocd-cm` (argocd config map) should still be populated with the external hostname provided.
=> [WIP] Allow user to provide custom external hostname for argo-server

pkg/controller/argocd/util.go
If the controller is used a library, we need to ensure that this logic is available in the controller too and not only in main.go.
=> Set "route api available" to true when controller boots up

pkg/controller/argocd/service.go, pkg/controller/argocd/service_test.go
Current reconciliation logic does not check if Dex is enabled/disabled and creates a service for it.
Added a check to verify that Dex is enabled before creating a service for it.
=> fix: do not deploy service for dex when disabled

pkg/controller/argocd/role.go, pkg/controller/argocd/role_test.go, pkg/controller/argocd/rolebinding.go, pkg/controller/argocd/rolebinding_test.go
Operator should not create Role and Role Bindings for Dex if it has been disabled by the user.
=> do not create role/role_bindings for Dex, if disabled

pkg/controller/argocd/service_account.go, pkg/controller/argocd/service_account_test.go
Operator should not create Service Account for Dex if it has been disabled by the user.
=> do not create ServiceAccount for Dex, if disabled

pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/common/keys.go, pkg/controller/argocd/argocd_controller.go, pkg/controller/argocd/argocd_controller_test.go, pkg/controller/argocd/role.go, pkg/controller/argocd/rolebinding.go, pkg/controller/argocd/service_account.go, pkg/controller/argocd/util.go, pkg/controller/argocd/util_test.go, pkg/controller/argoutil/resource.go
Currently, the service accounts and cluster role resources are not cleaned up when the argocd instance is deleted. This PR introduces a finalizer and a pre-delete hook logic to delete the remaining resources. 
How to test:
1. Create a test namespace with the name `argocd-test`.
2. Run the operator locally.
```shell
operator-sdk run local --watch-namespace argocd-test
```
3. Create an instance of argocd in argocd-test. This will create cluster roles and bindings.
4. Delete the instance.
5. Observe the cluster roles, cluster role bindings, and service accounts getting deleted.
=> Remove cluster resources on instance deletion

pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go
Issue: the dec init container is stuck in a crash loop if the binary is aready in use.
Resolution: do not overwrite existing files as implemented in argocd PR https://github.com/argoproj/argo-cd/pull/3136
=> make dex init container resilient to restarts

pkg/controller/argocd/hooks_test.go, pkg/controller/argocd/rolebinding.go, pkg/controller/argocd/rolebinding_test.go, pkg/reconciler/openshift/clusterconfig_test.go, pkg/reconciler/openshift/openshift.go, pkg/reconciler/openshift/openshift_test.go
This PR adds a hook that provides the `argocd-application-controller` to have `admin` privileges only for the namespace it is installed in and not cluster-wide for Openshift deployments. 
Note: A custom role for `argocd-application-controller` with limited permissions will still be created but for openshift deployments, `Cluster Role - admin` will be used for creating the `RoleBinding`
=> Provide admin access to ArgoCD application-controller for local ns

pkg/controller/argocd/role.go, pkg/controller/argocd/role_test.go, pkg/controller/argocd/rolebinding.go, pkg/controller/argocd/rolebinding_test.go, pkg/controller/argocd/service_account_test.go, pkg/reconciler/openshift/openshift.go, pkg/reconciler/openshift/openshift_test.go
/kind bug
**[Issue]**
Currently the name generated for all resources follows the convention **"instance-name"-"service-name"**, which would work fine for namespace scoped resources.   
The problem occurs in cluster scoped resources.   Each argocd instance needs to reference to its copy of cluster resources.   We need to generate unique name for cluster resources.  Otherwise,  ArgoCD instance A cannot  have its cluster role that is different than ArgoCD instance B for example.
We need to generate unique name for cluster resources for 
@shubhamagarwal19 explained to me that this function is to generate unique name for cluster resources that are used by different argocd instances.   The fact that we need to generate "ClusterResourceName" can still sound strange.  Cluster resource names are …
=> generate unique name for cluster scoped resources

pkg/reconciler/openshift/openshift.go
Machine Sets are used in cluster configuration scenarios. Currently, the application controller service account doesn't have permissions to manage machine set resources. This PR adds a rule in the cluster config cluster role to manage Machine Sets
How to Test:
1. Install Argo CD operator by creating a catalog source
2. Create an argocd instance in `test` namespace
3. Add `test` namespace to cluster config namespaces list ie set an environment variable `ARGOCD_CLUSTER_CONFIG_NAMESPACES=test` in the Subscription
4. Verify if machine set rule is added in clusterrole `<cr-name>-test-argocd-application-controller`
```yaml
- apiGroups:
- 'machine.openshift.io'
resources:
- '*'
verbs:
- '*'
```
5. Create a sample application with machine sets
```shell
argocd app create machineset --repo …
```
=> Add permissions to manage machine sets in cluster config scenario

deploy/cluster_role.yaml, deploy/cluster_role_binding.yaml, deploy/role.yaml, docs/install/manual.md
Update the local RBAC files to provide permissions for the argocd operator service account. This PR will fix the broken manual installation steps
Fixes: #255
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
=> Update RBAC for manual installation of the operator

pkg/common/defaults.go, pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go, pkg/controller/argocd/statefulset.go, pkg/controller/argocd/statefulset_test.go, pkg/controller/argocd/status.go, pkg/controller/argocd/util.go, pkg/controller/argocd/util_test.go
- Updates the Default ArgoCD version from 1.7.7 -> 1.8.7
- This would now deploy ArgoCD Application Controller as a `StatefulSet` rather than a `Deployment`.
- Cleans up the existing `argocd-application-controller` Deployment before creating the new one as a `StatefulSet`
[Test-Fresh-Installation]
- To test Fresh Installation, Deploy the latest Operator.
- Create an ArgoCD instance.
- Make sure, `application-controller` is deployed as a `StatefulSet` and not as a `Deployment`
- Also, verify the ArgoCD server version, it should be `v1.8.7`
[Test-Upgrade-Scenario]
- To test Upgrade scenario, Upgrade to latest Operator,
- Make sure the existing `application-controller DEPLOYMENT` is removed and is now deployed as a `StatefulSet` with version `v1.8.7`
=> Upgraded ArgoCD version from 1.7.7 to 1.8.7

pkg/reconciler/openshift/openshift.go
Currently, the cluster role associated with the application controller service account doesn't have permissions to manage `compliance.openshift.io` apiGroup. 
This PR appends a rule in the ClusterConfig cluster role for the application controller to manage `compliance.openshift.io`.
[How-To-Test]
- Deploy the latest ArgoCD operator
- Create an ArgoCD instance in `argocd` namespace
- Add `argocd` namespace to cluster config namespaces list ie set an environment variable `ARGOCD_CLUSTER_CONFIG_NAMESPACES=argocd` in the Subscription
- Verify if rule for `compliance.openshift.io` is added to the clusterrole `<cr-name>-<namespace>-argocd-application-controller`
```
- verbs:
- get
- watch
- list
apiGroups:
- compliance.openshift.io
resources:
- scansettings
- compliancesuites
- compliancescans …
```
=> support compliance.openshift.io apiGroup for cluster config

pkg/common/defaults.go, pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go
Upgrade argo-cd from v1.8.7 to v2.0-rc1. Incorporated the below change.
```
The dex commands rundex and gendexcfg have been migrated from argocd-util to argocd-dex. It means that you need to update argocd-dex-server deployment's commands to install argocd-dex binary instead of argocd-util in init container and run dex command from argocd-dex instead of argocd-util
```
Follow up PR'S::
----------------
Consider all the new features introduced in argo-cd v2.0 and identify what needs to be incorporated into argocd-operator
How to Test:
----------------
> Create argocd-cr
> Check if the dex-server pod is created with below changes.
https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/1.8-2.0.md#dex-tool-migrated-from-argocd-util-to-argocd-dex
> Validate Dex …
=> Upgrade argo-cd from v1.8.7 to v2.0-rc1

pkg/reconciler/openshift/openshift.go
**machineconfig** is used in post installation machine configuration tasks. Currently, the application controller service account doesn't have permissions to manage **machineconfig** resources. This PR adds a rule in the cluster config cluster role to manage **machineconfig**
More details about machine configuration resource:
https://docs.openshift.com/container-platform/4.7/post_installation_configuration/machine-configuration-tasks.html
How to Test:
Install Argo CD operator by creating a catalog source
Create an argocd instance in test namespace
Add test namespace to cluster config namespaces list ie set an environment variable ARGOCD_CLUSTER_CONFIG_NAMESPACES=test in the Subscription
Verify if machineconfig rule is added in clusterrole <cr-name>-test-argocd-application-controller
```
- …
```
=> Add permissions to manage machineconfig resource

deploy/crds/argoproj.io_argocds_crd.yaml, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/controller/argocd/applicationset.go, pkg/controller/argocd/applicationset_test.go, pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go, pkg/controller/argocd/testing.go, pkg/controller/argocd/util.go
Problem: Cannot deploy Application set and Redis HA Proxy pods in namespace where resource quota is associated. It is mandatory to assign resource requests and limits for containers in such namespaces.
```
(combined from similar events): Error creating: pods "example-argocd-applicationset-controller-5984478995-g98wr" is forbidden: failed quota: mem-cpu-demo: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```
```
(combined from similar events): Error creating: pods "example-argocd-redis-ha-haproxy-6fd9d65fd4-wtjbb" is forbidden: failed quota: mem-cpu-demo: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```
Solution: Provide an option(place holder) in the ArgoCD CR where user can define the resource requirements.
How to Test:
Create a namespace with …
=> feat: Handle resource requirements for Application set and Redis HA Proxy Containers

deploy/operator.yaml, pkg/common/defaults.go
This release includes the following enhancements, bug fixes and documentation updates.
Enhancements
* #184 - Add Property to Disable Admin User
* #194 - Add support for proxies in the repo-server deployment
* #280 - Add support for Argo CD 2.0.
Bug Fixes
* #186 - Pods stuck in crashloop after update to 0.0.14
* #187 - Fix issue with replacing the resource configuration
* #191 - Missing gpg configmap after update argocd-operator 0.0.13 to 0.0.14
Documentation
* #189 - Add documentation for the resourceInclusions property
* #190 - Fixed port-forward command
* #195 - Fixed wrong `TLS` key example for server route
=> Release Argo CD Operator v0.0.15

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/task.md, .github/PULL_REQUEST_TEMPLATE.md
Once merged, any new PR's or Issues created by contributors  will automatically see the template's contents in the pull request body.
Reference:
[Issues and PR templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)
=> Set up PULL_REQUEST and ISSUE_TEMPLATES

pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go
/kind bug
Correctly volume mount `argocd-gpg-keys-cm` ConfigMap to `<instance>-repo-server` pods.
Fixes #286 
=> fix: volume mount argocd-gpg-keys-cm to repo server pods

pkg/common/values.go, pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go, pkg/controller/argocd/statefulset.go, pkg/controller/argocd/statefulset_test.go, pkg/controller/argocd/util.go
Argo CD v2.0 introduced a Secret mount for a TLS secret named `argocd-repo-server-tls`. This secret can be used to specify the TLS certificate used by the repo server's gRPC endpoint. It must be made available to the workloads of the server, application controller and the repo server itself.
This PR adds reconciliation logic for adding the required volume mounts.
The next step will be to provide configuration to request this TLS from OpenShift service CA.
Fixes #288
* Reconcile any `ArgoCD` CR
* Inspect the `<instance>-repo-server` deployment and look for the …
=> feat: Reconcile argocd-repo-server-tls volume mounts

docs/reference/argocd.md, examples/argocd-oauth.yaml, pkg/common/defaults.go
Updates dex to `v2.28.0`
`v2.22.0` contains a bug in how OpenShift auth is processed and will result in an empty username in ArgoCD. This has been resolved in subsequent versions of ArgoCD
=> Updated Dex version to v2.28.0

docs/usage/insights.md
Insight.md documentation page does not provide details on how to setup openshift routes for grafana and the required secret to reference for the password.
#292 
Fixes #?
#292 
By following the doc changes in the PR , you should be able to login in to Grafana without any confusion.
=> Doc: Update grafana setup and login for openshift platform (#292)

deploy/kustomization.yaml, docs/install/kustomize.md
> /kind bug
Kustomize is one of the supported ways of installing argo-cd operator on any kubernetes platform. It will help any new user getting started. 
#80 
#300 
Fixes #?
#80 
#300 
Follow the documentation to install operator using kustomize
=> chore: update the documentation for installing operator using Kustomize(#80)(#300)

pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go, pkg/controller/argocd/statefulset.go, pkg/controller/argocd/statefulset_test.go, pkg/controller/argocd/testing.go
/kind bug
This PR adds compute resources to definition of several of the ArgoCD init containers.  Without this, the associated pods will fail to start if ArgoCD is installed into a namespace which has resource quotas set.
Fixes #304 
To test, define a namespace that has resource quotas set, then create an ArgoCD CR that defines compute resources for its components, and install into the namespace.  All pods should start successfully.
=> fix: add compute resources to init containers

deploy/crds/argoproj.io_argocdexports_crd.yaml, deploy/crds/argoproj.io_argocds_crd.yaml
Our CRDs still reside in `apiextensions.k8s.io/v1beta1`. This API is deprecated and will be removed soon from upstream Kubernetes.
This PR updates CRDs `argocds` and `argocdexports` to `apiextensions.k8s.io/v1`. Changes are the result of `operator-sdk generate crds` with a newer version of kubebuilder.
Fixes #261
On a virgin cluster / new-install scenario:
1. Deploy CRDs to a "virgin" cluster (`oc apply -f deploy/crds/` and `oc apply -f deploy/argo-cd`)
2. Start operator locally (e.g. `operator-sdk run local`) …
=> chore: Update CRDs to apiextensions.k8s.io/v1

.osdk-scorecard.yaml, cmd/manager/main.go, deploy/olm-catalog/argocd-operator/0.0.16/argocd-operator.v0.0.16.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.0.16/argoproj.io_applications_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.16/argoproj.io_applicationsets_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.16/argoproj.io_appprojects_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.16/argoproj.io_argocdexports_crd.yaml, deploy/olm-catalog/argocd-operator/0.0.16/argoproj.io_argocds_crd.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml, deploy/role.yaml, docs/reference/argocd.md, docs/usage/keycloak.md, examples/argocd-keycloak.yaml, mkdocs.yml, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/common/defaults.go, pkg/controller/argocd/keycloak.go, pkg/controller/argocd/keycloak_test.go, pkg/controller/argocd/sso.go, pkg/controller/argocd/sso_test.go, pkg/controller/argocd/util.go, version/version.go
This PR adds `sso provider` in CR.   The reconciler installs Keycloack/RHSSO using OpenShift Templates.   This PR does not configure.  This PR also does not delete installed Keycloak.
Added
Fixes #?
This PR address installing keycloak for openshift of #312
Deploy the example argocd CR
```
kind: ArgoCD
metadata:
labels:
example: route
spec:
sso:
provider: keycloak
server:
route:
enabled: true
```
or add the below section to your existing argocd CR …
=> feat: Install keycloak for openshift using OpenShift templates

build/Dockerfile
This PR updates the operator base image to the latest version.
The current release image is failing the quay.io security scans, as the base image is quite old at this point. 
https://quay.io/repository/argoprojlabs/argocd-operator/manifest/sha256:38254c8d53172993cb51c0b4c72645757ba36e7e8e3b1251683b00cede47fa7c?tab=vulnerabilities
The updated image is passing.
https://quay.io/repository/jmckind/argocd-operator/manifest/sha256:ab70a593a4f40bd035c25d9756cd189262b3bff3d5c54842479fae2bdbe79207?tab=vulnerabilities
=> Update Base Image to the Latest Version

docs/requirements.txt, mkdocs.yml
fixes #332 
> /kind bug
Currently the docs requirements.txt is not defined with versions of required modules. Add the exact module versions as dependencies.
Also, update the site_url to empty string as defined in the error message.
NA
fixes #332 
Fixes #?
#332 
Install mkdocs locally and run `mkdocs serve`
=> fix readthedocs build issue

docs/reference/argocd.md
=> chore: Fix typo in the TLS Options Documentation.

pkg/common/keys.go, pkg/controller/argocd/argocd_controller.go, pkg/controller/argocd/argocd_controller_test.go, pkg/controller/argocd/custommapper.go, pkg/controller/argocd/custommapper_test.go, pkg/controller/argocd/role.go, pkg/controller/argocd/role_test.go, pkg/controller/argocd/rolebinding.go, pkg/controller/argocd/rolebinding_test.go, pkg/controller/argocd/route_test.go, pkg/controller/argocd/secret.go, pkg/controller/argocd/secret_test.go, pkg/controller/argocd/service_account_test.go, pkg/controller/argocd/testing.go, pkg/controller/argocd/util.go
This PR addresses the need to manually provide the permissions to ArgoCD instance for managing a new namespace. This feature would allow the user to simply label a namespace with the label `argocd.argoproj.io/managed-by: <namespace of argocd>` and the operator would create the required permissions. 
Fixes  #352
// TODO
=> allow operator to manage permissions based on namespace labels

pkg/common/defaults.go, pkg/controller/argocd/keycloak_test.go
This PR addresses the issue that was created due to PR #349. I have unintentionally updated the Keycloak Image in PR #349, changing it back to the original state.
> /kind bug
Revert the  Keycloak Image name and version that was updated in #349 
NA
1. Run the operator using `operator-sdk run local`
2. Create an Argo CD instance
3. Update the Argo CD CR Spec with
```
sso:
provider: keycloak
```
4. Verify that the Keycloak pods are up and running.
=> Revert Keycloak image name and version update in #349

pkg/controller/argocd/deployment.go, pkg/controller/argocd/statefulset.go
/kind bug
Perform reconciliation of deployments and statefulsets when resource requests or limits have changed.
Fixes #?
* Create ArgoCD CR
* Set resource specifications on `controller`, `repo` or `server` components
* Before this fix: Neither application controller, repo server or server objects will get reconciled (keep old resource spec)
* After this fix: All three workloads should get updated resource spec from ArgoCD CR
=> fix: Allow reconciliation of resource overrides

docs/reference/argocd.md
This fixes a small docs typo that referenced kustomizeBuildOptions instead of oidcConfig
N/A
Nothing to test, just a doc fix.
=> chore: Fix small typo in reference docs (kustomizeBuildOptions -> oidcConfig)

deploy/crds/argoproj.io_argocds_crd.yaml, docs/reference/argocd.md, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/apis/argoproj/v1alpha1/zz_generated.deepcopy.go, pkg/controller/argocd/route.go, pkg/controller/argocd/route_test.go
This PR enables the ability to add additional labels to a generated route. This can be useful in a number of scenarios including router sharding, etc.
Fixes #359 
This can be tested by building the operator from the PR branch and deploying an ArgoCD instance with the following CR:
```yaml
kind: ArgoCD
metadata:
labels:
example: route
spec:
grafana:
enabled: true
route:
enabled: true
prometheus:
enabled: true
route:
enabled: true
server:
route:
enabled: true
labels:
shard: my-shard
```
You can see from the …
=> feat: Add ability to apply additional labels to generated routes

pkg/controller/argocd/keycloak.go, pkg/controller/argocd/sso.go
> /kind bug
#366  introduced a new bug which does not allow operator to update the keycloak related OIDC configuration intermittently. 
Reason for failure:
A user can choose to override Keycloak container resource requests/limits from Argo CD CR (Please refer #366 ). When a user does not provide Keycloak container resource requests/limits in Argo CD CR, operator overrides the default values and updates the Keycloak deployment config with new resource requirements.
#366 fails to get the new version(modified) deployment config to update the OIDC configuration. 
NA
1. Run the …
=> fix: Keycloak fails to update OIDC config in argocd-cm intermittently

pkg/controller/argocd/configmap.go, pkg/controller/argocd/configmap_test.go
> /kind bug
I have observed an unexpected crash of the operator when the operator is trying to reconcile an empty Argo CD configmap.
I can reproduce this issue by creating an empty Argo CD configmap (argocd-cm) in a namespace and then creating an Argo CD CR. Noticed that operator crashed while reconciling the empty configmap.
Error:
```
goroutine 1873 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1769d40, 0x1b43340)
/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.18.3/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1769d40, 0x1b43340) …
```
=> fix: operator crashes on reconciliation when existing Argo CD configmap is empty

pkg/controller/argocd/deployment.go
> /kind bug
Users can modify argocd server container resource limit/request in the ArgoCD CR.  The operator should apply/reconcile the changes to the cluster.   However, reconciler is not checking for changes in ArgoCD CR against the running state due to a bug.
This PR adds a check in the reconcile function to check for changes in ArgoCD CR on argocd server container resource limit/request against the cluster and set the "changed" flag accordingly.
NA
1. Create ArgoCD CR in the foo namespace.
2. Record the resource limit/request on the running argocd …
=> fix: ArgoCD server resources limit/request changes in ArgoCD CR is not reconcilied

.github/workflows/publish.yaml
This PR adds a GHA workflow to build and publish the latest code to a container registry with the tag `:latest`. It requires three secrets to be created in the repository:
- `REGISTRY_URL` - The registry to publish the image to (i.e. `quay.io/<reponame>`)
- `REGISTRY_USERNAME` - The user to authenticate as
- `REGISTRY_PASSWORD` - The password/token to use to authenticate
This workflow will only run on push/merge to the `master` branch.
Fixes #325 
**How to test changes / Special notes to the …
=> feat: Publish latest operator image after push to master branch

deploy/crds/argoproj.io_argocds_crd.yaml, docs/reference/argocd.md, pkg/apis/argoproj/v1alpha1/argocd_types.go, pkg/common/defaults.go, pkg/controller/argocd/applicationset.go, pkg/controller/argocd/applicationset_test.go, pkg/controller/argocd/deployment.go, pkg/controller/argocd/deployment_test.go, pkg/controller/argocd/statefulset_test.go, pkg/controller/argocd/util.go, pkg/controller/argocd/util_test.go
This PR adds the ability to adjust the loglevel of each of the ArgoCD components (controller, repo, server)
Fixes #329 
After building the operator from this PR branch, you can deploy it with the following to confirm the loglevel functionality:
```yaml
kind: ArgoCD
metadata:
labels:
example: basic
spec: 
server:
logLevel: "warn"
repo:
logLevel: "error"
controller:
logLevel: "info"
```
If you don't set any of the above, it will default the loglevel to info (which is the current behavior of each of the …
=> feat: Add ability to configure loglevel for each ArgoCD component

pkg/controller/argocd/argocd_controller.go, pkg/controller/argocd/util.go, pkg/controller/argocd/util_test.go
> /kind bug
When the ArgoCD instance is deleted from the source namespace, operator would remove the managed-by label from all the namespaces that were managed by this particular argocd instance.
The operator currently already has the logic to remove the RBACs from the namespaces from which the label is being removed, so it takes care of removing the RBACs as soon as the labels is removed.
This ensures there are no redundant roles/role_bindings/labels are present for a namespace.
> https://issues.redhat.com/browse/GITOPS-1228
BUILD for testing - create a catalog source using the …
=> FIX: remove RBACs from target-namespace when ArgoCD instance is deleted

CONTRIBUTING.md, controllers/argocd/route.go
This PR aims to eliminate confusing as to what verifyRouteAPI is actually user for. The comment currently says since `Prometheus` which is confusing, since this method is for verifying the existence of the OpenShift Routes API within a cluster. Also this PR updates the link in the Contributing.md to point to the proper file location to make it easier for new comers to find the document.
Fixes #?
N/A
N/A
=> fix comment for verifyRouteAPI in route.go

docs/usage/resource_management.md, mkdocs.yml
This PR creates a page to explain the creation, updation and deletion of resource requests/limits for Argo CD workloads.
Install mkdocs
Run `mkdocs serve` to start the UI locally on `0.0.0.0:8000`
A new page can be seen with name `Resource Requirements`
=> Create a new page for Argo CD resource requirements

controllers/argocd/role.go, controllers/argocd/rolebinding.go
/kind bug
This prevents setting ("illegal" cross-namespace) `ownerReferences` to role and rolebindings created from the `managed-by` feature. We only set up `ownerReferences` for resources in the same namespace as the ArgoCD CR.
Since this may change the behaviour of Argo CD's drift detection in certain situations (because we do apply all labels from the ArgoCD CR to the resources we create), a second PR that fixes this behavior will be coming soon.
Fixes #408 
* Create `ArgoCD` CR in namespace `ns-one`
* Create namespace `ns-two`
* Apply `managed-by` label to `ns-two`: `kubectl …
=> fix: Only set ownerReferences for roles & rolebindings in CR's namespace

api/v1alpha1/argocd_types.go, api/v1alpha1/argocd_types_test.go, common/defaults.go, controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, controllers/argocd/deployment.go, controllers/argocd/hpa.go, controllers/argocd/ingress.go, controllers/argocd/prometheus.go, controllers/argocd/role.go, controllers/argocd/rolebinding.go, controllers/argocd/route.go, controllers/argocd/secret.go, controllers/argocd/secret_test.go, controllers/argocd/service.go, controllers/argocd/service_account.go, controllers/argocd/statefulset.go, controllers/argocd/util.go, controllers/argocd/util_test.go, controllers/argocdexport/export.go, controllers/argocdexport/job.go, controllers/argoutil/resource.go, controllers/argoutil/resource_test.go, controllers/argoutil/secret.go, controllers/argoutil/volume.go, controllers/openshift/clusterconfig_test.go
/kind bug
Currently, when we create resources, we inherit all labels from the `ArgoCD` CR to those resources. If the `ArgoCD` CR was created by Argo CD itself from Git, it will have an instance label (`app.kubernetes.io/instance` by default), indicating that the resource is managed by that particular Argo CD instance/application. However, this label will also be inherited on the resources that the Operator creates, and that are not managed through Argo CD (but through the Operator). This confuses Argo CD, as it thinks it might be managing these resources.
IMHO, we don't need to copy the labels from the `ArgoCD` CR at all, and just set some default labels on the resources we create to be able to identify it.
Also, this …
=> fix: Do not copy all labels from ArgoCD CR to resources we create

.gitignore
/kind cleanup
New Operator SDK creates `build/_output` for transient build artifacts. We should ignore it for Git.
Fixes #?
=> chore: Ignore transient build artifacts in Git

controllers/argocd/secret.go
/kind bug
This bug fixes a reconciliation loop and race condition between the Argo CD Operator and Argo CD.
Argo CD usually picks up changes from `argocd-secret` without the need to restart. This is also true for changes to `tls.key` and `tls.crt` fields, as Argo CD would just restart the TLS listener with the new configuration on this occasion.
The Operator instructs the `argocd-server` deployment to restart after a change to `tls.crt` or `tls.key` in the `-tls` secret. This will, for some reason, trigger Argo CD to generate a new key in `tls.key` of `argocd-secret`, which leads to the reconciliation loop and the constant restarts. …
=> fix: Do not restart argocd-server on changes to argocd-tls

bundle/manifests/argoproj.io_argocds.yaml
> /kind bug
Adds the updated `bundle/manifests/argoproj.io_argocds.yaml` file which was missing from PR #415. This file is generated by running `make bundle`.
=> fix: update bundle manifest with ExecTimeout

pkg/controller/argocd/secret.go
/kind bug
Backport to rhos-v1.2 branch (see #421 for PR to master branch)
This bug fixes a reconciliation loop and race condition between the Argo CD Operator and Argo CD.
Argo CD usually picks up changes from `argocd-secret` without the need to restart. This is also true for changes to `tls.key` and `tls.crt` fields, as Argo CD would just restart the TLS listener with the new configuration on this occasion.
The Operator instructs the `argocd-server` deployment to restart after a change to `tls.crt` or `tls.key` in the `-tls` secret. This will, for some reason, trigger Argo CD to generate a new key in `tls.key` of `argocd-secret`, which leads to the reconciliation loop and the constant restarts.
**Have you updated the …
=> fix: Do not restart argocd-server on changes to argocd-tls (rhos-v1.2)

bundle.Dockerfile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argocd-operator_v1_serviceaccount.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml
There's been a change in the operator-sdk version 1.10.1 to not generate a file (`bundle/manifests/argocd-operator_v1_serviceaccount.yaml`) when running `make bundle`, and in version 1.11.0 the presence of that file will actually cause `make bundle` to error out. This PR is to remove that file and regenerate the bundle artifacts using operator-sdk version 1.11.0
=> chore: upgrade operator-sdk to v1.11.0

common/defaults.go
Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>
> /kind bug
This bumps the default ArgoCD version to v2.1.0 and the default ApplicationSet version to v0.2.0.
Fixes #403 
Deploy an ArgoCD CR and verify that it deploys ArgoCD v2.1.0 and ApplicationSet v0.2.0
=> Bump Default ArgoCD and ApplicationSet versions

api/v1alpha1/argocd_types.go, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_argocds.yaml, common/defaults.go, config/crd/bases/argoproj.io_argocds.yaml, config/manager/kustomization.yaml, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, controllers/argocd/statefulset_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go, docs/reference/argocd.md
Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>
This PR provides the ability to set the logformat of ArgoCD components. By default (if nothing is set), it will use text format. Otherwise, if you specify json it will cause the specified component to use json format.
Fixes #180 
You can test this change by running the operator from this PR branch with the follow resource:
```yaml
kind: ArgoCD
metadata:
labels:
example: basic
spec:
controller:
logFormat: json
server:
logFormat: json
repo:
logFormat: json
``` …
=> feat: Add log format for ArgoCD components

deploy/olm-catalog/argocd-operator/0.0.16/argocd-operator.v0.0.16.clusterserviceversion.yaml, pkg/controller/argocd/argocd_controller.go, pkg/controller/argocd/argocd_controller_test.go, pkg/controller/argocd/role.go, pkg/controller/argocd/role_test.go, pkg/controller/argocd/rolebinding_test.go, pkg/controller/argocd/route_test.go, pkg/controller/argocd/secret.go, pkg/controller/argocd/secret_test.go, pkg/controller/argocd/service_account_test.go, pkg/controller/argocd/util.go, pkg/controller/argocd/util_test.go
> /kind bug
This PR fixes the issue with the `managed-by` label getting reset to the source namespace. This happened only for the namespaces where ArgoCD instance is installed. 
Earlier the operator would by default label the namespace where the argocd instance is installed with the managed-by label as the source namespace. The fix is to not label the namespace explicitly while making sure the required RBACs are created/deleted for the namespace. This is done by appending the source namesapce to the list of namespaces retrieved using the label. 
Fixes - https://issues.redhat.com/browse/GITOPS-1247
**How to test changes / Special notes …
=> Fix: managed-by label reset to source namespace

controllers/argocd/secret.go
/kind bug
The Operator reconciles the admin password for Argo CD from the `<instance>-cluster` secret, which stores a base64 encoded version of the password in its `admin.password` field. Users tend to encode base64 data like this: `echo foobar | base64`. This also encodes the final newline from `echo` into the base64 data, which effectively makes the password useless (users will not be able to login).
This change removes any trailing newline from the decoded value in `admin.password`, so users won't shoot themselves in the foot.
Fixes #?
* Run Operator locally
* Create new Argo …
=> fix: Remove trailing newline from admin.password

Makefile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
Sets the IMG and BUNDLE_IMG variables in the makefile, so that developers don't have to remember to specify them when running `make bundle`
=> fix: Update Makefile to set IMG and BUNDLE_IMG

bundle/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/argocd-operator-manager-config_v1_configmap.yaml, bundle/manifests/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/default/kustomization.yaml, config/manager/manager.yaml, config/rbac/auth_proxy_role_binding.yaml, config/rbac/leader_election_role_binding.yaml, config/rbac/role_binding.yaml, config/rbac/service_account.yaml
Adds the prefix `argocd-operator-` to all resources belonging to the operator, so that they won't have generic names like `controller-manager`
Fixes #?
Install the operator and check that the names of the operator's resources are correct.
=> fix: use operator sdk naming conventions for resources

bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/manifests/bases/argocd-operator.clusterserviceversion.yaml
Adds descriptions for the ArgoCD CRDs to the argocd-operator's CSV file.  Fixes the *Provided APIs* section of the operator's details page showing *Not Available* as the description.
Install the operator via the OLM catalog.  The proper descriptions should be shown for each ArgoCD CRD in the *Provided APIs* section
=> chore: Add descriptions for ArgoCD CRDs in CSV

common/defaults.go
> /kind bug
Fixes #445
NA
#445 
**Steps to reproduce the behavior:**
1. Run the operator locally using `make install && make run`
2. Create an Argo CD CR with the below configuration.
```
kind: ArgoCD
metadata:
namespace: foo
spec:
applicationSet:
resources:
limits:
cpu: "2"
memory: 1Gi
requests:
cpu: 250m
memory: 512Mi
server:
route:
enabled: true
```
3. Verify that the application set pod moves in to `ImagePullBackoff` state.
=> fix: Invalid Image location for ApplicationSets

controllers/argocd/applicationset.go
/kind bug
This PR adds check for nodeSelector and tolerations in applicationSet reconciler so that the pod can reschedule on correct nodes
Fixes #450 
`make install`, `make run` and then in argoCD CR spec add , verify that all pods now have nodeSelectors and tolerations
```
spec:
applicationSet: {}
nodePlacement:
nodeSelector:
abc: abc
tolerations:
- effect: NoSchedule
key: abc
value: abc
```
=> fix: add nodePlacement check in applicationSet reconciler

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go
…g map
/kind bug
Adds reconciliation logic for resourceInclusions from argocd CR to `argocd-cm` config map
Fixes #471 
1. Deploy operator
2. Update the argo-cd CR resource inclusions
3. wait for config map to be reconciled
4. config map should reflect changes in resource inclusions
=> fix: reconcile argocd cr changes for resouce inclusions in argocd-cm config map

api/v1alpha1/argocd_types.go, api/v1alpha1/argocdexport_types.go, bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/manifests/bases/argocd-operator.clusterserviceversion.yaml, controllers/argocdexport/job.go
> /kind bug
batch/v1beta1 version of cronjob is set to be deprecated in k8s v1.25. We should upgrade it in our code base before it becomes too late and causes bigger problems as we have seen it can in the past 
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
Fixes #?
=> feat: bump cronjob api to v1

controllers/argocd/util.go, controllers/argocd/util_test.go
kind bug
Adds logic to remove namespaces that were managed by an argo-cd instance (i.e, they contained the managed-by label) from that instance's cluster secret after the namespace has been deleted 
Currently, argocd-operator only handles cases where managed namespaces are updated, but doesn't handle the scenario where managed namespaces are deleted
Fixes #478 …
=> fix: Remove managed namespace from cluster secret after deletion

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go
/kind bug
Porting https://github.com/argoproj-labs/argocd-operator/pull/472 into release-0.1 branch
Fixes #471 
=> fix: reconcile resource inclusions from argocd CR into argocd-cm

controllers/argocd/util.go, controllers/argocd/util_test.go
kind bug
Porting https://github.com/argoproj-labs/argocd-operator/pull/479 into release-0.1 branch
Fixes #478 
=> fix: handle deletion of managed ns in cluster secret and update unit test

controllers/argoutil/env.go, controllers/argoutil/env_test.go
> /kind bug
Sort the Env vars before adding to the workloads.
Fixes #466 
NA
Fixes #466 
NA
=> fix: reposerver, server and controller pods restart continuously when multiple env vars are set

build/util/util.sh, common/defaults.go, controllers/argocdexport/job.go, tests/e2e/argocd-tests/04-assert.yaml, tests/e2e/argocd-tests/04-export.yaml
> /kind bug
Fixes the export function of the argocd operator
There were three problems that required fixing
1. The name of the service account has changed.  It is now prefixed by the name of the argocd instance it belongs to.
2. The argocd command to invoke the export function has changed from `argocd-util export` to `argocd admin export`
3. On OpenShift, the SCC that OpenShift assigns to the export job pod has changed from `restricted` to `anyuid`.  The effect of this is that the pod no longer has permissions to write the export data to the PV.  The fix for this is to specify the correct `runAsUser`, `runaAsGroup` and `fsGroup` values for the export job pod.
**Have you …
=> fix: fix broken argocd export

controllers/argocd/secret.go
/kind bug
Previously when a user deleted the information under `.data` in argocd-secret, an error would occur that caused pods to crash (error was from an `assignment to entry in nil map`). This PR adds a check that will see if `.data == nil`, and if it is, it will repopulate it with new data. 
Verifying the error behavior: 
- checkout to recent version of master branch `git checkout master`
- Run `make docker-build`, `make docker-push` and login to a cluster and then run `make deploy`
- Add the Argo CD instance: 
```
cat <<EOF | kubectl apply -f - …
```
=> fix: crash when no .data exists in argocd-secret

controllers/argoutil/env.go
> /kind bug
/kind cleanup
https://github.com/argoproj-labs/argocd-operator/pull/467 introduced environment merge logic that should be simplified.
* eliminated an unnecessary for-loop
* use go library sort function
Fixes #?
Test covered by env_test.go
=> chore:  simplify env merge logic

build/util/util.sh, common/defaults.go, controllers/argocdexport/job.go, tests/e2e/argocd-tests/04-assert.yaml, tests/e2e/argocd-tests/04-export.yaml
> /kind bug
Fixes the export function of the argocd operator Cherry picks the fix for this bug from the release-0.1 branch to master.
There were three problems that required fixing
1. The name of the service account has changed.  It is now prefixed by the name of the argocd instance it belongs to.
2. The argocd command to invoke the export function has changed from `argocd-util export` to `argocd admin export`
3. On OpenShift, the SCC that OpenShift assigns to the export job pod has changed from `restricted` to `anyuid`.  The effect of this is that the pod no longer has permissions to write the export data to the PV.  The fix for this is to specify the correct …
=> fix: fix broken argocd export (cherry-pick to master) (#490)

controllers/argocd/util.go
/kind bug
fixes a bug where a managed namespace was not being removed from the managing argocd instance's cluster secret after that namespace was updated to be managed by a different argocd instance 
Fixes https://issues.redhat.com/browse/GITOPS-1644
1. Install Gitops-operator 
2. Create namespaces: `test-target`, `test-argo1`, `test-argo2`
3. Label …
=> fix: managed namespace not getting properly removed from argocd instance cluster secret 

common/keys.go, controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/rolebinding_test.go, docs/usage/custom_roles.md
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
1. Introduces the env variables `CONTROLLER_CLUSTER_ROLE` and `SERVER_CLUSTER_ROLE` for specifying the cluster roles for application controller and server respectively.
2. If these env variables are found, the operator will use these roles in the bindings and delete the existing default roles.
3. These roles will be applied to all the namespaces where Argo CD is running or managed by Argo CD using the managed-by label
1. Run the operator locally and create multiple Argo CD instances
2. Add the env variables `CONTROLLER_CLUSTER_ROLE` …
=> feat: Support for custom roles using env variables

controllers/argocd/argocd_controller.go, controllers/argocd/role.go, controllers/argocd/rolebinding.go, controllers/argocd/testing.go, controllers/argocd/util.go, controllers/argocd/util_test.go
Filter the list of managed namespaces only once during each reconciliation and reuse them at multiple places. Currently, we list the namespaces while reconciling roles and role bindings. Since RBAC is managed for each argocd component, the operator filters the namespaces more than eight times per reconciliation. 
Fixes #?
=> Filter managed namespaces only once per reconciliation

api/v1alpha1/argocd_types.go, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/status.go, controllers/argocd/status_test.go, deploy/olm-catalog/argocd-operator/0.2.0/argoproj.io_argocds.yaml, docs/reference/api.html.md, tests/e2e/argocd-tests/02-ingress-available.yaml
This would add a new field, `.host`, to `.status` of `ArgoCD`. When route or ingress is enabled (priority given to route) then the route will be displayed in the new URL field. 
When no URL exists from a route or ingress, the field will not be displayed. 
When on a non-OpenShift cluster (meaning the Route API is not available), if the user chooses to enable Route, they will only get a log saying that Routes are not available in non-OpenShift environments and to please use Ingresses instead. The state of the application controller and of the URL will not be affected. 
When the route or ingress is configured, but the corresponding controller has not yet set it up properly (i.e. is not in Ready state or …
=> add route/ingress URL to .status

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, controllers/argocd/util_test.go, docs/reference/argocd.md
> /kind bug
#552 
Fixes #552 
1. Create an Argo CD Instance
2. Deploy the below Argo CD CR.
```
kind: ArgoCD
metadata:
labels:
example: example-argocd
spec:
server:
route:
enabled: true
```
3. Add a cert to argocd-tls-certs-cm configmap.
```
..........
data:
test.example.com: '-----BEGIN CERTIFICATE-----  -----END CERTIFICATE-----'
```
4. Argo CD controller reconciles the configmap changes and remove the added cert.
=> fix: argocd-tls-certs-cm is overwritten on any change

docs/usage/ingress.md, docs/usage/routes.md
Adds documentation about how to utilize the `.host` field under the Argo CD operand's `.status` field that was added in PR https://github.com/argoproj-labs/argocd-operator/pull/514
=> add docs for host field in .status

controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/rolebinding_test.go
/kind bug
When creating a namespace with the manage-by label it creates unnecessary dexServer and redisHa roles and roleBindings on the new namespace. The below namespace test doesn't need these roles/rolebindings.
~~~
apiVersion: v1
kind: Namespace
metadata:
name: test
labels:
argocd.argoproj.io/managed-by: openshift-gitops
~~~
Fixes GITOPS-1550
1. Create a target namespace with managed-by label of the namespace where Argo CD instance is deployed.
2. Run
`$ oc get roles -n <target-namespace>`
`$ oc get rolebindings -n <target-namespace>`
3. Confirm that no desServer and redisHa …
=> GITOPS-1550 removed unnecessary roles/rolebindings for target namespace

build/util/Dockerfile, common/defaults.go, controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, controllers/argocd/util_test.go, docs/reference/argocd.md, go.mod, go.sum
> /kind bug
1. cherrypicks #553 
2. fixes CVE 2022-24348 by upgrading Argo CD to v2.2.5
#552 
CVE 2022-24348
Fixes #552 
CVE 2022-24348
#552  is a clean cherry-pick from master branch. There is no additional testing required.
Steps to test CVE 2022-24348:
- Create namespace helm-guestbook
- Create ArgoCD instance somewhere
- Create application with this manifest
```
kind: Application
metadata:
name: helm-guestbook
namespace: <argo namespace>
spec:
destination:
namespace: helm-guestbook
server: …
```
=> [Release v0.2.1] fix argocd-tls-certs-cm overwritting and CVE 2022-24348

controllers/argocd/secret.go, controllers/argocd/testing.go, controllers/argocd/util_test.go, controllers/argoutil/tls.go
/kind bug
See https://github.com/redhat-developer/gitops-operator/issues/277
Recent versions of Firefox refuse to process TLS certificates that are signed by an unnamed CA. The Operator uses a CA certificate that's created without a X509 `Subject`, and thus, Firefox chokes.
For an existing installation, the `argocd-tls` and `argocd-ca` secrets must be deleted and reconciled back by the Operator.
Fixes https://github.com/redhat-developer/gitops-operator/issues/277
* Install a recent version of Firefox (I used 97.0.1 (64-bit), installed …
=> fix: Set subject on CA cert used for signing self-signed certs

deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_argocds.yaml
> /kind bug
PR #534 did not add changes into bundle. To be specific `deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_argocds.yaml` file. This is causing CI on the other PR's fail.
Run `make bundle` to regenerate outdated manifests.
NA
Fixes PR #534 
This should unblock the CI failures on other PRs.
=> fix: add missing bundle updates from #534

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go
/kind bug
Fixes a bug with CMP 2.0 support where the reconciler would panic if there was an existing argocd repo deployment without any init containers
Fixes #586
**How to test**
* Install the operator.
* Install an Argo CD instance
* Edit the repo server deployment and delete the init container
`kubectl edit deployments.apps argocd-repo-server `
* The operator should not panic. Edit the repo server deployment again and check that the init container was added back
=> fix: panic when missing init containers

bundle/manifests/argocd-operator.clusterserviceversion.yaml, common/defaults.go, config/rbac/role.yaml, controllers/argocd/argocd_controller.go, controllers/argocd/keycloak.go, controllers/argocd/keycloak_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go, deploy/olm-catalog/argocd-operator/0.2.0/argocd-operator.v0.2.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml, docs/reference/argocd.md, docs/usage/keycloak/openshift.md, examples/argocd-keycloak-openshift.yaml, hack/test.sh, kuttl-test-keycloak.yaml, kuttl-test-rhsso.yaml, tests/e2e-keycloak/argocd-tests/01-argocd-keycloak.yaml, tests/e2e-keycloak/argocd-tests/01-assert.yaml, tests/e2e-keycloak/argocd-tests/99-delete.yaml, tests/e2e-rhsso/argocd-tests/01-argocd-rhsso.yaml, tests/e2e-rhsso/argocd-tests/01-assert.yaml, tests/e2e-rhsso/argocd-tests/02-sleep.yaml, tests/e2e-rhsso/argocd-tests/03-verify-oidc.yaml, tests/e2e-rhsso/argocd-tests/04-verifyRealmCreation.yaml, tests/e2e-rhsso/argocd-tests/99-delete.yaml
**This PR adds the below enhancements.**
-------------------------------------------
* Added missing RBAC annotations in `agocd_controller.go`: `template.openshift.io` and `oauth.openshift.io` api groups. Without these annotations, RBAC manifests won't get generated properly in order to install RHSSO.
* Removed hardcoded OIDC client secrets and replaced them by generated random strings. These client secrets do not need to be stored. 
* Added `KeycloakIdentityProviderMapper` to workaround https://github.com/keycloak/keycloak-operator/issues/471. Without the workaround, tokens can't be translated to credentials that contain the group identity.
* Propagated proxy environment variables from operator to …
=> feat: Upgrade RH-SSO to v7.5.1 and support kube:admin, ocp groups and proxy env

bundle/manifests/argoproj.io_applicationsets.yaml, common/defaults.go, config/crd/bases/argoproj.io_applicationsets.yaml, deploy/olm-catalog/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_applicationsets.yaml
> /kind chore
upgrades appsets to v0.4.1
upgrades appsets to v0.4.1
1. Run the operator locally using `make install run`
2. Deploy the below Argo CD CR.
```
kind: ArgoCD
metadata:
labels:
example: autoscale
spec:
applicationSet: {}
server:
ingress:
enabled: true
```
3. Wait for a minute for operator to reconcile the Argo CD resource and create its workloads.
4. Use the below command to verify the ApplicationSet version.
`kubectl describe deployment …
=> [0.3.0] upgrades appsets to v0.4.1

bundle/manifests/argoproj.io_applicationsets.yaml, common/defaults.go, config/crd/bases/argoproj.io_applicationsets.yaml, deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_applicationsets.yaml
> /kind chore
upgrades appsets to v0.4.1
upgrades appsets to v0.4.1
1. Run the operator locally using `make install run`
2. Deploy the below Argo CD CR.
```
kind: ArgoCD
metadata:
labels:
example: autoscale
spec:
applicationSet: {}
server:
ingress:
enabled: true
```
3. Wait for a minute for operator to reconcile the Argo CD resource and create its workloads.
4. Use the below command to verify the ApplicationSet version.
`kubectl describe deployment …
=> upgrades appsets to v0.4.1

controllers/argocd/secret.go, controllers/argocd/secret_test.go
/kind bug
While reconciling cluster permissions, every time the Secret was deleted if the secret belongs to a cluster config instance.
In this PR, we are updating the logic to not delete the Secret, but to remove the `namespaces` field from the Secret.
Fixes [GITOPS-1777](https://issues.redhat.com/browse/GITOPS-1777)
* build operator out of this branch
* create Argo CD instance
* Enable route for Argo CD instance to be able to access UI
* Log in to Argo CD UI -> Settings -> Clusters, edit the existing cluster to see the Secret getting created
* Update ArgoCD instance to add a …
=> bug: update workflow to avoid deleting Secrets while reconciling cluster permissions

docs/requirements.txt
/kind chore
Fix builds of readthedocs by pinning jinja2 version.
Builds are failing with the below error on Readthedocs.
```
Traceback (most recent call last):
File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/docs/checkouts/readthedocs.org/user_builds/argocd-operator/envs/latest/lib/python3.7/site-packages/mkdocs/__main__.py", line 221, in <module>
cli()
File …
```
=> chore: Fix readthedocs builds

controllers/openshift/openshift.go
> /kind bug
> /kind chore
Adds permissions for managing `monitoring.coreos.com` resources to the `argocd-application-controller` role in order for argocd-operator to create `prometheusRules` (if there is one included in any application that is being managed by any argo-cd instance controlled by the argocd-operator)
Fixes https://issues.redhat.com/browse/GITOPS-1638
**How to test changes / Special notes to the …
=> feat: add permissions to manage monitoring resources

common/defaults.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go
Enables probes on dex container which ensures instance is running properly.
It has been observed in some circumstances that dex becomes unhealthy and requires manual deletion of the pod to bring it back into working order
=> Added probes to Dex container

controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go
Signed-off-by: saumeya <saumeyakatyal@gmail.com>
/kind bug
There is a known issue in Kubernetes (https://github.com/kubernetes/kubernetes/issues/67250) where, if the pods created by StatefulSets fail then they don't get restarted on their own unless manually deleted. This PR adds the deletion in the operator itself, so that it can fetch such a broken pod and restart it.
Fixes #?
1. Run the operator using `make intall` and `make run`
2. In the Application Controller StatefulSet, update the image to any broken url, this will recreate the bug and the `application-controller` pod …
=> fix: delete broken pods of statefulSets

docs/reference/api.html.md
/kind bug
Docs incorrectly use URL instead of host, this will fix it. 
Fixes #601 
N/A
=> Fix docs to say host instead of URL

common/defaults.go
> /kind chore
Fixes [CVE-2021-36159](https://alpinelinux.org/posts/Alpine-3.14.1-released.html) and [CVE-2021-3711](https://www.alpinelinux.org/posts/Alpine-3.14.2-released.html)
Fixes [CVE-2021-36159](https://alpinelinux.org/posts/Alpine-3.14.1-released.html) and [CVE-2021-3711](https://www.alpinelinux.org/posts/Alpine-3.14.2-released.html)
Install and run the operator using `make install run`
Create an Argo CD instance using 
```
kind: ArgoCD
metadata:
labels:
example: ingress
spec:
server:
ingress:
enabled: true …
```
=> chore: update dex version to v2.30.3

controllers/argocd/hooks_test.go, controllers/argocd/policyrule.go, controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/rolebinding_test.go, controllers/argocd/service_account.go, controllers/argocd/service_account_test.go
/kind chore
Fixes #? [GITOPS-1854](https://issues.redhat.com/browse/GITOPS-1854)
=> chore: cleanup reconcilation of roles, role bindings, service accounts

controllers/argocd/role.go
/kind bug
The reconciliation process has entered a continuous loop with #605 . This PR fixes the function call that was used for reconciling cluster roles.
Fixes #?
* Start the operator using `make install run`
* Create an argocd instance using below command
```
cat <<EOF | kubectl apply -f -                                                                    
kind: ArgoCD
metadata:
name: argocd
spec: {}
EOF
```
* check if all pods are running and READY status is 1/1
```
$ kubectl get pods
NAME                                  READY   STATUS …
```
=> bug: fix continuous reconciliation of resources

controllers/argocdexport/reconcile.go
/kind chore
CronJob has been deprecated in v1.21+, and unavailable in v1.25+.
References of CronJob were updated to use "batch/v1" in PR #477 but couple of places were missed out.
Updating missed places to use "batch/v1" for CronJob.
Fixes #?
https://issues.redhat.com/browse/GITOPS-1940
- make install run
- make test
All tests should pass successfully.
=> update deprecated cronjob reference

controllers/argocd/argocd_controller.go, controllers/argocd/argocd_controller_test.go, controllers/argocd/deployment.go, docs/usage/custom_roles.md
This PR introduces a new environment variable "REMOVE_MANAGED_BY_LABEL_ON_ARGOCD_DELETION", and changes the default behave on namespace with "managed-by" label when the target Argo CD instance gets removed by the gitops-operator. By default, when the Argo CD instance with the target namespace gets deleted, the namespace keeps "managed-by" label value. Only when "REMOVE_MANAGED_BY_LABEL_ON_ARGOCD_DELETION" is set to "true" in the Subscription config, it will remove the "managed-by" label on Argo CD deletion.
Fixes https://issues.redhat.com/browse/GITOPS-1826
> …
=> feat: added env variable to remove managed-by label on argocd instance deletion

api/v1alpha1/argocd_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, deploy/olm-catalog/argocd-operator/0.4.0/argoproj.io_argocds.yaml, docs/usage/extra-config.md, mkdocs.yml, tests/k8s/1-018_validate_extra_config/01-argocd-with-extraconfig.yaml, tests/k8s/1-018_validate_extra_config/01-assert.yaml, tests/k8s/1-018_validate_extra_config/02-argocd-with-firstclass-and-extraconfig copy.yaml, tests/k8s/1-018_validate_extra_config/02-assert.yaml, tests/k8s/1-018_validate_extra_config/03-assert.yaml, tests/k8s/1-018_validate_extra_config/03-update-configmap.yaml, tests/k8s/1-018_validate_extra_config/04-assert.yaml, tests/k8s/1-018_validate_extra_config/04-create-dex-without-extraconfig.yaml, tests/k8s/1-018_validate_extra_config/05-assert.yaml, tests/k8s/1-018_validate_extra_config/05-override-dex-using-extraconfig.yaml
Problem Statements
As the Argo CD upstream project evolves, new features are continuously added and new config-cm configurations are constantly introduced. Argocd Operator is virtually impossible to keep up with Argo CD’s new configurations. Argocd Operator is lagging behind to support new Argo CD features in months or more
Oftentimes to support a new feature, it is as simple as reconciling a config-cm entry. For example,https://github.com/argoproj-labs/argocd-operator/pull/598 introduced a map entry application.resourceTrackingMethod. However, the code to make this a first class configuration as a field Argocd CR required to touch 10+ files. It takes quite  a bit of engineering effort to reconcile …
=> feat: Add support for ExtraConfig in Argo CD CRD

api/v1alpha1/argocd_types.go, build/redis/haproxy.cfg.tpl, build/redis/init.sh.tpl, build/redis/redis.conf.tpl, build/redis/redis_liveness.sh.tpl, build/redis/redis_readiness.sh.tpl, build/redis/sentinel.conf.tpl, build/redis/sentinel_liveness.sh.tpl, bundle/manifests/argoproj.io_argocds.yaml, common/values.go, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/applicationset_test.go, controllers/argocd/configmap.go, controllers/argocd/custommapper.go, controllers/argocd/custommapper_test.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, controllers/argocd/secret.go, controllers/argocd/secret_test.go, controllers/argocd/service.go, controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go, deploy/olm-catalog/argocd-operator/0.4.0/argoproj.io_argocds.yaml, docs/reference/argocd.md, tests/k8s/1-007_validate_volume_mounts/01-assert.yaml
This PR adds support to watch for changes to the `argocd-operator-redis-tls` secret, which should contain the TLS configuration (cert/key combination) that the argocd components should use to communicate with the redis server. If a change is detected, the appropriate workloads will be restarted.  Note that this secret is something defined by the operator and not by Argo CD itself.
The PR adds two new settings
-  `.spec.redis.disableTLSVerification: <bool>`: if set to `true`, the application controller, the repo server and the api server will not validate the TLS certificate used by the redis server (by setting the `--redis-insecure-skip-tls-verify` flag when starting these components).
- …
=> feat: Secure communication with redis

controllers/argocd/configmap.go
> /kind bug
As part of the [PR](https://github.com/argoproj-labs/argocd-operator/pull/642), I have refactored the Argo CD config map reconciliation logic and made it simpler. @rishabh while integrating the changes into DownStream(openshift-gitops) noticed that OIDC configuration is not getting updated when `.spec.SSO.provider` is set to Keycloak.
I could have caught this by testing the PR on OpenShift platform. There is an existing test to validate the changes.
`1-001_validate_rhsso`
This PR will fix the issue.
NA
1. Run the operator locally.
2. Run …
=> fix: operator overrides the OIDC configuration for Keycloak

build/util/Dockerfile, common/defaults.go, docs/reference/argocd.md, go.mod, go.sum
> /kind bug
Fixes **CVE-2022-29165**
```
A critical vulnerability has been discovered in Argo CD which would allow unauthenticated users to impersonate as any Argo CD user or role, including the admin user, by sending a specifically crafted JSON Web Token (JWT) along with the request. In order for this vulnerability to be exploited, [anonymous access](https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#anonymous-access) to the Argo CD instance must have been enabled.
In a default Argo CD installation, anonymous access is disabled. To find out if anonymous access is enabled in your instance, please see the Workarounds section of this advisory …
```
=> fix: upgrade Argo CD to handle CVE-2022-29165

controllers/argocd/util_test.go
/kind chore
As part of PR: https://github.com/argoproj-labs/argocd-operator/pull/647 I inadvertently committed an invalid unit test.  This PR is to remove that test.
Run `REDIS_CONFIG_PATH="$PWD/build/redis" make test`.  The tests should complete without errors.
=> chore: remove invalid unit test

tests/k8s/1-005_validate-custom-argocd-namespace/02-assert.yaml
After updating to use argocd 2.4-rc2, the `1-005_validate-custom-argocd-namespace` e2e test started failing most of the time, with an occasional successful run.
The problem seems to be that when the test creates the application CR, the repo server is not yet ready, and so argocd backs off and waits to retry the sync.  For some reason it seems to be backing off for longer than before.
The current timeout for the test is 300 seconds.  After running the test case multiple times with a timeout of 600 seconds, I see that most of the time the test is taking around 400 seconds to complete successfully, with the occasional run completing in under 300 seconds.
This PR increases the timeout …
=> chore: fix flaky e2e test

controllers/argocd/util.go, controllers/argocd/util_test.go
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>
/kind bug
> /kind bug
> /kind chore
since k8s v1.24 secret is not auto mounted to SA , dex creation fails as oauth client used for dex is service account. This PR creates a token and adds the token to service account
Fixes  [326](https://github.com/redhat-developer/gitops-operator/issues/326)
Run this on …
=> fix: mount secret to service account for dex if its not there

controllers/argocd/keycloak.go, controllers/argocd/keycloak_test.go, controllers/argocd/sso.go, controllers/argocd/sso_test.go
/kind bug
> /kind chore
adds check for nil pointer error when generating keycloak conflig for openshift 
Fixes #?
=> fix: nil pointer error for keycloak on openshift

controllers/argocd/role.go, controllers/argocd/rolebinding.go, tests/k8s/1-019_validate_rolebindings_with_managed_by/01-assert.yaml, tests/k8s/1-019_validate_rolebindings_with_managed_by/01-basic.yaml, tests/k8s/1-019_validate_rolebindings_with_managed_by/02-argocd-instance.yaml, tests/k8s/1-019_validate_rolebindings_with_managed_by/02-assert.yaml
/kind bug
Fixes [GITOPS-1963](https://issues.redhat.com/browse/GITOPS-1963) issue.
Fixes #GITOPS-1963 Operator does not create necessary RoleBindings in all cases
a. $ oc create namespace central-argocd
b. $ oc create namespace argocd-1
c. $ oc label ns argocd-1 [argocd.argoproj.io/managed-by=central-argocd](http://argocd.argoproj.io/managed-by=central-argocd)
d. $ oc project central-argocd
e. $ oc apply -f argocd-basic.yaml
f. $ oc get roles -n central-argocd 
Now observe that all 4 roles/rolebindings including dex and redis service are created for central-argocd ns
=> fix: Operator does not create necessary RoleBindings in all cases

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go
> /kind bug
Redis Image upgrade is not work as expected. There is an issue with the current implementation that does not allow the operator to upgrade the redis image.
This PR will fix the above issue.
NA
1. Run the below UnitTest
`/usr/local/go/bin/go test -timeout 30s -run ^TestReconcileArgoCD_reconcileRedisDeployment_testImageUpgrade$ github.com/argoproj-labs/argocd-operator/controllers/argocd`
or
2. Run the operator locally using `make install run`
- Create an Argo CD instance.
- Stop the operator
- Rerun the operator using the below command …
=> fix: issue with redis image upgrade

controllers/argocd/notifications_util.go
/kind bug
> /kind chore
Spacing issue in the `on-sync-succeeded` trigger configuration in `argocd-notifications-cm` throws an invalid JSON request, which blocks notifications from being sent out on successful app sync. This PR fixes that 
Fixes #?
=> fix: minor spacing issue in trigger configuration blocks notifications from being sent out

controllers/argocd/deployment.go
kind enhancement
Passes the cluster version to the reconcilerHook when reconciling the Redis haproxy deployment.  This is to allow the behaviour of the hook to be based on the OpenShift version that the operator is running on.
Fixes #?
=> fix: pass cluster version to haproxy reconciler hook

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, controllers/argocd/util.go
/kind bug
This PR aims to identify all the fields of RepoServer and ensures as CR changes for repo server fields new deployment is triggered with updated values
As a part of PR have seen all fields  of spec.Repo
logLevel, logFormat, image, version are reconciled as a part of init containers 
reconcilation on change for env, volumes, volumeMounts, initContainers is already present
sidecarContainers are reconciled as a part of comtainers
left with two fields  mountSAToken, serviceaccount reconiclation logic is in this PR
Fixes #?
1) Make default deployment of ArgoCD via operator
2) …
=> Fix: reconcile repo server on mountSAToken and mountSAToken Name change setting

bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/default/manager_config_patch.yaml, config/manager/manager.yaml, deploy/olm-catalog/argocd-operator/0.4.0/argocd-operator.v0.4.0.clusterserviceversion.yaml
/kind bug
> /kind chore
Adds security context for operator pods
Fixes #663 
=> Added security context for deployment operator

.github/workflows/ci-build.yaml
/kind chore
Currently, the output of e2e tests is only redirected to a log file. With this change, the logs will also be displayed on the console
Fixes #?
=> chore: Redirect e2e test logs to both stdout and log file

controllers/argocd/secret.go, controllers/argocd/secret_test.go
/kind bug
This PR makes the following changes.
1) If argocd-secret does not exist (has been deleted) , the reconciler recreates the secret and regenerates a new server session key.
2) When the admin password changes, the reconciler adds the new password hash to the argocd_secret.
When .data field has been deleted from argocd-secret and get regenerated, this fixes a bug where argocd login no longer works afterwards. 
https://issues.redhat.com/browse/GITOPS-2006
Verifying the error behavior: 
- checkout to recent version of master branch `git checkout master`
- Run `make …
=> fix: argocd login won't crash when .data is repopulated in argocd-secret

api/v1alpha1/argocd_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/ingress.go, controllers/argocd/ingress_test.go, controllers/argocd/keycloak.go, deploy/olm-catalog/argocd-operator/0.4.0/argoproj.io_argocds.yaml, docs/reference/argocd.md
This PR adds IngressClass support to Ingress resources.
Fixes #626
Relevant tests can be run by the following command:
```shell
go test -v -run 'TestReconcileArgoCD_reconcile_.*Ingress_ingressClassName' ./controllers/argocd/
```
Change can be tested by setting up a dev environment and applying the following manifest:
```yaml
kind: ArgoCD
metadata:
labels:
example: ingress
spec:
server:
grpc:
ingress:
enabled: true
ingress:
enabled: true
ingressClassName: nginx
insecure: true
```
**Note:** As discussed in …
=> feat: Support Ingress Class Annotation in Argo CD CRD

controllers/argocd/deployment.go, controllers/openshift/openshift.go, controllers/openshift/openshift_test.go
/kind bug
Backport fix for haproxy crash on openshift to 0.2
Fixes #?
=> fix: backport haproxy crash fix to 0.2

controllers/argocd/deployment.go, controllers/argocd/policyrule.go, controllers/argocd/role.go, controllers/argocd/rolebinding.go, controllers/argocd/service_account.go
/kind bug
Backport adding policy rules for redis for OpenShift to 0.2
Fixes #?
=> Fix: backport adding policy rules for redis for OpenShift to 0.2

controllers/argocd/deployment.go, controllers/argocd/policyrule.go, controllers/argocd/role.go, controllers/argocd/rolebinding.go, controllers/argocd/service_account.go
/kind bug
Backport adding policy rules for redis for OpenShift to 0.3
Fixes #?
=> Fix: backport adding policy rules for redis for OpenShift to 0.3

controllers/argocd/dex.go, controllers/argocd/dex_test.go
/kind bug
Fixes https://github.com/redhat-developer/gitops-operator/issues/132
Removing the `ImagePullPolicy` in dex deployment
The default policy of `IfNotPresent` property will be used in the deployment.
Fixes #?
=> fix: imagePullPolicy in dex deployment

controllers/argocd/statefulset.go
Signed-off-by: saumeya <saumeyakatyal@gmail.com>
/kind bug
According to the upstream PR - https://github.com/argoproj/argo-cd/pull/9557. This PR updates the statefulset in the operator 
This will be backported to previous versions after merge
```make install run```
=> fix: remove liveness probe from application controller statefulset

bundle/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/prometheus/monitor.yaml, config/rbac/auth_proxy_service.yaml, deploy/olm-catalog/argocd-operator/0.5.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml, deploy/olm-catalog/argocd-operator/0.5.0/argocd-operator.v0.5.0.clusterserviceversion.yaml
> /kind bug
Fixes #750 
NA
Fixes #750 
Closes #750 
1. Build the operator using the steps mentioned [here](https://argocd-operator.readthedocs.io/en/latest/contribute/development/#bundle).
2. Publish the operator to your OpenShift Cluster.
3. Install the Operator from operatorhub console.
4. Wait for the operator to create resources.
5. Check the operator pod label is now updated to `control-plane: argocd-operator`.
=> fix: operator resources should have unique labels.

controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/rolebinding_test.go
> /kind bug
Fixes #755 
Closes #755 
NA
Fixes #755 
Steps to reproduce:
**Prerequisite**:
Run the operator locally using `make install run`
1) Install namespace-scoped Argo CD:
kubectl create ns gitops-service-argocd
kubectl apply -f https://raw.githubusercontent.com/redhat-appstudio/infra-deployments/main/components/gitops/staging/argo-cd.yaml
kubectl apply -f https://raw.githubusercontent.com/redhat-appstudio/infra-deployments/main/components/gitops/staging/allow-argocd-to-manage.yaml
2) Create a Namespace managed by …
=> fix: terminating namespaces blocks new managed Argo CD namespaces

api/v1alpha1/argocd_types.go, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/keycloak.go, controllers/argocd/sso.go, deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_argocds.yaml, docs/reference/argocd.md, docs/usage/keycloak/kubernetes.md, docs/usage/keycloak/openshift.md, examples/argocd-keycloak-k8s.yaml, examples/argocd-route.yaml, tests/ocp/1-001_validate_rhsso/01-argocd-rhsso.yaml, tests/ocp/1-001_validate_rhsso/03-verify-oidc.yaml, tests/ocp/1-001_validate_rhsso/04-verifyRealmCreation.yaml, tests/ocp/1-001_validate_rhsso/99-delete.yaml
> /kind bug
Single Sign On with GitOps Operator can fail with the error message "x509: certificate signed by unknown authority" under the following circumstances:
You are using RHSSO (KeyCloak) as SSO provider and You are using a self-signed certificate for your route endpoints, or you are using a private CA to issue certificates.
This behavior is a result of a [security fix](https://github.com/argoproj/argo-cd/security/advisories/GHSA-7943-82jg-wmw5) in Argo CD, which enforces a strict validation of TLS certificates on the configued OIDC endpoints.
**Workaround & Mitigation**
There are multiple workarounds available:
For Argo CD Operator 0.4.0, you can disable TLS validation for the OIDC (Keycloak/RHSSO) endpoint in …
=> fix: Keycloak/RHSSO login yields in certificate signed by unknown authority 

controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/rolebinding_test.go
> /kind bug
Fixes #755 
Closes #755 
NA
Fixes #755 
Steps to reproduce:
**Prerequisite**:
Run the operator locally using `make install run`
1) Install namespace-scoped Argo CD:
kubectl create ns gitops-service-argocd
kubectl apply -f https://raw.githubusercontent.com/redhat-appstudio/infra-deployments/main/components/gitops/staging/argo-cd.yaml
kubectl apply -f https://raw.githubusercontent.com/redhat-appstudio/infra-deployments/main/components/gitops/staging/allow-argocd-to-manage.yaml
2) Create a Namespace managed by …
=> [v0.3.x] fix: terminating namespaces blocks new managed Argo CD namespaces

api/v1alpha1/argocd_types.go, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/keycloak.go, controllers/argocd/sso.go, docs/reference/argocd.md, docs/usage/keycloak/kubernetes.md, docs/usage/keycloak/openshift.md, examples/argocd-keycloak-k8s.yaml, tests/ocp/1-001_validate_rhsso/01-argocd-rhsso.yaml, tests/ocp/1-001_validate_rhsso/03-verify-oidc.yaml, tests/ocp/1-001_validate_rhsso/04-verifyRealmCreation.yaml, tests/ocp/1-001_validate_rhsso/99-delete.yaml
> /kind bug
Single Sign On with GitOps Operator can fail with the error message "x509: certificate signed by unknown authority" under the following circumstances:
You are using RHSSO (KeyCloak) as SSO provider and You are using a self-signed certificate for your route endpoints, or you are using a private CA to issue certificates.
This behavior is a result of a [security fix](https://github.com/argoproj/argo-cd/security/advisories/GHSA-7943-82jg-wmw5) in Argo CD, which enforces a strict validation of TLS certificates on the configued OIDC endpoints.
**Workaround & Mitigation**
There are multiple workarounds available:
For Argo CD Operator 0.4.0, you can disable TLS validation for the OIDC (Keycloak/RHSSO) endpoint in …
=> [v0.4.x] fix: Keycloak/RHSSO login yields in certificate signed by unknown authority 

api/v1alpha1/argocd_types.go, build/util/Dockerfile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_argocds.yaml, common/defaults.go, config/crd/bases/argoproj.io_argocds.yaml, config/manager/kustomization.yaml, controllers/argocd/keycloak.go, deploy/olm-catalog/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_argocds.yaml, docs/reference/argocd.md, docs/usage/keycloak/kubernetes.md, docs/usage/keycloak/openshift.md, examples/argocd-keycloak-openshift.yaml
> /kind bug
Single Sign On with GitOps Operator can fail with the error message "x509: certificate signed by unknown authority" under the following circumstances:
You are using RHSSO (KeyCloak) as SSO provider and You are using a self-signed certificate for your route endpoints, or you are using a private CA to issue certificates.
This behavior is a result of a [security fix](https://github.com/argoproj/argo-cd/security/advisories/GHSA-7943-82jg-wmw5) in Argo CD, which enforces a strict validation of TLS certificates on the configued OIDC endpoints.
**Workaround & Mitigation**
There are multiple workarounds available:
For Argo CD Operator 0.4.0, you can disable TLS validation for the OIDC (Keycloak/RHSSO) endpoint in …
=> [v0.3.x] fix: Keycloak/RHSSO login yields in certificate signed by unknown authority

api/v1alpha1/argocd_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/notifications.go, controllers/argocd/notifications_test.go, deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_argocds.yaml, docs/reference/argocd.md, examples/argocd-notifications.yaml
Fixes #770 
Closes #770 
Fixes #770 
- Run the operator locally using `make install run`
- Create an Argo CD instance with notifications enabled.
```
kind: ArgoCD
metadata:
spec:
notifications:
enabled: True
server:
ingress:
enabled: true
```
- Wait for the Argo CD workloads to be created. Watch for notifications pod to be available.
- Edit the Argo CD CR created above to add env vars.
```
kind: ArgoCD
metadata: …
```
=> feat: add support for env and proxy vars for notificaitons

build/util/Dockerfile
> /kind bug
Fixes #774 
Closes #774 
NA
Fixes #774 
1. I have built a new version of Argo CD Export by updating the DockerFile with AWS CLI installation(Please look for Files Changed Section).
2. Update the `defaults.go` -> 
`ArgoCDDefaultExportJobImage`  -> `quay.io/aveerama/argocd-operator-util`
`ArgoCDDefaultExportJobVersion` -> `sha256:5ed626b270ea3316c831e7945f2f00bb3335490a7e63240442e897b43133bb5d`
3. Run `make install run`
4. Create an Argo CD Instance using
```
kubectl apply -f …
```
=> fix: broken Argo CD Export for AWS (#774)

controllers/argocd/ingress_test.go, controllers/argocd/sso.go, controllers/argocd/sso_test.go, controllers/argocdexport/local.go, controllers/argoutil/resource.go, tests/auxiliary/smtplistener/cmd/listener/serve.go
/kind bug
> /kind chore
This PR updates the logic for SSO related field deprecations in the CR, so that single event is emitted with latest timestamp and CR association so that no. of emitted events is greatly reduced and events have more metadata stored
Fixes #785 
https://issues.redhat.com/browse/GITOPS-2230
1. Run the operator against a cluster
2. Create an …
=> fix: Update sso eventing logic to stop spam

docs/reference/argocd.md
Signed-off-by: saumeya <saumeyakatyal@gmail.com>
Fixes #?
=> doc: add controller env variable examples

controllers/argocd/applicationset.go
Signed-off-by: rjeczkow [rjeczkow@gmail.com](mailto:rjeczkow@gmail.com)
Fixing discrepancy between Applicationset Controller [Pod ContainerPort](https://github.com/argoproj-labs/argocd-operator/blob/master/controllers/argocd/applicationset.go#L227) (8000) and [Service TargetPort](https://github.com/argoproj-labs/argocd-operator/blob/master/controllers/argocd/applicationset.go#L498) (8080) for metrics
/kind bug
Setting ContainerPort for ApplicationSet container to 8080 in order to make it consistent with the ApplicationSet service TargetPort
https://issues.redhat.com/browse/GITOPS-2411
Fixes #?
**How to test changes / Special notes to …
=> Fixing discrepancy between Applicationset Controller Pod ContainerPort (8000) and Service TargetPort (8080) for metrics

controllers/argocd/policyrule.go
/kind chore
add list and watch only for `applications` resources and  for `argoproj.io` apigroups only for cluster role
Fixes #?
=> restrict server clusterrole list and watch permissions to only applications

controllers/argocd/status.go, controllers/argocd/status_test.go, examples/argocd-ingress-openshift.yaml, tests/ocp/1-002_verify_hostname_with_ingress/01-argocd-ingress.yaml, tests/ocp/1-002_verify_hostname_with_ingress/01-assert.yaml, tests/ocp/1-003_verify_hostname_with_route/01-argocd-route.yaml, tests/ocp/1-003_verify_hostname_with_route/01-assert.yaml
> /kind bug
Fixes #816 
Closes #816 
Refer #816 
**Additionally you can also run the newly added automation tests on your OCP platform**
- `kubectl kuttl test ./tests/ocp --config ./tests/kuttl-tests.yaml --test 1-002_verify_hostname_with_ingress`
-  `kubectl kuttl test ./tests/ocp --config ./tests/kuttl-tests.yaml --test 1-003_verify_hostname_with_route`
=> fix: host url for Ingress in the .status feild on OpenShift (#)

build/util/Dockerfile, build/util/entrypoint.sh, build/util/util.sh, docs/usage/export.md, examples/argocdexport-aws.yaml
> /kind bug
Closes #182 
Closes #279 
Closes #596 
NA
Fixes #182 
Fixes #279 
Fixes #596 
1. Pull the PR on to your local and build a export image using `make util-build`
(or)
You can alternatively use the image that I built for testing 
Image - abhishekf5/argocdexportimage
Version - "sha256:c468e2ce7d9c740b6704239fcbc2bfb853c127dbf8b133e322cb2ddc889c84d2"
2. Copy the util image SHA and update to the defaults.go 
- `ArgoCDDefaultExportJobImage`
- `ArgoCDDefaultExportJobVersion`
3. Run the Argo CD Operator using `make …
=> feat: Remove Argo CD as a base Image from the Export Dockerfile

deploy/registry/Dockerfile
Fixes #800 
NA
Fixes #800 
1. Deploy a local Kubernetes cluster with version v1.25.z
2. Add OLM plugin or install OLM (steps vary from distribution to distributions) 
- If you are on minikube, you can install OLM using the minikube addon.
3. Try installing the v0.4.0 of argocd-operator , it should fail with the error mentioned in #800 
4. Replace registry image mentioned below in the `catalogsource` and verify that operator is running.
=> feat: upgrade the registery base image to v1.26.2 (#800)

tests/k8s/1-021_validate_notification_controller/03-add-sleep.yaml
add sleep to notification controller test
Signed-off-by: Jaideep Rao <jaideep.r97@gmail.com>
> /kind bug
> /kind chore
Fixes #?
=> chore: try to fix notification controller flaky test by adding sleep

bundle/manifests/argocd-operator.clusterserviceversion.yaml, common/defaults.go, config/manager/kustomization.yaml, config/manifests/bases/argocd-operator.clusterserviceversion.yaml, deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.5.0/argocd-operator.v0.5.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml, deploy/registry/Dockerfile
> /kind chore
As part of the release process, we update the Release manifests back to the bundle folder.
Please refer to the last point of the below doc
https://argocd-operator.readthedocs.io/en/latest/release-process/
NA
Fixes #?
=> chore: Update Release manifests back to the 0.5.0 bundle folder (#827)

.gitignore, controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go
/kind bug
GITOPS-2480
Fixes GITOPS-2480
1. Create an argocd instance in a namespace which doesn't have cluster admin permission.
2. Run `kubectl get pods -A -v=20` command in the argocd-application-controller terminal.
3. Confirm that there's no `.kube: permission denied` error
=> GITOPS-2480: Added HOME env var to application controller

common/keys.go, controllers/argocd/dex.go, controllers/argocd/secret.go, controllers/argocd/secret_test.go, examples/argocd-openshift-dex.yaml, examples/argocd-route.yaml
This PR will introduce a behavioral change in the way operator configures Dex for OpenShift connector.
Currently, Operator configures dex openshift connector to the Argo CD Instance when `.spec.dex.OpenShiftOAuth: true` && `.spec.provider: dex`. While this configuration works as expected, the oidc configuration which includes the `clientSecret` is placed in the configmap as plain text. This can be a security risk.
Once this PR is merged, operator will provide the reference of the `clientSecret` in the configmap and not the actual secret. Argo CD Server will read this `clientSecret` reference from `argocd-secret`.
The new configuration …
=> feat: read dex clientSecret from argocd-secret

build/util/Dockerfile, common/defaults.go, go.mod, go.sum
Signed-off-by: Regina Scott [rescott@redhat.com](mailto:rescott@redhat.com)
(cherry picked from commit https://github.com/argoproj-labs/argocd-operator/commit/6e748cc94afc5a6881cd230d9087203ede627aca)
What type of PR is this?
/kind chore
What does this PR do / why we need it:
cherry picks https://github.com/argoproj-labs/argocd-operator/pull/865 to release v0.6.0
=> upgrade to argocd v2.6.3 (#865)

controllers/argocd/role.go, controllers/argocd/rolebinding.go, tests/k8s/1-031_validate_handle_terminating_namespaces/01-install.yaml, tests/k8s/1-031_validate_handle_terminating_namespaces/02-delete-ns.yaml, tests/k8s/1-031_validate_handle_terminating_namespaces/03-assert.yaml, tests/k8s/1-031_validate_handle_terminating_namespaces/03-create-app.yaml
Signed-off-by: Jaideep Rao <jaideep.r97@gmail.com>
/kind bug
> /kind chore
**What does this PR do / why we need it**: 
This PR removes the "managed-by" label from a previously managed now terminating namespace, which triggers the removal of this namespace from the argo-cd instance's cluster secret thus unblocking it from deploying resources to other managed namespaces 
This seems like a cleaner approach than directly deleting the namespace from the cluster secret as we already have existing code paths to achieve this that could be triggered …
=> fix: remove managed-by label from terminating namespaces

controllers/argocd/secret.go, tests/ocp/1-004_validate_dex_clientsecret/01-assert.yaml, tests/ocp/1-004_validate_dex_clientsecret/01-install.yaml, tests/ocp/1-004_validate_dex_clientsecret/02-verify-clientsecret.yaml
> /kind bug
This PR will fix the issue with `dex client secret is not updated in the argocd-secret intermittently.`
The actual enhancement of securing the dex client secret (OIDC) is part of #847 
This looks like a race condition or sometimes when operator tries to get the dex client secret from Argo CD dex service account (from the secret named token) the token secret is not created by then. This can be fixed in the reconciliation of existing Argo CD secret which is called much later multiple times.
This is an intermittent behavior and can be reproduced more on the bundle installation rather than the local installation.
NA …
=> [release-0.6] fix: dex client secret is not updated in the argocd-secret intermittently

controllers/argocd/secret.go, tests/ocp/1-004_validate_dex_clientsecret/01-assert.yaml, tests/ocp/1-004_validate_dex_clientsecret/01-install.yaml, tests/ocp/1-004_validate_dex_clientsecret/02-verify-clientsecret.yaml
> /kind bug
This PR will fix the issue with `dex client secret is not updated in the argocd-secret intermittently.`
The actual enhancement of securing the dex client secret (OIDC) is part of #847 
This looks like a race condition or sometimes when operator tries to get the dex client secret from Argo CD dex service account (from the secret named token) the token secret is not created by then. This can be fixed in the reconciliation of existing Argo CD secret which is called much later multiple times.
This is an intermittent behavior and can be reproduced more on the bundle installation rather than the local installation.
NA …
=> fix: dex client secret is not updated in the argocd-secret intermittently

controllers/argocd/secret.go, tests/ocp/1-005_validate_dex_clientsecret_deprecated/01-assert.yaml, tests/ocp/1-005_validate_dex_clientsecret_deprecated/01-install.yaml, tests/ocp/1-005_validate_dex_clientsecret_deprecated/02-verify-clientsecret.yaml
/kind bug
https://github.com/argoproj-labs/argocd-operator/pull/872 moved the actual Dex client secret to the `argocd-secret` and references it from the Dex configuration.
However, the change only considers `.spec.sso.dex` to figure out whether the client secret should be written. There is the (old) way of having Dex configuration in `.spec.dex`, and while being deprecated, is still used in the wild.
This change considers both, existence of `.spec.dex` and `.spec.sso.dex` as the trigger for reconciling the client secret into the `argocd-secret`.
Fixes https://issues.redhat.com/browse/GITOPS-2761
**How to test changes / Special notes to …
=> fix: Reconcile Dex client secret when .spec.dex is set

docs/usage/basics.md, docs/usage/deploy-to-different-namespaces.md, mkdocs.yml
This PR updates the docs w.r.t 
This PR adds docs for the below features
- Default Permissions for a namespace scoped Argo CD Installation
- How to configure an Argo CD instance to cluster scoped
- Default Permissions for a cluster scoped Argo CD Instance
- How to extend the permissions of an Argo CD Instance to deploy additional resources
- How can Argo CD deploy resources to different namespaces
- Install Mkdocs
- Run `mkdocs serve`
=> chore: Add docs for namespace scoped and cluster scoped privileges

controllers/argocd/hpa.go, controllers/argocd/hpa_test.go
/kind bug
> /kind chore
Presently, if `.spec.server.autoscale.enabled` is set, the operator just creates/deletes an hpa. If hpa configuration parameters are changed in `.spec.server.autoscale.hpa` the created hpa is not reconcilied by the operator so the changes don't take effect
Fixes #?
1. Deploy operator
2. create Argo CD CR
3. enable server autoscale and …
=> fix: propagate hpa changes from cr to hpa on cluster

.github/workflows/lint.yaml, .golangci.yml, api/v1alpha1/argocd_types.go, api/v1alpha1/argocdexport_types.go, api/v1alpha1/groupversion_info.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, docs/reference/argocd.md
/kind bug
> /kind chore
Ports the fixes merged into master in #860  to release-0.6 for a situation when the operator overwrites HPA changes in replicas when autoscale is enabled for server
Fixes #?
=> bug: operator interfering with hpa in autoscale mode for server

controllers/argocd/hpa.go, controllers/argocd/hpa_test.go
> /kind bug
> /kind chore
port https://github.com/argoproj-labs/argocd-operator/pull/870 to 0.6 branch
Fixes #?
=> bug: fix proper reconciliation of hpa object

controllers/argocd/configmap.go, docs/reference/argocd.md
/kind chore
This PR adds removal timeline for deprecated `resourceCustomizations`. The `resourceCustomizations` was deprecated in `v0.5.0` and is planned to be removed in `v0.8.0`.
1. Run the operator locally using make install run
2. Create a argocd instance using deprecated `resourceCustomizations` field
> eg: https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#resource-customizations-example
3. Execute `kubectl get events | grep ResourceCustomizations`
4. Observe that deprecation event was emitted
```
9m19s       Warning   DeprecationNotice         argocd/example-argocd …
```
=> chore: Add timeline to remove deprecated resourceCustomizations

bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, deploy/olm-catalog/argocd-operator/0.7.0/argocd-operator.v0.7.0.clusterserviceversion.yaml
/kind bug
This PR fixes installation in environments that require images to be mirrored by digest rather than tag, such as openshift in a "restricted" network install.
Note that this PR includes modifying older CSV versions.  I'm not sure that's kosher.  If not, please free to leave out that part, or kick it back to me for fixing.
N/A
Fixes #510 
Issue #510 includes a description of how to test that the actual problem is fixed.
That said, it's a lot of work. It should also be possible to upgrade an existing installation, and just look at the output of 
```
ns=argocd; # or …
```
=> fix: replace kube-rbac-proxy image tag v0.8.0 with its digest equivalent (#510)

docs/reference/argocd.md, tests/k8s/1-025_validate_resource_ignore_differences/01-argocd-with-resource-ignore-difference.yaml, tests/k8s/1-025_validate_resource_ignore_differences/01-assert.yaml
> /kind bug
This adds system-level configuration documentation that relates to resource customization. 
Also fixes a typo from "deployments" to "Deployment" in some `kind` fields. 
https://issues.redhat.com/browse/GITOPS-2463
=> Add system-level configuration docs and fix minor typo

docs/reference/argocd.md
The reference for argocd does not include extraConfig.  I spent a while looking for something like that.  Issue #858 implies I'm not the only one.
Fixes #858
=> fix: add reference doc for Extra Config (#858)

controllers/argocd/secret.go
=> [release-0.6] fix: Dex resource cleanup when .spec.dex & DISABLE_DEX is set 

api/v1alpha1/argocd_types.go, api/v1alpha1/zz_generated.deepcopy.go, controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go
/kind bug
I've implemented a breaking API change in #926 . This PR reverts the appSync type back to `metav1.Duration` and leaves the API as it was before.
Fixes -
Set the `controller.appSync` value to 1 minute and verify that the controller performs reconciliation every minute instead of the default 3 minutes.
=> fix: Revert appSync type implemented in #926

go.mod, main.go
Our log timestamp is not human readable.
Fixes #?
[GITOPS-2898: Operator logs should have human readable timestamps
](https://issues.redhat.com/browse/GITOPS-2898)
1. Have a k8s cluster running.
2. Go to argocd-operator/ directory and run `make install run`. Observe the timestamps are in RFC3339 format e.g. `2023-06-27T07:12:48-04:00`.
=> Fixed timestamp in log

api/v1alpha1/argocd_types.go, api/v1alpha1/argocdexport_types.go, api/v1alpha1/groupversion_info.go, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_applications.yaml, common/defaults.go, config/manager/kustomization.yaml, deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.7.0/argocd-operator.v0.7.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.7.0/argoproj.io_applications.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
/kind chore
Releasing 0.7.0
Fixes #?
=> Release 0.7

.readthedocs.yml
The build.image config key on .readthedocs.yaml has been deprecated, and will be removed on October 16, 2023. Even though we weren't using it, we still have to have this key otherwise our docs will break. 
I used the same configuration that argocd upstream has: https://github.com/argoproj/argo-cd/blob/master/.readthedocs.yml
=> add build.os config for readthedocs

common/defaults.go, controllers/argocd/keycloak.go, controllers/argocd/keycloak_test.go, docs/reference/argocd.md, examples/argocd-keycloak-openshift.yaml, tests/ocp/1-001_validate_rhsso/01-assert.yaml
RH-SSO 7.5 is deprecated, This PR upgrades the default RH-SSO version from 7.5 to 7.6. 
Fixes #976 
Closes #976 
1. Run the operator locally using `make install run`.
2. Submit the below Argo CD CR, to create Argo CD instance and RH-SSO installation with configuration.
```
kind: ArgoCD
metadata:
spec:
extraConfig:
oidc.tls.insecure.skip.verify: 'true'
sso:
provider: keycloak
keycloak:
rootCA: "---BEGIN---END---"
server:
route:
enabled: true
```
3. Login to the Argo CD via browser, Click on `Login via Keycloak`.
4. Click on `Login with OpenShift`.
5. …
=> feat: upgrade RH-SSO from 7.5 to 7.6

controllers/argocd/argocd_controller.go, controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/sso.go, controllers/argocd/testing.go
This PR removes dead code and unused parms which is causing lint failure in #975.
Fixes following linter errors
```
controllers/argocd/sso.go:34:2: `multipleSSOConfiguration` is unused (deadcode)
multipleSSOConfiguration string = "multiple SSO configuration: "
^
controllers/argocd/testing.go:97:6: `makeTestArgoCDForKeycloakWithDex` is unused (deadcode)
func makeTestArgoCDForKeycloakWithDex(opts ...argoCDOpt) *argoprojv1alpha1.ArgoCD {
^
controllers/argocd/argocd_controller.go:24: File is not `goimports`-ed with -local github.com/argoproj-labs/argocd-operator (goimports)
argoproj "github.com/argoproj-labs/argocd-operator/api/v1alpha1"
controllers/argocd/role.go:34:44: …
```
=> refactor: Remove dead code

api/v1alpha1/argocd_conversion.go, api/v1alpha1/argocd_types.go, api/v1beta1/argocd_types.go, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_argocds.yaml, common/defaults.go, common/keys.go, config/crd/bases/argoproj.io_argocds.yaml, config/manifests/bases/argocd-operator.clusterserviceversion.yaml, controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, controllers/argocd/util.go, deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator.v0.8.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.8.0/argoproj.io_argocds.yaml, docs/reference/argocd.md
/kind refactor
Removes deprecated `.spec.resourceCustomizations` way of customizing resource behaviour from ArgoCD CRD. This field was deprecated in favor of new `resourceHealthChecks`, `resourceIgnoreDifferences`, and `resourceActions`. subkeys introduced in #793.
No conversion support from v1alpha1 to v1beta1 has been added since users were informed about its removal in advance. The value of `.spec.resourceCustomizations` in v1alpha1 will be dropped during the conversion to v1beta1.
=> refactor: Remove deprecated .spec.resourceCustomizations

api/v1beta1/argocd_types.go, bundle/manifests/argoproj.io_argocds.yaml, common/values.go, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/applicationset.go, controllers/argocd/applicationset_test.go, controllers/argocd/argocd_controller.go, controllers/argocd/configmap.go, controllers/argocd/custommapper.go, controllers/argocd/util.go, deploy/olm-catalog/argocd-operator/0.8.0/argoproj.io_argocds.yaml, docs/reference/argocd.md, tests/k8s/1-033_validate_applicationset_tls_scm_volume_mount/01-assert.yaml, tests/k8s/1-033_validate_applicationset_tls_scm_volume_mount/01-install.yaml
ArgoCD recently added support for custom TLS certificates for ApplicationSet Gitlab SCM Providers. ApplicationSetController added a new option `--scm-root-ca-path` and expects the certificate to be mounted on the path specified. As part of this PR, we added a new parameter to `spec.applicationSet.scmRootCaPath` to ArgoCD spec which takes the data from a hard-coded configMap named `argocd-appset-gitlab-scm-tls-certs-cm` containing the certificate and volume mounts it on the applicationset-controller pods on the path specified in `spec.applicationSet.scmRootCaPath`. The PR also adds a watcher on the the configMap to reconcile ArgoCD for any changes to the ConfigMap.
**Have you updated the necessary …
=> Add tls cert mount appset controller

config/crd/kustomization.yaml, config/default/kustomization.yaml, docs/install/manual.md
/kind bug
Deprecation warning from kustomize build:
```shell
$ kustomize build ./config/default
```
The `bases` field was deprecated in [v2.1.0](https://github.com/kubernetes-sigs/kustomize/blob/v2.1.0/docs/v_2.1.0.md#resources-expanded-bases-deprecated), and `patchesStrategicMerge` in [v5.0.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0).
Run `kustomize build config/default` to generate manifests, there is nothing changed.
=> fix: replace deprecated syntax in kustomization.yaml

controllers/argocd/custommapper_test.go, controllers/argocd/keycloak.go, controllers/argocd/secret_test.go, controllers/argocd/testing.go
Follow up PR for https://github.com/argoproj-labs/argocd-operator/pull/999 to replace v1alpha1 references of ArgoCD to v1beta1 in operator-redesign branch.
Change:
Update the ArgoCD API import path & references to use 
- `argoproj` for v1beta1
- `argoprojv1alpha1` for v1alpha1
=> code-refactoring: Replace ArgoCD v1alpha1 references with v1beta1

.github/cherry-pick-bot.yml
This PR adds configuration for GCP cherry pick bot to streamline the process of back-porting PRs to release branches. This bot is already used in upstream argocd for cherry picking changes.
**Bot Usage:**
Any PR which needs to be back-ported can be automated by commenting on the PR with
```
/cherry-pick target-branch-name
```
More details regarding bot can be found [here](https://github.com/googleapis/repo-automation-bots/tree/main/packages/cherry-pick-bot)
[GCP cherry pick bot ](https://github.com/apps/gcp-cherry-pick-bot) is already installed on this repo by argocd org admins.
=> chore: Add gcp cherry-pick bot

build/util/Dockerfile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, common/defaults.go, config/manager/kustomization.yaml, deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator.v0.8.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml, go.mod, go.sum
> /kind chore
Releases argocd-operator 0.8.0
+ also upgrades argocd version to 2.8.4
=> argocd-operator release 0.8.0

build/util/Dockerfile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, common/defaults.go, config/manager/kustomization.yaml, deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml, deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator.v0.8.0.clusterserviceversion.yaml
/kind bug
Forgot to update control plane during last PR
=> update control plane

docs/usage/basics.md
> /kind bug
> /kind chore
This adds a reference for where to find the initial password for the `admin` user when first creating a new `ArgoCD` resource. The `admin.password` in `argocd-secret`, is incorrect and you can't log in as the `admin` user. I found the fix in [this issue](https://github.com/argoproj/argo-cd/issues/3543) and figured the docs should be updated accordingly.
Fixes #78
This was `Closed` but still …
=> doc: Proper reference to where to find default admin password

controllers/argocd/policyrule.go
/kind bug
> /kind chore
Expand argocd-server permissions/rbac to manage applicationsets
JIRA Link: https://issues.redhat.com/browse/GITOPS-3762
Fixed a bug in the RBAC rules within the controllers/argocd/policyrule.go file, particularly within the policyRuleForServer() function. This correction ensures the accurate assignment of permissions for the …
=> Expand argocd-server permissions to manage applicationsets

docs/usage/enabling-disabling-argocd-core-components.md
Documentation for the feature of enabling/disabling the individual ArgoCD core components.
=> Add documentation for enabling/disabling argocd core components

controllers/argocd/util.go, controllers/argocd/util_test.go
/kind bug
Currently, when we set application-controller 'status/operation processor' values below 10, it set it to default value of 10.
This PR allows the value to be less than the default value, but is the value is less or equals to 0 it sets it back to the default value.
Fixes [GITOPS-3770](https://issues.redhat.com/browse/GITOPS-3770)
=> fix logic to allow processor operation to be less than default value

controllers/argocd/notifications.go, controllers/argocd/notifications_test.go
/kind bug
This PR correctly initializes the repo-server address  using `--argocd-repo-server` flag to fix  #1124
```bash
$ argocd-notifications --help 
[...]
--argocd-repo-server string       Argo CD repo server address (default "argocd-repo-server:8081")
```
Fixes #1124
E2e tests are included in #1084. To manually verify the address,
1. create a ArgoCD CR with notifications enabled
```yaml
kind: ArgoCD
metadata:
name: example
spec:
notifications:
enabled: true
```
2. check for `--argocd-repo-server`  flag under `command` in `example-notifications-controller` deployment spec.
3. verify that the …
=> fix: Use correct repo-server address for notification controller

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go
/kind bug
This PR has fix for the issue where operator doesn't delete ServiceAccount from repo-server deployment configurations, if it is deleted from Argo CD CR.
Fixes #?
1. Create Argo CD CR and add a service account in spec.repo.serviceaccount (other than default)
2. Observe repo-server deployment reflecting new service account in serviceAccountName and serviceAccount fields. 
3. Delete spec.repo.serviceaccount field in Argo CD CR.
4. repo-server deployment still has old value, it is supposed to be set to empty.
=> fix: Operator doesn't reflect deletion of SA from repo setting

docs/usage/environment_variables.md, go.mod, main.go
/kind bug
This enables changing logging level of the manager (i.e. operator) based on an environment variable.
* [*] Documentation update is required by this PR.
* [*] Documentation has been updated.
Fixes #1223 
1. Set the log level on the command line prior to running locally, i.e
```
export LOG_LEVEL=warn
make install run
```
2. In Kubernetes/OpenShift set the LOG_LEVEL environment on the Deployment for a Helm deployment or via the Subscription in OLM.
=> Add environment variable to change manager (operator) logging level

tests/k8s/1-034_validate_applicationset_reconcile_enabled_set_false/01-assert.yaml, tests/k8s/1-034_validate_applicationset_reconcile_enabled_set_false/01-errors.yaml
/kind bug
Currently the e2e test `1-034_validate_applicationset_reconcile_enabled_set_false` seems to be working when argocd-controller is running locally, but failing when the test is executed against the cluster. The PR fixes the test flakiness.
* To execute locally:
* Execute `make install run` in argocd-operator.
* In a new tab, execute `kubectl kuttl test ./tests/k8s --config ./tests/kuttl-tests.yaml --test 1-034_validate_applicationset_reconcile_enabled_set_false`
* To run against a cluster:
* Deploy the operator in the cluster. Update your kube context to point to the cluster.
* Execute the test using …
=> fix flaky disable components e2e test

controllers/argocd/policyrule.go
/kind bug
Add the necessary batch permissions to the policy rules for argocd server to support creating batch job
https://issues.redhat.com/browse/GITOPS-3617
Successfully tested through manual verification in Argo CD UI:
* build the argocd-operator images with the changes in this PR, and push to quay.io/username/argocd-operator
* configure a new CustomCatalog in OpenShift, pointing to the above quay.io images
* in OpenShift OperatorHub, search the modified custom argocd-operator, and install it
* create an Argo CD instance under the installed custom argocd-operator
* navigate to …
=> GITOPS-3617 Create Job from Cronjob feature failing with error cannot create resource "jobs"

docs/install/olm.md
link files required for installation and show their content
The installation documentation refers to files only by filename, without mentioning where to find them, linking to them or showing their content. To avoid copy&paste from different pages, it would be convenient and less error-prone to have this all on one page. 
fix #1107 
This is a documentation-only PR.
Fixes #1107 
This contains the fixes for #1106 in the `operatorgroup.yaml` file contained in #1108
=> docs/install/olm.md: link files required for installation

deploy/operator_group.yaml
remove `targetNamespaces` in `deploy/operator_group.yaml`, as this is no longer supported in 0.8.0
fix #1106
(Not sure if bug or documentation?)
/kind bug
> /kind chore
fixes #1106
=> deploy/operator_group.yaml: remove targetNamespaces 

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, controllers/argocd/dex.go
/kind bug
The operator overrides dex connector configuration in argocd-cm upon setting .spec.sso.dex.config in ArgoCD CR. This PR includes the user provided dex config along with the dex connectors. 
Fixes #?
1. Create an Argo CD CR with the dex provider and OpenShiftAuth enabled. Or use the default Argo CD instance in the openshift-gitops namespace.
2. Update the dex config in the CR.
```yaml
provider: dex
dex:
config: |
expiry:
idTokens: "1h"
signingKeys: "12h"
```
3. Ensure that both the connector and the config are present in the argocd-cm.
=> fix: operator shouldn't overwrite dex config 

controllers/argocd/status.go
>  ApplicationSet controller status is Pending even if its Failed which will be misleading for the user
>  Fixed it by adding Failed status field
JIRA LINK - https://issues.redhat.com/browse/GITOPS-2472
=> Add Failed status field for all ArgoCD Controllers

controllers/argocd/ingress.go, controllers/argocd/route.go, controllers/argocd/route_test.go, controllers/argocd/util.go
Fix the failing of webhook route in argocd due to long route name
JIRA link:
https://issues.redhat.com/browse/GITOPSRVCE-794
=> Fix webhook route fail in argocd due to long route name

controllers/argocd/deployment_test.go, controllers/argocd/util_test.go
We want to improve coverage of our unit-tests. This adds a new test for getArgoControllerContainerEnv in simmilar fashion to existing tests of getArgoApplicationControllerCommand.
=> Add containerenv unittest for appsync

controllers/argocd/applicationset.go, controllers/argocd/applicationset_test.go
> /kind bug
The appset controller doesn't consider the `--enable-scm-providers` flag value when set as below in deployment
```yaml
args:
- --enable-scm-providers
- "false"
```
This changes updates the flag to be in following format which is recognized by the controller
```yaml
args:
- --enable-scm-providers=false
```
=> fix: update --enable-scm-providers cmd in appset deployment

controllers/argocd/statefulset_test.go, controllers/argocd/util_test.go
We want to improve the coverage of our unit tests. This adds a new test for `spec.controller.Env`.
Fixes: GITOPS-3220
=> test: Add unittest for spec.controller.Env

controllers/argocd/secret.go, controllers/argocd/secret_test.go
/kind bug
This PR fixes the reset of Argo-cd admin password when updated using cli/dashboard. Argo-cd will reset the password when the data field for admin.password is nil.
Fixes [GITOPS-3581](https://issues.redhat.com/browse/GITOPS-3581)
To check it locally, running k8s cluster
1. Run below command
```
make install run
```
2. On different terminal run 
```
kubectl port-forward service/example-argocd-server 8443:443
```
3. Get login password and perform login 
```
kubectl -n argocd get secret <secret-name> -o jsonpath="{.data.password}" | base64 -d; echo
argocd login --username …
```
=> fix: stop argo-cd secret reseting admin password when updated using cli/dashboard

controllers/argocd/policyrule.go
cherry-pick from #1277
Signed-off-by: Cheng Fang <cfang@redhat.com>
> /kind bug
https://issues.redhat.com/browse/GITOPS-4133
Creating Job from CronJob using ArgoCD UI fails with - cannot set blockOwnerDeletion
=> fix: GITOPS-4133 Creating Job from CronJob using ArgoCD UI fails with - cannot set blockOwnerDeletion

build/util/Dockerfile, bundle/manifests/argoproj.io_applicationsets.yaml, common/defaults.go, config/crd/bases/argoproj.io_applicationsets.yaml, controllers/argocd/dex_test.go, deploy/olm-catalog/argocd-operator/0.9.0/argoproj.io_applicationsets.yaml, go.mod, go.sum
/kind bug
This PR patches below Argo CD CVEs
- CVE-2024-21661 -  Denial of Service Due to Unsafe Array Modification in Multi-threaded Environment
- CVE-2023-50726 - Users with `create` but not `override` privileges can perform local sync 
- CVE-2024-21652 - Bypassing Brute Force Protection via Application Crash and In-Memory Data Loss
- CVE-2024-29893 - uncontrolled resource consumption vulnerability
- CVE-2024-21662 - Bypassing Rate Limit and Brute Force Protection Using Cache Overflow
Argo CD version: v2.10.5 
Argo CD image: https://quay.io/repository/argoproj/argocd?tab=tags
=> fix: Update Argo CD to v2.10.5 to patch multiple Argo CD CVEs

Makefile, build/util/Dockerfile, common/defaults.go, controllers/argocd/dex_test.go, go.mod, go.sum
/kind bug
This PR patches below Argo CD CVEs
https://github.com/advisories/GHSA-6v85-wr92-q4p7 - Denial of Service Due to Unsafe Array Modification in Multi-threaded Environment
https://github.com/advisories/GHSA-g623-jcgg-mhmm - Users with create but not override privileges can perform local sync
https://github.com/advisories/GHSA-x32m-mvfj-52xv - Bypassing Brute Force Protection via Application Crash and In-Memory Data Loss
https://github.com/advisories/GHSA-jhwx-mhww-rgc3 - uncontrolled resource consumption vulnerability
https://github.com/advisories/GHSA-2vgg-9h6w-m454 - Bypassing Rate Limit and Brute Force Protection Using Cache Overflow
Argo CD version: …
=> fix: Update Argo CD to v2.9.10 to patch multiple Argo CD CVEs

bundle/manifests/argocd-operator.clusterserviceversion.yaml, common/defaults.go, config/manager/kustomization.yaml, config/manifests/bases/argocd-operator.clusterserviceversion.yaml, deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.9.0/argocd-operator.v0.9.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
/kind chore
Releases argocd-operator v0.9.0
Fixes #?
=> release for argocd-operator v0.9.0

controllers/argocd/configmap.go, controllers/argocd/dex.go
> /kind bug
In the `reconcileArgoConfigMap` method, if dex is enabled, ConfigMap is updated twice - once in the `reconcileDexConfiguration` method and then outside. There is a chance that the redirect URI is different in both these updates, causing wrong values to be persisted in the configMap. To fix that, setting the same value of dex config in both the updates.
Reproduced the problem in a demo cluster and ensured that the problem is not reproducible with this fix.
Fixes https://issues.redhat.com/browse/GITOPS-4358 …
=> Fix redirect uri

controllers/argocd/deployment.go, controllers/argocd/statefulset.go, controllers/argocd/status.go
/kind bug
When Redis is set to false, the remote field is not being set, and the argocd controller/repo server fall back to the default value of  ```argocd-redis```
```yaml
redis:
enabled: false
remote: 'argocd-dragonfly:6379'
```
When Redis is set to true, the custom remote field is being set, but the redis deployment is also being deployed
```yaml
redis:
enabled: true
remote: 'argocd-dragonfly:6379'
```
Looking at the code,  it seemed simpler to update the condition to be ```enabled + remote``` for a custom endpoint instead of rewriting for ```disabled + remote```.
N/A?
Should I open a Separate Issue?
**How to test changes / Special …
=> fix(Redis): Custom Endpoint without Deploying Redis

common/keys.go, controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/rolebinding_test.go, docs/usage/custom_roles.md
This WIP PR enables users to define custom roles for cluster scoped instances of Argo CD. This is becoming increasingly important with the addition of the auto-respect RBAC feature added in Argo CD 2.10.
Fixes #1275
Note this also tracked in Red Hat's issue database here: https://issues.redhat.com/browse/GITOPS-2614
Ready for review, note I am a novice Go developer so would recommend close scrunity in case I;m not complying with  Go ideoms anywhere.
=> Add support for custom ClusterRoles (controller,server) for cluster scoped instances

config/crd/kustomization.yaml, controllers/argocd/applicationset/status.go
/kind bug
This PR fix missing notificaionConfiguration.yaml to `crd/kustomation.yaml` and fixes a nil pointer error caused by directly checking if applicationSet is enabled.
Fixes #?
=> fix:  nil pointer err in appset & add missing notification crd in kustomize

controllers/argocd/keycloak.go, controllers/argocd/keycloak_test.go, controllers/argocd/sso.go, controllers/argocd/sso_test.go, controllers/argocd/status.go, controllers/argocd/status_test.go, controllers/argocd/util.go, main.go
/kind bug
Users have the option to disable DeploymentConfig API on their OCP clusters. In such cases, the operator shouldn't watch the DeploymentConfig APIs and shouldn't install Keycloak using Template.
https://docs.openshift.com/container-platform/4.14/installing/cluster-capabilities.html#deployment-config-capability_cluster-capabilities
Fixes https://issues.redhat.com/browse/GITOPS-4489
=> fix: verify DeploymentConfig API when installing keycloak using Template

.github/workflows/lint.yaml, .golangci.yml, build/redis/haproxy.cfg.tpl, build/redis/haproxy_init.sh.tpl, build/redis/init.sh.tpl, build/redis/redis.conf.tpl, build/redis/redis_liveness.sh.tpl, build/redis/redis_readiness.sh.tpl, build/redis/sentinel.conf.tpl, build/redis/sentinel_liveness.sh.tpl, common/defaults.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, controllers/argocd/networkpolicies.go, controllers/argocd/networkpolicies_test.go, controllers/argocd/policyrule.go, controllers/argocd/secret.go, controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go
> /kind bug
Fix CVE-2024-31989
It has been discovered that an unprivileged pod in a different namespace on the same cluster could connect to the Redis server on port 6379. Despite having installed the latest version of the VPC CNI plugin on the EKS cluster, it requires manual enablement through configuration to enforce network policies. This raises concerns that many clients might unknowingly have open access to their Redis servers. This vulnerability could lead to Privilege Escalation to the level of cluster controller, or to information leakage, affecting anyone who does not have strict access controls on their Redis instance. This issue has been patched in version(s) 2.8.19, 2.9.15 and 2.10.10.
**Have you updated …
=> feat: secure redis authentication [CVE-2024-31989]

api/v1alpha1/argocd_types.go, api/v1beta1/argocd_types.go, controllers/argocd/route.go, controllers/argocd/route_test.go, docs/usage/routes.md
- This PR updates the default TLS termination policy of OpenShift Route from passthrough to reencrypt. With this change, OpenShift users could use the default ingress certificates for the argocd server without any explicit modification.
- The user/browser/CLI and the Router will communicate using the ingress certificate. The operator relies on OpenShift Service's CA to generate a self-signed certificate in the argocd-server-tls secret which will be used between the Router and the Argo CD server.
Fixes #?
1. Create an Argo CD CR without specifying the server's …
=> feat: Update the default TLS termination policy to reencrypt 

.github/workflows/lint.yaml, .golangci.yml, build/redis/haproxy.cfg.tpl, build/redis/haproxy_init.sh.tpl, build/redis/init.sh.tpl, build/redis/redis.conf.tpl, build/redis/redis_liveness.sh.tpl, build/redis/redis_readiness.sh.tpl, build/redis/sentinel.conf.tpl, build/redis/sentinel_liveness.sh.tpl, common/defaults.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, controllers/argocd/networkpolicies.go, controllers/argocd/networkpolicies_test.go, controllers/argocd/policyrule.go, controllers/argocd/secret.go, controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go
> /kind bug
Fix CVE-2024-31989
It has been discovered that an unprivileged pod in a different namespace on the same cluster could connect to the Redis server on port 6379. Despite having installed the latest version of the VPC CNI plugin on the EKS cluster, it requires manual enablement through configuration to enforce network policies. This raises concerns that many clients might unknowingly have open access to their Redis servers. This vulnerability could lead to Privilege Escalation to the level of cluster controller, or to information leakage, affecting anyone who does not have strict access controls on their Redis instance. This issue has been patched in version(s) 2.8.19, 2.9.15 and 2.10.10.
**Have you updated …
=> feat: secure redis authentication [CVE-2024-31989] (#1364)

api/v1alpha1/argocd_conversion.go, api/v1alpha1/argocd_types.go, api/v1beta1/argocd_types.go, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/configmap_test.go, controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, controllers/argocd/rolebinding_test.go, controllers/argocd/statefulset.go, controllers/argocd/util_test.go, deploy/olm-catalog/argocd-operator/0.9.0/argoproj.io_argocds.yaml, docs/usage/custom_roles.md
This PR enables user to define custom roles for cluster scoped instances of Argo CD. This is becoming increasingly important with the addition of the auto-respect RBAC feature added in Argo CD 2.10.
**Which issue(s) this PR fixes:**
Fixes https://github.com/argoproj-labs/argocd-operator/issues/1275
Note this also tracked in Red Hat's issue database here: https://issues.redhat.com/browse/GITOPS-2614
**How to test changes / Special notes to the reviewer:**
- Create a namespace and to make it cluster scoped namespace update `ARGOCD_CLUSTER_CONFIG_NAMESPACES` environment variable of Subscription resource. 
- Create ClusterRoles and ClusterRoleBindings for …
=> feat: Add support for custom ClusterRoles (controller,server) for cluster scoped instances

build/redis/sentinel_liveness.sh.tpl, bundle/manifests/argocd-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/argocd/argocd_controller.go, deploy/olm-catalog/argocd-operator/0.9.0/argocd-operator.v0.9.0.clusterserviceversion.yaml
/kind bug
Follow up PR for #1364 to fix redis issues
=> fix: Add net policy rbac and remove auth from sentinel script 

api/v1alpha1/argocd_conversion.go
/kind bug
Fix nil dereference in conversion of SSO.Keycloak field from v1alpha1 to v1beta1:
```
2024/05/27 23:31:07 http: panic serving 10.130.0.2:48878: runtime error: invalid memory address or nil pointer dereference
goroutine 900 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1868 +0xb9
panic({0x1a9be80?, 0x2eb0b90?})
/usr/local/go/src/runtime/panic.go:920 +0x270
github.com/argoproj-labs/argocd-operator/api/v1alpha1.(*ArgoCD).ConvertTo(0xc002eb2900, {0x2031020?, 0xc00216b500})
/go/pkg/mod/github.com/argoproj-labs/argocd-operator@v0.9.0-rc3.0.20240524133052-4047a69a7130/api/v1alpha1/argocd_conversion.go:39 +0x443
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*webhook).convertO …
```
=> Fix panic on SSO Keycloak conversion

controllers/argocd/route.go, controllers/argocd/route_test.go, controllers/argocd/service.go, controllers/argocd/service_test.go
/kind bug
https://github.com/argoproj-labs/argocd-operator/pull/1363 changed the default termination policy from passthrough to reencrypt. However, there could be some users who have configured the old passthrough Route with a custom certificate before the upgrade. We don't want to overwrite their configuration once they upgrade the operator.
This PR introduces logic to update the Route to renencrypt only if the "argocd-server-tls` secret is not present.
Fixes #?
1. Install/Run an older version of the operator that still has Passthrough as default.
2. Verify that the Route is …
=> fix: don't change the default policy to reencrypt if the TLS secret is already present

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go
It is necessary to set the seccompProfile to RuntimeDefault to meet the [PodSecurityStandards of restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted), which will be a common default in clusters.
Otherwise the workloads will be evaluated as baseline and rejected, if not set otherwise in the [namespace metadata](https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-admission-labels-for-namespaces).
Fixes #?
Wrt testing:
Ideally we would set the namespace `metadata.labels` values for argoCD to 
``` …
```
=> Add SeccompProfile for PodSecurityStandards "restricted" to avoid Pod Security Violations on restricted namespaces

Makefile
Adds Podman compatibility to Makefile
I think no doc update is needed for this
Fixes #1298
```bash
make docker-build docker-push
make bundle-build bundle-push
make catalog-build catalog-push
```
with podman or docker installed, both will work
=> Adds podman compatibility in makefile

controllers/argocd/ingress.go, controllers/argocd/ingress_test.go
> Fix update issue in Ingress 
JIRA LINK - https://issues.redhat.com/browse/GITOPS-3412
=> Update ingressClassName of ingress based on ArgoCD ingressClassName

.github/workflows/codegen.yaml, Makefile
/kind chore
- Update `Makefile` to automatically downloaded the specific version of operator-sdk into `(repo root)/bin`
- Update `codegen.yaml` to automatically use the Go version defined in `go.mod`
=> Automatically download correct operator-sdk version to bin dir, if not found

common/keys.go, controllers/argocd/util.go, controllers/argocd/util_test.go, docs/reference/argocd.md, docs/usage/environment_variables.md
/kind bug
* The repo server container image version will now fallback to spec.version before falling back to the default version if spec.repo.version is not set. Otherwise users get in the confusing situation of all the argo pods other than repo running a newer version than the repo server.
* It also fixes some documentation and code comments which were inaccurate after a previous change (#373). Also cleans up the unused field ArgoCDRepoImageEnvName after that change.
Fixes #623 
Added tests for the repo server image and version
=>  fix: Use image configured in spec as fallback before default image for repository server workload

controllers/argocdexport/job.go
/kind bug
argocdexport job was still using service account name same as master branch. As the naming Scheme is updated, this PR updates the SA name for argocdexport jobs.
Fixes #?
=> [ operator Redesign ] fix: argocdexport job using incorrect Service Account

controllers/argocd/sso/status.go
/kind bug
SSO status didn't revert to unknown status if argocd spec.sso is set empty, with this PR if no provider is set for SSO, the default status is set to unknown
Fixes #?
=> [ Operator Redesign ] fix: Argocd sso status resets to Unknow if spec.sso is set to nil

.github/workflows/codegen.yaml, Makefile, docs/install/openshift.md, docs/reference/argocd.md, docs/release-process.md, docs/requirements.txt, docs/usage/appsets-in-any-namespace.md, mkdocs.yml
Cherry-picks #1249, #1282, #1299, #1314, #1351, #1396
=> [code-refactoring] Rebase latest doc & config changes from master

controllers/argocd/applicationset/deployment.go, controllers/argocd/reposerver/deployment.go, controllers/argocd/server/deployment.go
/kind bug
With this PR, the Reconciler will update the `env` for deployment of reposerver and server.
This PR also adds the missing default node selector from server deployment.
Fixes #?
=> [ Operator Redesign ] fix: Reconciler skip's env reconciliation for reposerver and server deployment

common/keys.go, controllers/argocd/redis/deployment.go, controllers/argocd/server/deployment.go, controllers/argocd/sso/dex/deployment.go
/kind bug
This PR adds custom node placement to the deployment of dex, server and Redis 
This PR also updates removes trailing dot from ArgoCDKeyResourceCustomizations variable, as it's used with [dotSep](https://github.com/argoproj-labs/argocd-operator/blob/c8f011d11ef81d8dfba4ec2960aae993e2c6ff6f/controllers/argocd/instance.go#L182)
Fixes #?
=> [ Operator Redesign ] fix:  add custom node placement

controllers/argocd/appcontroller/helper.go
/kind bug
Before this PR, container resource didn't reconcile due to the type mismatch for func GetValueOrDefault, This change returns the resource requirement if it's not nil, And return empty/default resource requirement if nil.
Fixes #?
- run 
`make install run` 
- Run test kuttl k8s test `1-010`
`kubectl kuttl test ./tests/k8s --config ./tests/kuttl-tests.yaml --test 1-010_validate_resource_limit_changes`
=> [ Operator Redesign ] fix: container ResourceRequirements reconciliation 

docs/usage/environment_variables.md
This PR fixes the distorted table for "Environment Variables" [page](https://argocd-operator.readthedocs.io/en/stable/usage/environment_variables/).
Fixes #?
=> fix: doc table for Environment Variables

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, tests/k8s/1-007_validate_volume_mounts/01-assert.yaml
/kind bug
The ArgoCD HA guidelines [1] says:
> argocd-repo-server clones the repository into /tmp (or the path specified in the TMPDIR env variable). The Pod might run out of disk space if it has too many repositories or if the repositories have a lot of files. To avoid this problem mount a persistent volume.
However, with the current behaviour of argocd-operator, it is not possible to override the tmp path: when you attempt to do so, you will see this error in the operator logs:
```
2024-07-16T07:32:47Z ERROR Reconciler error {"controller": "argocd", "controllerGroup": "argoproj.io", "controllerKind": "ArgoCD", "ArgoCD": {"name":"argocd","namespace":"jgw"}, "namespace": "jgw", "name": "argocd", "reconcileID": …
```
=> fix: Allow override of default /tmp volume mount in repo server

docs/reference/argocd.md, docs/usage/ha/redis.md, docs/usage/ha/repo-server.md, mkdocs.yml
This PR adds documentation on how to use persistent volumes to increase repo-server storage. It also adds the missing CR fields for `.spec.repo` in documentation.
=> docs: Document how to use persistent storage for repo server

api/v1alpha1/argocd_conversion.go, api/v1alpha1/argocd_types.go, api/v1beta1/argocd_types.go, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_argocds.yaml, common/defaults.go, common/values.go, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/policyrule.go, controllers/argocd/role.go, controllers/argocd/role_test.go, controllers/argocd/rolebinding.go, deploy/olm-catalog/argocd-operator/0.10.1/argocd-operator.v0.10.1.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.10.1/argoproj.io_argocds.yaml, docs/usage/aggregated_roles.md
This PR enables user to use aggregated cluster roles for application controller in a cluster scoped instances of Argo CD. 
This will create a base cluster role (argocd-argocd-application-controlle) which can inherit permissions from these two other cluster roles.
- argocd-application-controller-view = It configures View permissions.
- gitops-application-controller-admin = It is also an  aggregated cluster role to configures Admin permissions. This can inherit permissions from cluster role that is created by users and add those into base cluster role. 
Fixes #?
This is tracked in Red Hat's issue database here: https://issues.redhat.com/browse/GITOPS-2615
**How to test …
=> feat: Add support for Aggregated ClusterRole for cluster scoped instances

docs/usage/resource_management.md
Fixed example code snippet for setting up `resources` for dex.
Fixes a bug in documentation for how to configure `resources` block for Dex ArgoCD component.
None. This is such a small fix, that I create a PR directly.
The change can be tested by provisioning a new ArgoCD resource and checking that dex got correct resources assigned.
```yaml
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
spec:
sso:
dex:
openShiftOAuth: true
resources:
requests:
cpu: 250m
memory: 128Mi
limits:
cpu: 500m
memory: 256Mi
provider: dex
tls:
ca: {}
```
=> docs: Update resource_management.md

docs/release-process.md
Updates the release documentation to account for new process in community operators repos 
Fixes #?
- check out to PR branch
- run `mkdocs serve`
=> docs: update release process docs

controllers/argocd/applicationset.go, controllers/argocd/applicationset_test.go
/kind bug
Current behaviour doesnt allow image to be overriden by `argocdSpec.image` for applicationset-controller pod, with this PR update application-set  controller image can be overide with priority set `default value < .spec.image < .spec.applicationSet.image`
Fixes https://github.com/argoproj-labs/argocd-operator/issues/1517
=> fix: allow argocd spec.image to override default image for appset controller

Makefile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, common/defaults.go, config/manager/kustomization.yaml, deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.12.0/argocd-operator.v0.12.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
> /kind bug
> /kind chore
Fixes #?
=> Release 0.12.0

controllers/argocd/applicationset.go, controllers/argocd/deployment.go, controllers/argocd/dex.go, controllers/argocd/keycloak.go, controllers/argocd/notifications.go, controllers/argocd/statefulset.go
> /kind bug
[#1288](https://github.com/argoproj-labs/argocd-operator/pull/1288) and [#1493](https://github.com/argoproj-labs/argocd-operator/pull/1493) introduced Pod Security Standards (PSS) to ensure all Argo CD component pods comply with the restricted security policy. However, these changes only apply to new installations.
This PR addresses the gap by adding logic to update existing installations. It ensures that the necessary `securityContext` is applied to existing pods and automatically reconciles any manual changes back to the intended configuration.
Closes #1492 
I performed an upgrade test as follows:
1. Ran `make run` …
=> fix: Add update logic to handle addition of PSS to deployments

.golangci.yml, api/v1alpha1/argocd_conversion.go, controllers/argocd/configmap.go, controllers/argocd/deployment.go, controllers/argocd/ingress.go, controllers/argocd/networkpolicies.go, controllers/argocd/prometheus.go, controllers/argocd/role_test.go, controllers/argocd/route.go, controllers/argocd/secret.go, controllers/argocd/service.go, controllers/argocd/util.go, controllers/notificationsconfiguration/configmap.go
/kind chore
This PR contains the following changes:
* updated `golangci.yml` to remove or replace deprecated linters and obsolete elements;
* fixed errors reported by golangci-lint `golangci-lint has version 1.60.3 built with go1.23.0 from c2e095c on 2024-08-22T21:45:24Z`;
* added `nolint:` annotation to all usages of the deprecated `Grafana` field, to keep using this field without warning until this field is fully removed from argocd crd.
Fixes #?
https://issues.redhat.com/browse/GITOPS-5439
=> chore(lint): update golangci-lint config and fix errors reported by golangci-lint

.github/PULL_REQUEST_TEMPLATE.md
/kind chore
Current PR template uses quote (>) to list all kind values, while it probably intend to use comments so submitters can choose the right PR kind by uncommenting a certain line.
I found the current template a bit confusing. I've seen some PR descriptions still contain all kind lines, or having the selecting kind line as quote.
With the fix in this PR, submitters just need to uncomment the right kind line, leave the rest as is, and the rendered description will only display the selected kind line, while keeping the other kind lines as hidden comments. Submitters can also choose to delete the 2 instruction lines and unused kind lines.
**Which issue(s) this PR …
=> chore: improve pull request template to include kind lines in comments instead of quote

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go
This PR is to fix an issue when operator is upgraded from version <=0.7 to >=0.7, then  ownerReferences in ConfigMap does not update the APIVersion.
/kind bug
https://issues.redhat.com/browse/GITOPS-3772
- Run operator for release <=0.7.
- Create ArgoCD instance.
- Check APIVersion in ownerReferences of ConfigMap, it will be `argoproj.io/v1alpha1`.
- Run operator for release >=0.7. 
- Check APIVersion in ownerReferences of ConfigMap, it should be `argoproj.io/v1beta1`.
=> fix: after upgrade from <0.7 to newer version, ownerReferences in configmaps not updated

controllers/argocd/service.go, controllers/argocd/service_test.go
/kind bug 
This PR adds logic to reconcile any manual changes on Server Service properties.
Fixes #1390
I performed an upgrade test as follows:
1. Ran make run
2. Created an ArgoCD CR.
3. Check the Server Service Type is ClusterIP (by default)
4. Apply 
```yaml
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
labels:
example: basic
spec:
server:
service:
type: NodePort
```
6.Check the Server Service Type is NodePort
=> fix: Add Server Service check to apply the changes in case the service exists

deploy/catalog_source.yaml
/kind bug 
Fixes the incorrect catalog image that points to an invalid argocd-operator image
Fixes #?
Didn't rebuild the bundle, as the current bundle is updated for 0.13 (next) release.
Checked manual installation and works well.
=> fix: catalog source image

controllers/argocd/ingress.go, controllers/argocd/ingress_test.go
/kind bug 
This PR adds logic to reconcile Server Ingress related changes in case it exists previously.
Fixes #558
Fixes: https://issues.redhat.com/browse/GITOPS-5386
I performed an upgrade test as follows:
1. Ran make run
2. Created an ArgoCD CR.
3. Check the Server Service Type is ClusterIP (by default)
4. Do a kubectl apply on something like:
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: ArgoCD
> metadata:
>   name: argocd
> spec:
>   server:
>     ingress:
>       enabled: true
5. Followed by a kubectl apply on something like:
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: ArgoCD
> metadata:
>   name: argocd
> …
=> Fix: Add Server Ingress checks to apply the changes in case it  exists

.github/workflows/ci-build.yaml
/kind failing-test 
PR fixes failing e2e ci due to depricated actions/upload-artifact@v2
=> Fix ci for release-0.10 branch

build/util/Dockerfile, common/defaults.go, go.mod, go.sum
/kind chore 
this PR updates argo-cd version for release 0.12
=> update argocd version from 2.12.3 ro 2.12.4

controllers/argocd/route.go, controllers/argocd/route_test.go, controllers/argocd/util.go
/kind chore 
This PR sends event if insecure fields key and certificates are used for route TLS configuration also adds warning in logs for the same.
Fixes [GITOPS-5517](https://issues.redhat.com/browse/GITOPS-5517)
- run `make install run` on an OpenShift cluster 
- apply the below 
```
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
labels:
example: repo
spec:
server:
route: 
enabled: true
tls: 
certificate: "Y2VydGlmY2F0ZQ=="
key: "cHJpdmF0ZS1rZXk="
insecureEdgeTerminationPolicy: Redirect
termination: reencrypt
```
- check for event created and logs
=> Add warning and send events if key and certificate used for route TLS configuration

common/keys.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go
This PR adds downstream support of argocd-extension in gitops-operator using env var
Fixes [GITOPS-5661](https://issues.redhat.com/browse/GITOPS-5661)
=> add support for image override for argocd-extension

docs/developer-guide/development.md
kind documentation
Guidance especially new contributors on how to run the operator locally.
Fixes #1566
=> docs: update development.md on how to run operator locally against a k8s cluster

build/util/Dockerfile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_applications.yaml, common/defaults.go, config/crd/bases/argoproj.io_applications.yaml, config/manager/kustomization.yaml, deploy/olm-catalog/argocd-operator/0.12.0/argocd-operator.v0.12.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.12.0/argoproj.io_applications.yaml, go.mod, go.sum
/kind chore
Upgrade ArgoCD version to 2.12.7
=> chore: Upgrade argocd version to 2.12.7

.github/workflows/ci-build.yaml, .github/workflows/go.yml, .github/workflows/lint.yaml, .github/workflows/publish.yaml, Dockerfile, go.mod
/kind cleanup
Argo CD 2.13 shipped with latest version of operator is built with golang 1.22
=> chore: Update golang to 1.22

docs/usage/routes.md
Follow up PR for #1547 to add documentation on how to use secrets to configure tls data for Argo CD routes. 
**How to test changes / Special notes to the reviewer:**
=> docs: How to use secrets to configure tls data for Argo CD routes

docs/reference/argocd.md, docs/usage/custom_labels_annotations.md
Fix the code block in custom labels and annotations documentation.
=> docs: Fix code block in custom label doc

docs/reference/notificationsconfiguration.md
Subscription supposed to lowercase and no pipe is need at the end
Notification configuration examples for subscriptions use uppercase letter and do not need to include a "|" at the end, which causes issues.
Fixes #?
=> docs: documentation notifications configuration example

api/v1beta1/argocd_types.go, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_argocds.yaml, common/keys.go, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, deploy/olm-catalog/argocd-operator/0.13.0/argocd-operator.v0.13.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.13.0/argoproj.io_argocds.yaml, docs/usage/respect_rbac.md, mkdocs.yml, tests/k8s/1-045_validate_controller_respect_rbac/01-assert.yaml, tests/k8s/1-045_validate_controller_respect_rbac/01-install.yaml, tests/k8s/1-045_validate_controller_respect_rbac/02-assert.yaml, tests/k8s/1-045_validate_controller_respect_rbac/02-install.yaml, tests/k8s/1-045_validate_controller_respect_rbac/03-errors.yaml, tests/k8s/1-045_validate_controller_respect_rbac/03-install.yaml, tests/k8s/1-045_validate_controller_respect_rbac/04-errors.yaml, tests/k8s/1-045_validate_controller_respect_rbac/04-install.yaml
This PR is to add logic to configure [RespectRBAC feature](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#auto-respect-rbac-for-controller) from Argo CD resource. Now users can configure value in `ConfigMap` via `argocd.spec.controller.respectRBAC` field.
RH issue tracker :- https://issues.redhat.com/browse/GITOPS-5955
=> feat: Add support for respectRBAC configuration.

controllers/argocd/applicationset.go, controllers/argocd/deployment.go, controllers/argocd/statefulset.go, controllers/argocd/util.go, controllers/argocd/util_test.go
/kind bug 
Operator overwrites k8s added labels or annotations. This sometimes results into unexpected behaviour. Eg. A kubectl rollout restart on deployment adds an annotation "kubectl.kubernetes.io/restartedAt" with timestamp. However operator detects this as a config drift and removes the annotations resulting into k8s terminating the rollout due to change in config. This commit fixes the issue by preserving such annotations & labels added onto live object during comparison.
**Special notes to the reviewer:**
This is a regression introduced by #1532
=> fix: update logic to preserve k8s specific labels & annotations

api/v1alpha1/argocd_types.go, api/v1beta1/argocd_types.go, bundle/manifests/argocd-operator.clusterserviceversion.yaml, bundle/manifests/argoproj.io_argocds.yaml, config/crd/bases/argoproj.io_argocds.yaml, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, deploy/olm-catalog/argocd-operator/0.13.0/argocd-operator.v0.13.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/0.13.0/argoproj.io_argocds.yaml, docs/usage/config_management_2.0.md, tests/k8s/1-0017_validate_cmp/02-assert.yaml, tests/k8s/1-0017_validate_cmp/02-cmp2-default-image.yaml, tests/k8s/1-0017_validate_cmp/99-delete.yaml
Make specifying the sidecar image for a config-management plugin optional. When the image is not specified the operator will use the product image being used for the repo server.
=> feat: make specifying config-management sidecar plugin image optional

build/util/Dockerfile, bundle/manifests/argocd-operator.clusterserviceversion.yaml, common/defaults.go, config/manager/kustomization.yaml, deploy/catalog_source.yaml, deploy/olm-catalog/argocd-operator/0.13.0/argocd-operator.v0.13.0.clusterserviceversion.yaml, deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
/kind chore
Release v0.13.0.
I have verified the images by installing operator on a amd64 cluster
=> chore: Release v0.13.0

tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/01-assert.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/01-sourcenamespace_without_wildcard.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/02-assert.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/02-errors.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/02-sourceNamespace_with_wildcard_pattern.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/03-assert.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/03-new_namespace_with_match_pattern.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/04-assert.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/04-sourceNamespace_with_wildcard.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/05-assert.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/05-errors.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/05-multiple_sourcenamespace.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/06-assert.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/06-errors.yaml, tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/06-validate_labels_role_rolebinding_after_removing_namespace_from_sourcenamespace.yaml
/kind cleanup
- Add `-thirtysix` prefix to namespaces (and associated resources), to prevent conflicts with other tests that use these namespace names (`default`, `test`, `dev`, etc)
- This should fix/improve intermittent failures of this test seen in other PRs.
N/A
=> Use unique namespaces in kuttl test 1-036, to avoid conflicts with other tests

controllers/argocd/notifications_util.go
/kind bug
Fix false positives for on-deployed notifications trigger. Refer https://github.com/argoproj/argo-cd/pull/21333 for more details. 
The fix cannot be backported as it depends on a new upstream feature.
=> fix: Stabilize on-deployed notification trigger

tests/k8s/1-036_validate_role_rolebinding_for_source_namespace/04-sourceNamespace_with_wildcard.yaml
Test fix
'1-036_validate_role_rolebinding_for_source_namespace' will fail on step 4 if another namespace on the cluster is in the process of being deleted (e.g. it has a non-nil deletiontimestamp). 
Unfortunately this can occur often in E2E tests, because after each test, that test's namespace is deleted.
The fix is to update the `sourceNamespaces` field to use a pattern that will only match the namespaces created by this test.
When this problem occurs, this is the operator output:
```
2025-01-08T07:46:26Z	INFO	controller_argocd	Creating Role 'kuttl-test-ultimate-ocelot/example-argocd_kuttl-test-ultimate-ocelot'
2025-01-08T07:46:26Z	INFO	controller_argocd	roles.rbac.authorization.k8s.io …
```
=> Fix intermittent failure on 'step 4' of 1-036_validate_role_rolebinding_for_source_namespace

controllers/argocd/applicationset.go, controllers/argocd/applicationset_test.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go
JIRA - https://issues.redhat.com/browse/GITOPS-5200
=> Fix issue in extraCommandArgs field

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, tests/k8s/1-038_validate_controller_extra_command_args/03-remove-extraCommandArgs.yaml
/kind bug
Cherry-pick https://github.com/argoproj-labs/argocd-operator/pull/1635
Fixes #?
Edit redis deployment to remove or modify serviceAccount & serviceAccountName, the changes should not take place and the values should be reset
=> fix: Reconcile serviceAccount fields in redis deployment (#1635)

controllers/notificationsconfiguration/configmap.go, controllers/notificationsconfiguration/configmap_test.go
/kind bug
This PR fix the broken check for context fields in notification configmap and notificationConfiguration CR.
Fixes [GITOPS-5970](https://issues.redhat.com/browse/GITOPS-5970)
- run controller on local using `make install run`
- create an argo-cd instance with notification controller enabled
- create a notificationConfiguraion with single context and check for notification-controller pod logs
- update the context field in the notificationConfiguration with more context and check for notification-controller pod logs, there should not be indefinitely repeated logs similar …
=> fix: broken check for context in notificationController

controllers/argocd/secret.go, controllers/argocd/secret_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go
/kind bug
Currently, the Argo CD operator will update the default cluster Secret after every reconcile, regardless of whether or not the `.data.namespaces` field has actually changed.
This PR updates the logic to only update `.data.namespaces` if the field has changed.
=> Only update Argo CD Cluster secret if the values have changed

controllers/argocd/argocd_controller.go, controllers/argocd/notifications.go, controllers/argocd/notifications_util.go
JIRA - https://issues.redhat.com/browse/GITOPS-5967
=> Add error condition when notification replica is greater than 1

controllers/notificationsconfiguration/configmap.go, controllers/notificationsconfiguration/configmap_test.go
* fix: broken check for context in notificationController
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
* add unit tests
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
* update test
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
---------
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
(cherry picked from commit eace21cb8c21c2c3024da5c4485b99646aed7dc2)
=> [cherry pick] release-0.12 fix: broken check for context in notificationController (#1626)

controllers/notificationsconfiguration/configmap.go, controllers/notificationsconfiguration/configmap_test.go
* fix: broken check for context in notificationController
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
* add unit tests
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
* update test
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
---------
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
(cherry picked from commit eace21cb8c21c2c3024da5c4485b99646aed7dc2)
=> [cherry pick] release-0.13 fix: broken check for context in notificationController (#1626)

controllers/argocd/statefulset.go
/kind bug
This pull request includes a change to the `reconcileRedisStatefulSet` function in the `statefulset.go` file to add a post-start lifecycle hook for the Redis StatefulSet. This hook ensures that the Redis Sentinel is reset after a short delay when the container starts.
Argo-cd:
Issue: https://github.com/argoproj/argo-cd/issues/16360
PR: https://github.com/argoproj/argo-cd/pull/20645
Fixes #1664 
=> fix: Add PostStart lifecycle hook to reset Redis sentinel

controllers/argocd/statefulset.go
Reverts argoproj-labs/argocd-operator#1674
The PostStart hook results into a crashLoopBackOff for state redis when custom certificates are used with redis. Reverting the change for now to unblock the release.
=> revert: "fix: Add PostStart lifecycle hook to reset Redis sentinel"

controllers/argocd/deployment.go
/kind bug
Fix for issue [GITOPS-6495](https://issues.redhat.com/browse/GITOPS-6495)
Error message when starting cmp server with busybox image and a FIPS compliant Argo CD binary.
```
/var/run/argocd/argocd-cmp-server: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```
####Root Cause:
For FIPS compliance, `argocd` binary must be compiled with `CGO_ENABLED=1`, and this mandates it to run with the same OS version in which it was complied so that the libraries linked during compilation are available at runtime as well. So if the binary was compiled in RHEL 8, it may not run on a RHEL 9/10. Since the `argocd-cmp-server` is designed to be run on different images, …
=> Copying argocd-cmp-server binary instead of argocd which can be dynamically linked for FIPS

controllers/argocd/deployment.go
/kind bug
Copy the `argocd-cmp-server` instead of the `argocd` binary which can be compiled dynamically for FIPS compliance and may not run with other container images.
Fixes #?
=> Copying argocd-cmp-server binary instead of argocd which can be dynamically linked for FIPS (#1692)

controllers/argocd/applicationset.go, controllers/argocd/applicationset_test.go, tests/k8s/1-033_validate_applicationset_tls_scm_volume_mount/01-assert.yaml
Fixes: #1689 
This fix Standardize ApplicationSet controller labels
- Update ApplicationSet controller resources to use consistent 'app.kubernetes.io/part-of: argocd' label
- Change from 'argocd-applicationset' to 'argocd' to ali
Fixes #?
=> fix: Standardize 'app.kubernetes.io/part-of' labels across all ArgoCD resources

controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go
**Description**
After upgrading from GitOps 1.15 to 1.16, the redis service account in GitOps 1.16 is assigned lower SecurityContextConstraints (SCC) and the operator fails to update the securityContext of the redis-ha-server StatefulSet. As a result, the container's user is hardcoded instead of being randomly assigned as required by the restricted-v2 SCC. This prevents the new configuration of the StatefulSet from being applied correctly.
**Impact**
The redis-ha-server StatefulSet pods will not be updated with the new settings, causing them to retain old configurations.
**Fixes:**
Ensure the operator updates the securityContext of redis-ha-server/argocd-application-controller StatefulSet after an upgrade.
=>  GITOPS-6759: fix- Redis HA Server StatefulSet SecurityContext Not Updated During Upgrade

api/v1alpha1/argocd_conversion.go, api/v1alpha1/argocd_conversion_test.go, controllers/argocd/applicationset_test.go, controllers/argocd/configmap.go, controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, controllers/argocd/ingress.go, controllers/argocd/prometheus_test.go, controllers/argocd/route.go, controllers/argocd/secret.go, controllers/argocd/service.go, controllers/argocdexport/job.go, controllers/notificationsconfiguration/configmap.go, controllers/suite_testx.go
/kind chore
- This PR fixes a number of warnings within the argocd-operator codebase.
- The main one being 'SA1019', which is reported against our own deprecated APIs.
- We were previously using `//nolint:staticcheck` for this, but `//lint:ignore SA1019 known to be deprecated` appears to be more effective
- Let me know if this differs for you in your IDE of choice (I tested from VS Code)
- Also fixed ginkgo import warning, sprintf warning, and more.
=> Fix linter warnings including deprecation warning SA1019

controllers/argocd/util.go
/kind bug 
At present, you will see the following error in the argocd-operator logs after an `ArgoCD` CR is deleted:
```
2025-04-05T00:43:51-04:00	ERROR	controller_argocd	unable to update status of ArgoCD	{"error": "ArgoCD.argoproj.io \"\" not found"}
github.com/argoproj-labs/argocd-operator/controllers/argocd.(*ReconcileArgoCD).Reconcile
/home/jgw/workspace/argo-cd/argocd-operator/controllers/argocd/argocd_controller.go:103
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
/home/jgw/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler …
```
=> fix: prevent 'unable to update status of ArgoCD' error on deleted CR

controllers/argocd/applicationset_test.go, controllers/argocd/deployment_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go, tests/k8s/1-038_validate_controller_extra_command_args/02-add-extraCommandArgs.yaml, tests/k8s/1-038_validate_controller_extra_command_args/02-assert.yaml, tests/k8s/1-038_validate_controller_extra_command_args/03-errors.yaml
`appendUniqueArgs` func update
- This function merges two slices of CLI arguments (cmd and extraArgs) while avoiding duplication and ensuring correct override behavior.
It handles the following scenarios:
- Preserves argument order, starting with all args from cmd.
- Flags in cmd are treated as non-repeatable — if the same flag appears in extraArgs, it replaces the one from cmd. (To update the existing flags I have added this logic orelse the multiple values for single flag logic will cause bug here)
- Skips duplicate flag+value pairs if already present.
- Allows repeatable flags with different values, only if the flag is not already in cmd. (flags in cmd are preexisting and is non-repeatable)
- Correctly pairs flags with their values (e.g., --flag value).
- …
=> Add support in appendUniqueArgs to allow flag with multiple values

api/v1beta1/argocd_types.go, controllers/argocd/status.go, controllers/argocd/util.go, tests/k8s/1-015_validate_sso_status/05-assert.yaml, tests/k8s/1-042_restricted_pss_compliant/01-install-argocd-in-restricted-pss-ns copy.yaml, tests/k8s/1-042_restricted_pss_compliant/03-assert.yaml, tests/k8s/1-042_restricted_pss_compliant/03-enable-keycloak-sso.yaml, tests/k8s/1-042_restricted_pss_compliant/04-check-pod.yaml, tests/k8s/1-042_restricted_pss_compliant/05-assert.yaml, tests/k8s/1-042_restricted_pss_compliant/05-enable-redis-ha.yaml, tests/k8s/1-048_validate_status_conditions/01-assert.yaml, tests/k8s/1-048_validate_status_conditions/01-install.yaml, tests/k8s/1-048_validate_status_conditions/02-assert.yaml, tests/k8s/1-048_validate_status_conditions/02-install.yaml, tests/k8s/1-048_validate_status_conditions/03-assert.yaml, tests/k8s/1-048_validate_status_conditions/03-install.yaml, tests/k8s/1-048_validate_status_conditions/04-assert.yaml, tests/k8s/1-048_validate_status_conditions/04-install.yaml
/kind bug
This PR is to fix a bug where, ArgoCD `Status.Phase` is not updated properly when `SSO` fails.
Fixes https://issues.redhat.com/browse/GITOPS-6667
=> fix: ArgoCD SSO status is not updated

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go
cherry-pick https://github.com/argoproj-labs/argocd-operator/pull/1667
(cherry picked from commit b1ec29f77a3741f07355d554c7f8ea4e7d3a4528) 
This PR adds logic to preserve the RBAC scope configuration in the RBAC ConfigMap when updating to SSO Keycloak. Previously, it was set to '[groups,email]' in the RBAC ConfigMap without updating the Spec.RBAC.Scopes, which caused a conflict during the ConfigMap sync when switching to Keycloak SSO and updating the ArgoCDConfiguration.
=> [release-0.13] Avoid spec.RBAC.scope sync with rbac configmap when sso keycloak (#1667)

mkdocs.yml
The current docs has a default mkdocs material favicon:
This change fixes that and use the logo that is already present in the docs as the new favicon:
Run the docs locally with `mkdocs serve` and test the favicon is changed
=> docs: Use argocd favicon in docs page

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, controllers/argocd/statefulset.go, controllers/argocd/statefulset_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go, tests/k8s/1-007_validate_volume_mounts/01-assert.yaml, tests/k8s/1-038_validate_controller_extra_command_args/02-assert.yaml, tests/k8s/1-038_validate_controller_extra_command_args/03-errors.yaml, tests/k8s/1-038_validate_controller_extra_command_args/04-errors.yaml
JIRA - https://issues.redhat.com/browse/GITOPS-7009
Steps to test -
Update [this](https://github.com/argoproj-labs/argocd-operator/blob/master/common/defaults.go#L73) value to ArgoCD version 3.0.0  
then apply :
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
spec:
cmdParams:
controller.resource.health.persist: "true"
Create an Application CR to see the CR status of application is working as expected
=> Add default health value in CM to get Health status in the Application CR

controllers/argocd/hooks.go, controllers/argocd/util.go
/kind enhancement 
Currently, the Argo CD CR controller can be imported by different vendor-specific operators. This PR allows the vendor operators to write external hooks and modify the controller-runtime builder of the Argo CD controller. For example, we can apply hooks to add additional watches without modifying the main [SetupWithManager](https://github.com/argoproj-labs/argocd-operator/blob/1739a0112b194f21022ed5ffbb1dc51ad08c86b9/controllers/argocd/argocd_controller.go#L250)
Fixes #?
**How to test changes / Special …
=> feat: modify controller-runtime builder using hooks

Makefile, controllers/argocd/service.go, controllers/argocd/util.go, controllers/argocdagent/deployment.go, controllers/argocdagent/deployment_test.go, controllers/argocdagent/service.go, controllers/argocdagent/service_test.go, controllers/argoutil/resource.go, tests/k8s/1-051_validate_argocd_agent_principal/01-assert.yaml
- Argo CD agent now includes support for proxying redis traffic from principal to agents. This means that it is no longer required to loadbalance the principal redis endpoint.
- This PR removes loadbalancer from principal redis endpoint, and ensures that other workloads reference the redis proxy  (via a new Service)
Fixes #?
=> Argo CD Agent: Add support for redis proxy

Makefile, controllers/argocd/service.go, controllers/argocd/util.go, controllers/argocdagent/deployment.go, controllers/argocdagent/deployment_test.go, controllers/argocdagent/service.go, controllers/argocdagent/service_test.go, controllers/argoutil/resource.go, tests/k8s/1-051_validate_argocd_agent_principal/01-assert.yaml
This is a cherry pick of https://github.com/argoproj-labs/argocd-operator/pull/1788
- Argo CD agent now includes support for proxying redis traffic from principal to agents. This means that it is no longer required to loadbalance the principal redis endpoint.
- This PR removes loadbalancer from principal redis endpoint, and ensures that other workloads reference the redis proxy (via a new Service)
Fixes #?
=> Argo CD Agent: Add support for redis proxy (#1788)

tests/k8s/1-047_validate_impersonation_namespace_scoped_instance/99-delete.yaml
/kind chore
E2E test `1-047_validate_impersonation_namespace_scoped_instance` creates a number of artifacts that don't get cleaned up after the test finishes.  This PR adds the needed cleanup.
=> Cleanup after e2e test 1_047

controllers/argocd/applicationset.go, controllers/argocd/applicationset_test.go, controllers/argocd/argocd_controller_test.go, controllers/argocd/configmap.go, controllers/argocd/configmap_test.go, controllers/argocd/deployment.go, controllers/argocd/dex.go, controllers/argocd/dexUtil.go, controllers/argocd/hpa.go, controllers/argocd/ingress.go, controllers/argocd/networkpolicies.go, controllers/argocd/notifications.go, controllers/argocd/prometheus.go, controllers/argocd/route.go, controllers/argocd/secret.go, controllers/argocd/service.go, controllers/argocd/service_test.go, controllers/argocd/statefulset.go, controllers/argocd/status.go, controllers/argocd/util.go, controllers/argocd/util_test.go, controllers/argocdexport/export.go, controllers/argocdexport/job.go, controllers/argocdexport/local.go, controllers/argoutil/resource.go
/kind bug 
Currently, the `IsObjectFound` utility function is used to check whether a particular object exists on the cluster. It is used across the codebase, and with many different types of objects.
Unfortunately, `IsObjectFound` is making an incorrect assumption: this function assumes that ANY error that occurs (besides is not found) should be treated the same as the object not existing.
For example:
| Cause      | Return value      |
| ------------- | ------------- |
|A) No error on Get object call|`IsObjectFound` returns true|
|B) Not found error on Get object call|`IsObjectFound` returns false|
|C) Any other error occurs on Get object call (network error, permission error, TLS error, etc)|`IsObjectFound` returns …
=> IsObjectFound function should not bury unexpected errors

.readthedocs.yml
/kind bug
Mkdocs builds are failing with error 
> Missing MkDocs configuration key The mkdocs.configuration key is missing. This key is now required, see our [blog post](https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/) for more information.
Fixes #?
=> docs: Fix mkdocs builds

controllers/argocdagent/configmap.go, controllers/argocdagent/deployment.go
/kind bug
This PR is to add few missing env variables from deployment manifest, that were added in configmap later but missed from deployment.
=> fix: add missing env variables in deployment

controllers/argocd/deployment.go, controllers/argocd/deployment_test.go, tests/k8s/1-044_validate_rollout_extension/01-assert.yaml, tests/k8s/1-044_validate_rollout_extension/02-errors.yaml
/kind bug
**Description of the problem**
When Argo Rollouts UI extension was enabled, the init container failed with the following error message
```
++ basename -- file:///home/ext-installer/rollout-extension.tar
+ ext_filename=rollout-extension.tar
++ mktemp -d -t extension-XXXXXX
mktemp: failed to create directory via template '/tmp/extension-XXXXXX': Read-only file system
```
Error message was coming from this line.
https://github.com/rh-gitops-midstream/release/blob/eddad5e34e05bcd548144f65f35152377ec5c21f/containers/argocd-extensions/install.sh#L110
This breaking change was introduced by https://github.com/argoproj-labs/argocd-operator/pull/1659 when the container root file system was made `read-only` using the property setting`readOnlyRootFilesystem: …
=> fix: Argo Rollouts UI extension installation error in initContainer due to read-only access

controllers/argocd/configmap.go, controllers/argocd/configmap_test.go
JIRA - https://issues.redhat.com/browse/GITOPS-6890
As mentioned [here](https://github.com/argoproj-labs/argocd-operator/blob/master/api/v1alpha1/argocd_types.go#L786) customizations field is deprecated in v1beta1  and in the ticket I see they have added customizations - https://github.com/argoproj/argo-cd/pull/21760/files#diff-d4871b2556f24756487ca6be13230ab1bcba17792d8fca91ca138d9b9727f614R13, does this mean this field is not deprecated? If not i will add the logic to add defaults for customizations as well
=> Add default resource.exclusions in ConfigMap

common/defaults.go, controllers/argocdagent/configmap.go, controllers/argocdagent/deployment.go, controllers/argocdagent/deployment_test.go, docs/release-process.md, tests/k8s/1-051_validate_argocd_agent_principal/01-install.yaml, tests/k8s/1-051_validate_argocd_agent_principal/02-delete.yaml, tests/k8s/1-051_validate_argocd_agent_principal/03-assert.yaml, tests/k8s/1-051_validate_argocd_agent_principal/03-install.yaml
/kind bug
This PR is to add logic for principal where image name is first taken from ArgoCD resource, if not available then it is taken from an env variable. If that is also not available then default is used.
Fixes: https://issues.redhat.com/browse/GITOPS-7605
=> fix: ArgoCD agent principal image configurations

controllers/argocd/deployment.go
This PR fixes the bug where redis ha proxy pod fails to restart with error related to security context after upgrade
Fixes #?
[GITOPS-7180](https://issues.redhat.com/browse/GITOPS-7180)
=> bug: fix redis ha proxy pod fails to restart after upgrade

controllers/argocd/argocd_controller.go, controllers/argocd/argocd_controller_test.go, controllers/argocd/dex.go, controllers/argocd/repo_server.go, controllers/argocd/role.go, controllers/argocd/service.go, controllers/argocd/service_account.go, controllers/argocd/sso.go, controllers/argocd/sso_test.go, controllers/argocd/status.go, controllers/argocd/status_test.go, controllers/argocd/util.go, controllers/argocd/util_test.go, tests/ginkgo/parallel/1-015_validate_sso_status_test.go, tests/ginkgo/parallel/1-047_validate_impersonation_namespace_scoped_instance_test.go, tests/ginkgo/parallel/1-048_validate_status_conditions_test.go, tests/ginkgo/parallel/1-120_verify_argocd_status_consistency_test.go
/kind bug
- Primary purpose is to fix this status race condition, which has been causing periodic test failures: 
- https://github.com/redhat-developer/gitops-operator/issues/909
- The fix modifies how status updating working in the operator: 
- Functions which wish to modify the ArgoCD CR .status field, are instead passed a pointer to a `ArgoCDStatus` object. Functions should update this status object, not the `ArgoCD` CR status directly. This status object is set on the `ArgoCD` CR on completion of reconciliation.
- This PR:
- Updates to .status field of `ArgoCD` CR only happen once, from one function (`updateStatusConditionOfArgoCD`), rather than many different functions.
- Remove some old dex deletion logic which …
=> fix: ArgoCD CR .status  is intermittently out of sync with actual Argo CD workloads

controllers/argocdagent/deployment.go, tests/ginkgo/sequential/1-051_validate_argocd_agent_principal_test.go
/kind bug
This PR is to fix principal deployment configs where default redis server address is hard coded to "argocd-redis", but when ArgoCD is deployed in different namespace then redis service name would be changed and this will cause issue in principal as it will be looking for a wrong address.
Fixes https://issues.redhat.com/browse/GITOPS-7790
=> fix: Redis server address is hard coded for principal deployment
