argoproj-labs/argocd-operator

- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.0.5/argocd-operator.v0.0.5.clusterserviceversion.yaml
- deploy/operator.yaml
- version/version.go
This PR updates the operator to v0.0.5
> Release v0.0.5

- deploy/crds/argoproj.io_argocds_crd.yaml
- docs/reference/argocd.md
- examples/argocd-ha.yaml
- examples/argocd-ingress.yaml
- examples/argocd-insecure.yaml
- examples/argocd-insights.yaml
- examples/argocd-route.yaml
- pkg/apis/argoproj/v1alpha1/argocd_types.go
- pkg/controller/argocd/ingress.go
- pkg/controller/argocd/route.go
- pkg/controller/argocd/util.go
This PR addresses #3 and  improves the Ingress and Route logic to allow for more control over selecting which resources get created.
> Allow for more control of Ingress and Routes

- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.0.6/argocd-operator.v0.0.6.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.0.6/argoproj.io_argocdexports_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.6/argoproj.io_argocds_crd.yaml
- deploy/operator.yaml
- pkg/common/defaults.go
- version/version.go
This PR updates the operator to v0.0.6
> Release v0.0.6

- deploy/catalog_source.yaml
- deploy/operator.yaml
- docs/reference/argocdexport.md
- pkg/common/defaults.go
- version/version.go
This PR updates the operator to v0.0.7
> Release v0.0.7

- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.0.8/argocd-operator.v0.0.8.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.0.8/argoproj.io_applications_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.8/argoproj.io_appprojects_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.8/argoproj.io_argocdexports_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.8/argoproj.io_argocds_crd.yaml
- deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
- deploy/operator.yaml
- docs/reference/argocdexport.md
- pkg/common/defaults.go
- version/version.go
This PR updates the operator to v0.0.8
> Release v0.0.8

- docs/usage/basics.md
This PR adds more information on the resources that are created and managed by the operator. A section was added to help address #62 that describes the purpose of the cluster secret.
> Update Usage Documentation

- pkg/controller/argocd/route.go
Changed passthrough insecure policy to redirect
> Changed passthrough insecure policy to redirect

- build/util/Dockerfile
- build/util/util.sh
- deploy/crds/argoproj.io_argocdexports_crd.yaml
- docs/reference/argocdexport.md
- docs/usage/export.md
- examples/argocdexport-azure.yaml
- pkg/apis/argoproj/v1alpha1/argocdexport_types.go
- pkg/common/keys.go
- pkg/common/values.go
- pkg/controller/argocdexport/export.go
This PR addresses #51 to add support for exporting to Microsoft Azure.
> Add Support for Backups to Azure

- README.md
- build/Dockerfile
- deploy/bundle/Dockerfile
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.0.9/argocd-operator.v0.0.9.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.0.9/argoproj.io_applications_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.9/argoproj.io_appprojects_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.9/argoproj.io_argocdexports_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.9/argoproj.io_argocds_crd.yaml
- deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
- docs/index.md
This PR addresses #89 to add the OLM artifacts for the v0.0.9 release.
> Add OLM Artifacts for v0.0.9 Release

- docs/reference/api.html.md
- docs/reference/argocdexport.md
- pkg/apis/argoproj/v1alpha1/argocd_types.go
- pkg/common/defaults.go
- version/version.go
This PR updates the operator to v0.0.11
> Update Argo CD Operator to v0.0.11 

- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.0.11/argoproj.io_applications_crd.yaml
- deploy/operator.yaml
This PR adds the OLM artifacts for v0.0.11 of the operator.
> Add OLM Artifacts for v0.0.11

- hack/local.sh
- pkg/controller/argocd/deployment.go
- pkg/controller/argocd/secret.go
This PR addresses #94 and will synchronize the TLS certificate and key used by Argo CD if there has been a change to the cluster TLS secret.
> Sync Changes to TLS Secret 

- examples/argocd-oauth.yaml
Update the example on how to enable the route using the "new way"
> Update example with how to enable the route

- docs/reference/argocd.md
Added some documentation regarding an SSO issue with properly mapping the roles.
> updated the docs to document a small nuanced issue with group mappings

- pkg/controller/argocd/deployment.go
- pkg/controller/argocd/deployment_test.go
Fix for not updating the mount volumes when a deployment is changed.
This checks that the volumes and volume mounts are replaced if they differ.
> Fix issue with replacing the resource configuration

- docs/reference/argocd.md
This documents `spec.resourceInclusions`, based on the ArgoCD documentation.
> Add documentation for the resourceInclusions property.

- pkg/controller/argocd/configmap.go
There was some debug logging accidentally left in.
> Remove extraneous logging.

- pkg/controller/argocd/deployment.go
- pkg/controller/argocd/util.go
Fix typos and remove dead code
> Fix typos and remove dead code

- pkg/controller/argocd/util.go
> Remove dead code

- pkg/controller/argocd/deployment.go
Add a couple of lines of logging when dex is disabled.
> Add logging when handling disabled dex.

- deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_argocds_crd.yaml
Update the CRD inside deploy dir to reflect changes from #184 
cc @iam-veeramalla @bigkevmcd
> Update ArgoCD CRD resource to support latest changes to the API

- pkg/controller/argocd/deployment.go
- pkg/controller/argocd/deployment_test.go
- pkg/reconciler/openshift/openshift.go
- pkg/reconciler/openshift/openshift_test.go
Added hook to update the redis deployment spec for openshift cluster with redhat specifc redis image args.
> Added openshift hook to use redhat specific redis image args

- pkg/controller/argocd/statefulset.go
- pkg/controller/argocd/statefulset_test.go
This PR fixes the issues with reconciliation logic of redis stateful sets.
> fixed reconciliation of redis stateful sets

- docs/reference/argocd.md
Corrected OpenShift SSO group configuration
> Corrected OpenShift SSO group configuration

- pkg/controller/argocd/configmap_test.go
- pkg/controller/argocd/util.go
Add unit test for @sabre1041's fix
> Fix dex clientID with unit test

- pkg/controller/argocd/statefulset.go
- pkg/controller/argocd/statefulset_test.go
> Fix HA mode for ArgoCD 1.8.7

- build/redis/init.sh.tpl
- build/redis/redis.conf.tpl
- docs/reference/argocd.md
- pkg/common/keys.go
- pkg/controller/argocd/deployment.go
- pkg/controller/argocd/hooks.go
- pkg/controller/argocd/hooks_test.go
- pkg/controller/argocd/policyrule.go
- pkg/controller/argocd/role.go
- pkg/controller/argocd/role_test.go
- pkg/controller/argocd/rolebinding.go
- pkg/controller/argocd/service_account.go
- pkg/controller/argocd/service_account_test.go
- pkg/controller/argocd/statefulset.go
- pkg/controller/argocd/util.go
- pkg/controller/argocd/util_test.go
- pkg/reconciler/openshift/clusterconfig_test.go
- pkg/reconciler/openshift/openshift.go
- pkg/reconciler/openshift/openshift_test.go
> OpenShift hooks for HA

- build/util/Dockerfile
- deploy/argo-cd/argoproj.io_applications_crd.yaml
- deploy/argo-cd/argoproj.io_appprojects_crd.yaml
- docs/contribute/development.md
- pkg/common/defaults.go
This PR updates the default version of Argo CD that will be deployed by the operator to v2.0.0
> Upgrade to Argo CD v2.0.0

- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.0.15/argocd-operator.v0.0.15.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_applicationsets_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_argocds_crd.yaml
- deploy/olm-catalog/argocd-operator/ci.yaml
> /kind bug
This PR updates the artifacts used by the operator hub to properly deploy the v0.0.15 version of the operator.
Fixes #?
N/A
N/A
> Update Operator Hub Artifacts for v0.0.15

- deploy/olm-catalog/argocd-operator/0.0.15/argocd-operator.v0.0.15.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.0.16/argocd-operator.v0.0.16.clusterserviceversion.yaml
/kind bug
This PR adds the ApplicationSet to the list of owned resources for the operator.
This is an attempt to resolve the issue with submitting the operator to the community operators repo for inclusion in the Operator Hub.
> Add Missing ApplicationSet Owned Resource in CSV.

- deploy/crds/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.0.15/argoproj.io_applicationsets_crd.yaml
- deploy/olm-catalog/argocd-operator/0.0.16/argoproj.io_applicationsets_crd.yaml
/kind bug
This PR removes the separator from the ApplicationSet CRD that is causing the bundle build to fail.
Fixes #?
> Remove Separator Causing Bundle Build Failure

- pkg/controller/argocd/secret.go
/kind bug
Adds owner reference to the Cluster Secret created by the operator.
Fixes #?
> Add owner reference to the cluster secret

- pkg/reconciler/openshift/openshift.go
Note: This bug is very specific to OpenShift
> /kind bug
fixes #339 
NA
Fixes #?
#339 
1. Run the operator locally
2. Create an ArgoCD instance to manage cluster config resource.
> fix: operator when run locally fails to create ArgoCD to manage cluster resources for OpenShift

- .github/workflows/lint.yaml
- .golangci.yml
Our code is a mess, we need to get better. This introduces golangci-lint for PRs to the default branch, so new code will be properly linted.
We will clean-up afterwards and then proceed to check whole code base every time.
Fixes #?
No test required.
> chore(ci): Introduce golangci-lint for PRs

- docs/reference/argocd.md
- mkdocs.yml
This PR updates the documentation for the newly added fields `Image` and `Version` for Single sign-on options.
These fields are added by the PR #349 
> chore: update documentation for Single sign-on options

- pkg/controller/argocd/util.go
/kind bug
This PR fixes the issue when namespace label `argocd.argoproj.io/managed-by` is updated to a different value i.e from namespace `foo` -> `bar`. 
The issue being, RBACs that were created for "foo" does not get removed when the namespace label is updated, while it creates the RBACs for the new namespace (bar). 
Fixes #?
https://issues.redhat.com/browse/GITOPS-1180
- Deploy the latest Operator.
- deploy two argocd instances in the namespace `foo1` and `foo2`.
- create a namesapce `bar` with the label `argocd-argoproj.io/managed-by: foo1`.
- Make sure argocd instance in …
> fix: delete existing RBACs when namespace label is updated

- pkg/controller/argocd/applicationset.go
- pkg/controller/argocd/applicationset_test.go
/kind bug
See [parent issue](https://github.com/argoproj-labs/argocd-operator/issues/377) for details.
This PR:
- Adds the fields to update logic which were previously missing.   Missing fields are volumes, serviceaccount name, and labels.
- Improves the existing Deployment create unit test, to handle these fields
- Adds a new test for updating an existing Deployment, which would catch the issue described in the original PR
Fixes #377
You can reproduce by:
1. Creating an ArgoCD with the appSet field defined
2. Waiting for it to reconcile the applicationset-controller Deploment
3. Ediit the applicationset-controller Deployment to …
> fix: ApplicationSet controller Deployment reconcilliation update logic misses volume field

- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.0.16/argocd-operator.v0.0.16.clusterserviceversion.yaml
- deploy/role.yaml
> /kind bug
fix #388 
NA
#388 
Fixes #?
#388 
- checkout the PR
- update ./hack/env.sh with your personal repo details
- run ./hack/build.sh
- run ./hack/push.sh
- register the SHA, update the SHA in clusterserviceversion resource(Image and Container Image feilds)
- run ./hack/bundle.sh
- run ./hack/register.sh
- register the SHA and update deploy/catalog_source.yaml
> fix: Operator errors on reconciling namespaces, Cannot list resource namespaces #388

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- config/samples/argoproj.io_v1alpha1_application.yaml
- config/samples/argoproj.io_v1alpha1_applicationset.yaml
- config/samples/argoproj.io_v1alpha1_appproject.yaml
- config/samples/argoproj.io_v1alpha1_argocd.yaml
- config/samples/argoproj.io_v1alpha1_argocdexport.yaml
- config/samples/kustomization.yaml
Adds sample CRs for argocd applications, applicationsets and appprojects to the `config/samples` folder and updates the `alm-examples` annotation in the CSV.  This also gets rid of the warnings when running `make bundle`
There is no functional change for this PR
> sdk upgrade: add samples

- docs/usage/dex.md
- mkdocs.yml
Adds documentation for:
- Dex Overview
- Dex OpenShift Connector
- Dex GitHub Connector
- Option to Disable Dex Installation
#213 #142  #375 
Install mkdocs
and run `mkdocs serve`
> Add documentation for Dex

- CONTRIBUTING.md
fixes a broken link in CONTRIBUTING.md
> doc: fix broken link to contribution guidelines

- .gitignore
/kind cleanup
Add `.vscode` to `.gitignore`, to have a clean working repository when using VScode
Fixes #?
> chore: Add .vscode to .gitignore

- docs/usage/ingress.md
This PR updates the documentation for the Argo CD server password.
NA
> chore: update documentation for argo cd server password

- .github/workflows/codegen.yaml
Add checks to our GitHub actions pipeline which validate that:
* go.mod and go.sum are in sync (e.g. user ran `go mod tidy` before submitting PR)
* `make bundle` with the current used version of Operator SDK does not have a diff from the PR's branch
Fixes #?
> chore: Add a check for generated code

- controllers/argocd/keycloak.go
- controllers/argocd/keycloak_test.go
- controllers/argocd/sso.go
> fix: Keycloak deployments do not respect NodeSelector and Tolerations in the Argo CD CR(#450)

- bundle/manifests/argoproj.io_applicationsets.yaml
- config/crd/bases/argoproj.io_applicationsets.yaml
/kind bug
The applicationset has not been updated to v0.2.0 even though version/image have been upgraded in default.go.
Fixes #?
> Update  applicationset crd to v0.2.0

- docs/contribute/openapi.md
- mkdocs.yml
> /kind bug
Fixes #459, #416 
Yes
Fixes #459, #416 
Yes tested the changes. For steps please refer #459
> chore: fix failing doc builds and minor issues.

- common/defaults.go
upgrades the dex version to v2.30.0
NA
> chore: upgrade the dex version to v2.30.0

- controllers/argocd/util.go
- controllers/argocd/util_test.go
/kind bug
Porting changes in https://github.com/argoproj-labs/argocd-operator/pull/479 to rhos-v1.3 branch to be consumed in gitops-operator v1.3.2 release
Fixes #?
> fix: remove managed namespace from cluster secret after deletion

- api/v1alpha1/argocd_types.go
- bundle/manifests/argoproj.io_argocds.yaml
- config/crd/bases/argoproj.io_argocds.yaml
- controllers/argocd/deployment.go
- deploy/olm-catalog/argocd-operator/0.2.0/argoproj.io_argocds.yaml
/kind cleanup
This is a small followup PR that relates to PR #458  for things that needed tweaking but got merged before the changes could be made.
See #458
> Followup PR for #458- allow setting replicas

- docs/reference/argocd.md
> doc: fix  repo and argocd server replicas field documentation

- controllers/argocd/keycloak.go
- controllers/argocd/keycloak_test.go
> /kind bug
Fixes #492 
NA
Fixes #492 
Please refer to the issue #492
> fix: operator cannot install keycloak when resourcequota scope is not set (#492)

- .github/workflows/publish.yaml
> /kind bug
Fixes #498 
NA
Fixes #498 
NA
> fix: Publish latest operator build to quay workflow is failing (#498)

- common/defaults.go
Update Argo CD version to v2.1.7
NA
NA
> chore: update Argo CD version to v2.1.7

- common/defaults.go
upgrades Argo CD to v2.1.8
https://hub.docker.com/layers/argoproj/argocd/v2.1.8/images/sha256-96430a46ceebb78db2f51ec97681267a79e2ab13c91e3762d569084b067d0867?context=explore
NA
> chore: update Argo CD version to v2.1.8

- common/defaults.go
- go.mod
- go.sum
upgrades Argo CD to v2.1.8
https://github.com/argoproj/argo-cd/releases/tag/v2.1.8
NA
NA
> chore: update Argo CD version to 2.1.8

- docs/reference/api.html.md
- docs/reference/argocd.md
- docs/usage/dex.md
… (#522)"
This reverts commit 2f43a08b7aa806a4468ba7e6c64404bdbb8fbacf.
> /kind bug
Fixes #?
> fix: Revert "docs: update operator documentation to reflect dex migration (#522)"

- .github/PULL_REQUEST_TEMPLATE.md
Adds a new kind `/kind chore` in the PR description section. I think this category is needed for routine tasks.
NA
> chore: add a new kind for routine tasks

- docs/install/manual.md
Added some info blocks to help the reader install the operator without issues.
> /kind bug
This is a documentation update to help reader perform manual install of operator without issues.
[ ] Documentation has been updated.
This is a documentation update.
Fixes #?
I think notes are pretty simple, just guiding the reader to the right direction.
> Updated manual.md

- controllers/argocd/applicationset.go
- controllers/argocd/applicationset_test.go
> /kind bug
cherry-pick #508 
When using  Operator on Red Hat Openshift 4.7, the argocd-applicationset-controller does not have the global proxy configuration applied.
This causes us to be unable to use ApplicationSet resources due to the following error in the argocd-applicationset-controller logs:
```
Error during fetching repo: `git fetch origin HEAD --tags --force` failed timeout after 1m30s
```
NA
https://github.com/redhat-developer/gitops-operator/issues/249
Please refer
https://github.com/redhat-developer/gitops-operator/issues/249
> [cherry-pick]: ApplicationSet Controller Does Not Receive Proxy Configuration #508

- build/util/Dockerfile
- common/defaults.go
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
update the manifests for release v0.2.0
NA
To test the PR with latest manifests.
1. Install OLM on your local kubernetes cluster.
2. Follow the instructions as shared in the Argo CD Operator Docs to verify the release v0.2.0
https://argocd-operator.readthedocs.io/en/latest/contribute/olm-env/
> feat: update manifests to release v0.2.0

- build/util/Dockerfile
- common/defaults.go
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
prepare the manifests for release v0.2.0
NA
To test the PR with latest manifests.
1. Install OLM on your local kubernetes cluster.
2. Follow the instructions as shared in the Argo CD Operator Docs to verify the release v0.2.0
https://argocd-operator.readthedocs.io/en/latest/contribute/olm-env/
> feat: prepare manifests for release v0.2.0

- docs/release-process.md
- mkdocs.yml
> /kind chore
This PR adds the documentation for release process.
You can test this changes by 
1. Install MKDocs for material.
2. Run `mkdocs serve`
> chore: document release process

- docs/usage/custom_roles.md
- mkdocs.yml
1. Improve the documentation for configuring custom roles via environment variables
2. Add Custom Roles section to the doc index.
Fixes #?
> Improve docs for custom roles feature

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.2.0/argocd-operator.v0.2.0.clusterserviceversion.yaml
> /kind bug
/kind chore
Fixes #?
> fix: update operator capabilities level in CSV

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml
> /kind bug
/kind chore
fix typo in operator capabilities in CSV
Fixes #?
> chore: fix typo in capabilities

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- common/defaults.go
- config/rbac/role.yaml
- controllers/argocd/argocd_controller.go
- controllers/argocd/keycloak.go
- controllers/argocd/keycloak_test.go
- controllers/argocd/util.go
- controllers/argocd/util_test.go
- deploy/olm-catalog/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml
- docs/reference/argocd.md
- docs/usage/keycloak/openshift.md
- examples/argocd-keycloak-openshift.yaml
- hack/test.sh
- kuttl-test-keycloak.yaml
- kuttl-test-rhsso.yaml
- tests/e2e-keycloak/argocd-tests/01-argocd-keycloak.yaml
- tests/e2e-keycloak/argocd-tests/01-assert.yaml
- tests/e2e-keycloak/argocd-tests/99-delete.yaml
- tests/e2e-rhsso/argocd-tests/01-argocd-rhsso.yaml
- tests/e2e-rhsso/argocd-tests/01-assert.yaml
- tests/e2e-rhsso/argocd-tests/02-sleep.yaml
- tests/e2e-rhsso/argocd-tests/03-verify-oidc.yaml
- tests/e2e-rhsso/argocd-tests/04-verifyRealmCreation.yaml
- tests/e2e-rhsso/argocd-tests/99-delete.yaml
cherry picks #555 
cherry picks #555 into release-0.3 branch 
Please refer #555 for complete information about and testing the PR.
> [cherry picks #555 ] Upgrade RH-SSO to v7.5.1 and support kube:admin, ocp groups and proxy env

- .github/workflows/lint.yaml
/kind chore
Fixes CI linting errors by upgrading golangci-lint
Fixes #?
Change is successful if CI tests pass
> chore: upgrade golangci-lint

- bundle/manifests/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_applications.yaml
> /kind chore
add missing crd changes for argocd v2.3
Application CRD should be in sync with the CRD in Argo CD upstream v2.3 branch.
https://github.com/argoproj/argo-cd/blob/release-2.3/manifests/crds/application-crd.yaml
> [release-0.3] add missing crd changes for argocd v2.3

- bundle/manifests/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_applications.yaml
> /kind chore
add missing crd changes for argocd v2.3
Application CRD should be in sync with the CRD in Argo CD upstream v2.3 branch.
https://github.com/argoproj/argo-cd/blob/release-2.3/manifests/crds/application-crd.yaml
> add missing crd changes for argocd v2.3

- build/util/Dockerfile
- common/defaults.go
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator-manager-config_v1_configmap.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator.v0.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_appprojects.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_argocdexports.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_argocds.yaml
- deploy/olm-catalog/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.3.0/argoproj.io_applicationsets.yaml
/kind chore
chore:[release-0.3] update argocd to v2.3.3 in Dockerfile and defaults.go
Added missing 0.2.1 crds
Fixes #?
> chore:[release-0.3] update argocd to v2.3.3 in Dockerfile and defaults.go

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- common/defaults.go
- config/manager/kustomization.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.3.0/argocd-operator.v0.3.0.clusterserviceversion.yaml
/kind chore
update manifests for release v0.3.0
Fixes #?
1. checkout the PR
2. Run the below command to deploy the catalog source
3. kubectl apply -f deploy/catalog_source.yaml
4. Install the operator.
> feat: update manifests for release v0.3.0

- controllers/argocd/argocd_controller_test.go
- controllers/argocd/configmap.go
- controllers/argocd/deployment.go
- controllers/argocd/hooks.go
- controllers/argocd/hooks_test.go
- controllers/argocd/ingress.go
- controllers/argocd/keycloak.go
- controllers/argocd/keycloak_client.go
- controllers/argocd/keycloak_client_test.go
- controllers/argocd/policyrule.go
- controllers/argocd/role.go
- controllers/argocd/role_test.go
- controllers/argocd/rolebinding.go
- controllers/argocd/rolebinding_test.go
- controllers/argocd/secret.go
- controllers/argocd/service_account.go
- controllers/argocd/service_account_test.go
- controllers/argocd/statefulset.go
- controllers/argocd/status.go
- controllers/argocd/testing.go
- controllers/argocd/util.go
- controllers/argocd/util_test.go
- controllers/argocdexport/job.go
- controllers/argoutil/volume.go
- controllers/openshift/openshift.go
- controllers/openshift/openshift_test.go
/kind cleanup
Fix all lint errors that were reported by `golangci-lint run`
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>
`golangci-lint run` should not report any lint errors
> Fix lint errors

- deploy/olm-catalog/argocd-operator/0.4.0/argoproj.io_argocds.yaml
/kind bug
The "make bundle" started failing as part of PR #473. This PR fixes the "make bundle"
Fixes #?
- make bundle
> fix make bundle

- docs/reference/api.html.md
/kind cleanup
Simple update to Documentation title since there was a typo.
N/A
N/A
> Fix typo in documentation

- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator-manager-config_v1_configmap.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argocd-operator.v0.2.1.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_appprojects.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_argocdexports.yaml
- deploy/olm-catalog/argocd-operator/0.2.1/argoproj.io_argocds.yaml
- deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
/kind chore
Adds the files from the bundle for version 0.2.1 to the master branch.  Without these files, we can't build the registry image
> add missing bundle from version 0.2.1

- tests/k8s/1-019_validate_rolebindings_with_managed_by/01-basic.yaml
- tests/k8s/1-019_validate_rolebindings_with_managed_by/02-argocd-instance.yaml
> /kind bug
> /kind chore
fix failing e2e test
Fixes #?
> fix: failing e2e test

- controllers/argocd/role.go
- controllers/argocd/rolebinding.go
- tests/k8s/1-019_validate_rolebindings_with_managed_by/01-assert.yaml
- tests/k8s/1-019_validate_rolebindings_with_managed_by/01-basic.yaml
- tests/k8s/1-019_validate_rolebindings_with_managed_by/02-argocd-instance.yaml
- tests/k8s/1-019_validate_rolebindings_with_managed_by/02-assert.yaml
/kind chore
Cherry-picks PR #667 into release-0.4
> fix: Operator does not create necessary RoleBindings in all cases (#667)

- docs/install/openshift.md
> /kind bug
#539 
Fixes #539 
Closes #539 
Please follow the doc to verify the installation of the operator on an OpenShift Cluster.
> fix: OpenShift Installation docs

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/default/manager_config_patch.yaml
- config/manager/manager.yaml
- deploy/olm-catalog/argocd-operator/0.4.0/argocd-operator.v0.4.0.clusterserviceversion.yaml
fix: added security context on operator manifest
> fix: added security context on operator manifest

- controllers/argocd/service.go
- tests/k8s/1-020_validate_redis_ha_nonha_services/01-assert.yaml
- tests/k8s/1-020_validate_redis_ha_nonha_services/01-basic.yaml
- tests/k8s/1-020_validate_redis_ha_nonha_services/01-errors.yaml
- tests/k8s/1-020_validate_redis_ha_nonha_services/02-assert.yaml
- tests/k8s/1-020_validate_redis_ha_nonha_services/02-enable-ha-patch.yaml
- tests/k8s/1-020_validate_redis_ha_nonha_services/02-errors.yaml
This PR cherry picks #709 into release branch 0.4
/kind bug
> /kind bug
> /kind chore
Fixes #?
> fix: added auto tls for redis ha (#709) cherry-pick into [release-0.4]

- .github/workflows/lint.yaml
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>
Upgrades linit in release0.2
> /kind bug
> /kind chore
Fixes #?
> chore: upgrade lint in CI of release-0.2

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
/kind chore
Upgrade ArgoCD version to v2.4.5
Fixes #?
> chore: upgrade argocd version to v2.4.5

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
/kind chore
Upgrading ArgoCD version to v2.4.6
Fixes #?
> chore: upgrade argocd v2.4.6 to release 0.4

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
/kind chore
upgrade argocd to v2.4.7 in release-0.4
Fixes #?
> chore: upgrade argocd to v2.4.7 - release-0.4

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
/kind chore
upgrade argocd to v2.4.7
Fixes #?
> chore: upgrade argocd to v2.4.7

- api/v1alpha1/zz_generated.deepcopy.go
- controllers/argocd/argocd_controller.go
- controllers/argocd/deployment.go
- controllers/openshift/openshift.go
- controllers/openshift/openshift_test.go
- main.go
/kind bug
Backport fix for haproxy crash to release 0.3
Fixes #?
> fix: backport haproxy crash fix to 0.3

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- common/defaults.go
- config/manager/kustomization.yaml
- deploy/olm-catalog/argocd-operator/0.4.0/argocd-operator.v0.4.0.clusterserviceversion.yaml
/kind chore
update manifests for release v0.4.0
Fixes #?
1. checkout the PR
2. Run the below command to deploy the catalog source
3. kubectl apply -f deploy/catalog_source.yaml
4. Install the operator.
> feat: update manifests for release v0.4.0

- controllers/argocd/statefulset.go
Signed-off-by: saumeya <saumeyakatyal@gmail.com>
/kind bug
Bug fix for  0.4.1
Fixes #?
> fix: remove liveness probe from application controller 0.4

- controllers/argocd/statefulset.go
/kind bug
Backporting fix to 0.3
Fixes #?
> fix: remove liveness probe from application-controller 0.3

- docs/reference/argocd.md
To update application-set controller default image
Fixes #748 
None
> docs: update application-set controller default image

- OWNERS
> /kind chore
Updates the OWNERS file
> chore: update OWNERS file

- controllers/argocd/role.go
- controllers/argocd/role_test.go
- controllers/argocd/rolebinding.go
- controllers/argocd/rolebinding_test.go
> /kind bug
cherry-picks #755 
NA
Fixes #755 
#755
> [v0.4.0] fix: terminating namespaces blocks new managed Argo CD namespaces

- controllers/argocd/statefulset.go
> /kind bug
> /kind chore
Fixes #?
> fix: remove liveness probe from application-controller 0.2

- tests/k8s/1-021_validate_notification_controller/03-disable_notification.yaml
> /kind bug
> /kind chore
Tries to fix flaky notifications controller e2e test
Fixes #?
> fix: fix flaky test

- controllers/argocd/notifications.go
- controllers/argocd/notifications_test.go
> /kind bug
Fixes #754 
Closes #754 
Fixes #754 
Automated Test:
`/usr/local/go/bin/go test -timeout 30s -run ^TestReconcileNotifications_testLogLevel$ github.com/argoproj-labs/argocd-operator/controllers/argocd`
To test manually:
Please follow #754
> fix: notification controller log level not working as expected (#754)

- docs/usage/export.md
- examples/argocdexport-azure.yaml
The existing documentation for Argo CD Export using Azure container storage is incorrect for the `azure.service.cert` field. This field should be update with the combination of certificate and private key for authenticating the Service Principal that will be used to access Azure Storage.
Made the relevant changes.
Closes #165 
Fixes #165 
If you have an existing account with Microsoft Azure, 
1. Create a Storage account and create a blob storage container.
2. Create a App Registration for Argo CD Export and provide the required permissions to Argo CD Export …
> Fix export for Azure Blob Storage

- docs/reference/argocd.md
Resource Customizations Example references PV as a health check, but the code snippet is for PVC
Fixes #?
> Fix: documentation resource customizations example

- tests/k8s/1-021_validate_notification_controller/03-disable_notification.yaml
> /kind bug
> /kind chore
attempts to fix flaky notifications controller test
Fixes #?
> fix: attempt to fix flaky notifications controller test

- controllers/argocd/policyrule.go
(cherry picked from commit a6ceb7ad2b296ca5941cbb907b2d611a1bfe3af5)
> /kind bug
/kind chore
Fixes #?
> chore: add list and watch only for applications for cluster role (#808)

- docs/reference/argocd.md
> docs: remove duplicate "Resource Exclusions Example" section

- build/util/Dockerfile
- bundle/manifests/argoproj.io_applications.yaml
- bundle/manifests/argoproj.io_applicationsets.yaml
- common/defaults.go
- config/crd/bases/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_applicationsets.yaml
- go.mod
- go.sum
/kind chore
update the argocd version to 2.5.3
Fixes #?
> chore: update the argocd version to 2.5.3 to release-0.5 branch

- build/util/Dockerfile
- bundle/manifests/argoproj.io_applications.yaml
- bundle/manifests/argoproj.io_applicationsets.yaml
- common/defaults.go
- config/crd/bases/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.5.0/argoproj.io_applicationsets.yaml
- go.mod
- go.sum
/kind chore
updated Argocd version to 2.5.3
Fixes #?
> chore: update Argocd version 2.5.3  in master

- build/util/Dockerfile
- build/util/entrypoint.sh
- build/util/util.sh
- common/defaults.go
- deploy/catalog_source.yaml
- deploy/registry/Dockerfile
- docs/usage/export.md
- examples/argocdexport-aws.yaml
- go.mod
- go.sum
> /kind bug
> /kind chore
cherrypicks #799 
cherrypicks #812 
cherrypicks #781 
Updates Argo CD version to v2.5.4
> Cherry-pick commits into the Release v0.5.0 branch

- docs/reference/argocd.md
- examples/argocd-resource-customizations.yaml
/kind bug
Fixes [GITOPS-2451](https://issues.redhat.com/browse/GITOPS-2451) to correct documentation about resource customizations
Change is already present in release-0.5 branch.
> Fix error in resource customizations documentation

- docs/reference/argocd.md
- examples/argocd-resource-customizations.yaml
/kind bug
Fixes [GITOPS-2451](https://issues.redhat.com/browse/GITOPS-2451) to correct documentation about resource customizations
> fix error in resource customization documentation

- docs/reference/argocd.md
- tests/k8s/1-025_validate_resource_ignore_differences/01-argocd-with-resource-ignore-difference.yaml
- tests/k8s/1-025_validate_resource_ignore_differences/01-assert.yaml
Adds documentation for system-level and application-level documentation about resource customization
https://issues.redhat.com/browse/GITOPS-2463
> add system-level and application-level resource customization documentation

- common/keys.go
- controllers/argocd/dex.go
- controllers/argocd/secret.go
- controllers/argocd/secret_test.go
- examples/argocd-openshift-dex.yaml
* feat: read dex clientSecret from argocd-secret
cherry-picks #847
> feat: read dex clientSecret from argocd-secret (#847)

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
What type of PR is this?
/kind chore
What does this PR do / why we need it:
upgrades argocd version to 2.6.3
> upgrade to argocd v2.6.3

- docs/reference/argocd.md
> /kind bug
> /kind chore
Fixes #?
> fix: typo in docs

- controllers/argocd/secret.go
/kind bug
> /kind chore
cherry picking https://github.com/argoproj-labs/argocd-operator/pull/883 into release-0.6 branch
Fixes #?
> fix: handle existing secret (#883)

- .github/workflows/lint.yaml
- .golangci.yml
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- common/defaults.go
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.6.0/argocd-operator.v0.6.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
/kind chore
Updates for release v0.6.0
NA, will release a gh release milestone
NA
https://argocd-operator.readthedocs.io/en/latest/e2e-test-guide/
> release v0.6.0

- docs/release-process.md
Clarifies release documentation and adds some additional information that was missing
well, inherently yes.
Normally you could just do:
- checkout to PR 
- run `mkdocs serve`
but seems like this is broken (will open up an issue for it). I guess just verify the changes for now?
> update/clarify current  release documentation

- controllers/argocd/sso.go
- controllers/argocd/sso_test.go
- docs/reference/argocd.md
- docs/usage/dex.md
- docs/usage/keycloak/kubernetes.md
/kind chore
Updates timeline in sso events & docs to reflect extended support for deprecated sso fields.
> chore: Extend removal timeline of deprecated sso fields

- docs/reference/api.html.md
- docs/reference/argocd.md
- docs/usage/dex.md
- docs/usage/keycloak/kubernetes.md
- docs/usage/keycloak/openshift.md
Update docs to reflect sso unification changes made in #896.
> doc: Update docs to reflect sso unification changes

- deploy/olm-catalog/argocd-operator/0.7.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.7.0/argocd-operator.v0.7.0.clusterserviceversion.yaml
/kind chore
Forgot to update the control plane from argocd-controller to controller-manager in 0.7.0 release
> update control plane

- pkg/workloads/deployment_test.go
- pkg/workloads/hpa_test.go
- pkg/workloads/secret_test.go
- pkg/workloads/statefulset_test.go
Minor fix for networking package tests.
Run unit tests.
> Updated workloads package tests

- api/v1alpha1/argocd_types.go
- bundle/manifests/argoproj.io_argocds.yaml
- config/crd/bases/argoproj.io_argocds.yaml
- deploy/olm-catalog/argocd-operator/0.8.0/argoproj.io_argocds.yaml
> /kind chore
This PR makes ArgoCD v1alpha1 deprecation message more informative.
> chore: Update ArgoCD v1alpha1 deprecation message

- build/util/Dockerfile
- common/defaults.go
Updates Argo CD Version to `v2.8.3`
NA
NA
> feat: pick up argo cd v2.8.3

- common/defaults.go
- controllers/argocd/keycloak.go
- controllers/argocd/keycloak_test.go
- tests/ocp/1-001_validate_rhsso/01-assert.yaml
> /kind bug
Fix issues with Keycloak probes failure and intermittent performance issues.
Fixes #1006 
Closes #1006 
Please refer #1006
> fix: keycloak probes failure and intermittent perforamance issues

- .github/dependabot.yml
/kind chore
**What does this PR do / why we need it**: enable depenabot to automate dependency version updates
Fixes #?
> Add .github/dependabot.yml to enable auto dependency version updates

- bundle.Dockerfile
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- common/defaults.go
- config/manager/kustomization.yaml
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator.v0.8.0.clusterserviceversion.yaml
/kind chore
previous release of 0.8.0 had some errors where images weren't updated correctly with most up-to-date image SHAs; this update fixes that
> re-release of v0.8.0

- bundle.Dockerfile
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- bundle/metadata/annotations.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator-webhook-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.8.0/argocd-operator.v0.8.0.clusterserviceversion.yaml
/kind cleanup
**Why do we need this PR?** 
some errors with the last PR due to my new laptop's updated sdk version were merged; this PR reverts those changes.
> fix incorrect operator-sdk version changes

- controllers/argocd/argocd_controller.go
- controllers/argocd/util.go
- main.go
> /kind bug
> /kind chore
switch to new `ArgoCDReconciler` 
Fixes #?
> code-refactoring: switch to new reconciler

- controllers/argocd/applicationset/applicationset.go
- controllers/argocd/argocd_controller.go
> /kind bug
> /kind chore
fix appset trying to manage routes without checking for openshift env
Fixes #?
> code-refactoring: fix appset trying to manage routes without checking for openshift env

- OWNERS
> /kind bug
> /kind chore
Fixes #?
> add to reviewers

- controllers/argocd/route.go
- controllers/argocd/route_test.go
> /kind bug
This PR has fix for the issue where operator doesn't reflect `ArgoCD.Spec.ApplicationSet.WebhookServer` configurations from CR into the Route that is created by operator.
Fixes #?
1. Create ArgoCD instance having below configurations in `Spec.ApplicationSet.WebhookServer` field.
```
applicationSet:
webhookServer:
host: webhook-host.<apps.URL>
route:
enabled: true
tls:
termination: edge 
```
**Actual results:**
- Webhook route created with default generated name, For example: `argocd-applicationset-controller-webhook-argo.apps.URL`
- Few other values that are given in …
> fix: ApplicationSet WebhookServer configurations don't reflect in created Route

- docs/reference/argocd.md
- docs/usage/appsets-in-any-namespace.md
- mkdocs.yml
Follow up PR for #1209 to add documentation for Appsets in any namespace.
> docs: Add documentation for Appsets in any namespace

- controllers/argocd/policyrule.go
- tests/k8s/1-037_validate_applicationset_in_any_namespace/04-assert.yaml
- tests/k8s/1-037_validate_applicationset_in_any_namespace/05-assert.yaml
- tests/k8s/1-037_validate_applicationset_in_any_namespace/06-assert.yaml
/kind bug
https://issues.redhat.com/browse/GITOPS-4183
[Bug RC-v1.12.0-3] `Create Job` from ArgoCD UI fails
This is a follow-up fix to #1219 
Fixes #?
> fix: GITOPS-4183 [Bug RC-v1.12.0-3] `Create Job` from ArgoCD UI fails

- docs/install/openshift.md
> docs: fix broken link in openshift.md

- bundle/manifests/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- bundle/manifests/argocd-operator-webhook-service_v1_service.yaml
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- common/defaults.go
- config/manager/kustomization.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.9.0/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.9.0/argocd-operator-webhook-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.9.0/argocd-operator.v0.9.0.clusterserviceversion.yaml
/kind bug
release 0.9.0 had a mistake with the control-plane, so this fix addresses it 
Fixes #?
> fix control-plane for v0.9.0

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- common/defaults.go
- config/manager/kustomization.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.9.0/argocd-operator.v0.9.0.clusterserviceversion.yaml
> /kind bug
> /kind chore
Fixes #?
> fix matchLabel on argocd-operator-controller-manager deployment

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
> fix: Upgrade argocd to 2.8.16 in release-0.8

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
> fix: Upgrade argocd to 2.9.12 in release-0.9

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
> fix: Upgrade argocd to 2.10.7 in release-0.10

- docs/release-process.md
Updates release guide instructions with additional information about the automatic changes to control-plane that the bundle makes that the release engineer has to revert. At some point this process should change so this doesn't happen every time, but it is this way for now. 
- check out to PR branch
- run `mkdocs serve`
> add updated instructions to release process doc

- pkg/argoutil/auth_test.go
- pkg/argoutil/log_test.go
- pkg/argoutil/tls_test.go
- pkg/argoutil/volume_test.go
- pkg/util/bool_test.go
- pkg/util/env_test.go
- pkg/util/file_test.go
- pkg/util/log_test.go
- pkg/util/map_test.go
- pkg/util/set_test.go
- pkg/util/string_test.go
It's not entirely clear to me how VerifyPassword function works. In its definition it takes parameters (password, hashedPassword), but in function HasArgoAdminPasswordChanged it is called with parameters(expectedPwd, actualPwd).
> Operator redesign/Add tests for util and argoutil pkg

- go.mod
- go.sum
> /kind bug
> /kind chore
Fixes #?
> fix: upgrade to argocd 2.8.18

- go.mod
- go.sum
> /kind bug
> /kind chore
Fixes #?
> fix: upgrade to argocd 2.10.9

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
> /kind bug
> /kind chore
Fixes #?
> fix: upgrade to argocd 2.9.14

- docs/requirements.txt
/kind chore
Fix failing readthedocs doc build, due to dependency update. I've updated the python dependencies to the same list that Argo CD users.
> Update mkdocs requirements.txt based on argo cd dependencies

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
> /kind bug
> /kind chore
Fixes #?
> update replaces version number for v0.10.0 to v0.9.1

- api/v1alpha1/argocd_conversion.go
- api/v1alpha1/argocd_conversion_test.go
- api/v1alpha1/argocd_types.go
- api/v1beta1/argocd_types.go
- bundle/manifests/argoproj.io_argocds.yaml
- config/crd/bases/argoproj.io_argocds.yaml
- controllers/argocd/keycloak.go
- controllers/argocd/keycloak_test.go
- controllers/argocd/sso_test.go
- controllers/argocd/status_test.go
- controllers/argocd/util.go
- deploy/olm-catalog/argocd-operator/0.9.0/argoproj.io_argocds.yaml
- tests/k8s/1-016_validate_keycloak/01-argocd-keycloak.yaml
- tests/k8s/1-016_validate_keycloak/01-assert.yaml
- tests/olm/1-002_alpha_to_beta_keycloak_conversion/01-argocd-keycloak.yaml
JIRA - https://issues.redhat.com/browse/GITOPS-1737
> Add host attribute to SSO provider spec

- build/util/Dockerfile
- bundle/manifests/argoproj.io_applications.yaml
- bundle/manifests/argoproj.io_applicationsets.yaml
- common/defaults.go
- config/crd/bases/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.9.0/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.9.0/argoproj.io_applicationsets.yaml
- go.mod
- go.sum
/kind chore
Update Argo CD version to v2.11.2.
https://quay.io/repository/argoproj/argocd/manifest/sha256:d2c274ff26c7ab164907de05826bdfe2e6f326af70edd0bb83194b75fbb71f9e
> chore: Update Argo CD to v2.11.2

- go.mod
- go.sum
> /kind bug
> /kind chore
Fixes #?
> Update argocd version to v2.11.3

- Makefile
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- common/defaults.go
- config/manager/kustomization.yaml
- config/manifests/bases/argocd-operator.clusterserviceversion.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argocd-operator-controller-manager-metrics-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argocd-operator-manager-config_v1_configmap.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argocd-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argocd-operator-webhook-service_v1_service.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argocd-operator.v0.10.1.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argoproj.io_appprojects.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argoproj.io_argocdexports.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argoproj.io_argocds.yaml
- deploy/olm-catalog/argocd-operator/0.10.1/argoproj.io_notificationsconfigurations.yaml
- deploy/olm-catalog/argocd-operator/argocd-operator.package.yaml
* update argocd version to 2.10.11
* operator v0.10.1
/kind chore
pulls in the changes from the 0.10.1 release back to master. Note: this does not update any argocd versions because the 0.10.1 argocd version is less than what master is currently at. 
Fixes #?
> cherry-pick  0.10.1 release to master branch (#1407)

- CONTRIBUTING.md
/kind chore
fix broken link in CONTRIBUTING.md to development guide
> chore(docs): fix broken link in CONTRIBUTING.md to development guide

- tests/k8s/1-022_validate_notifications/02-update-notifications-cm.yaml
> [ Operator Redesign ] Fix: update test 1-022 to use notificationsconfiguration CR 

- controllers/argocd/route.go
- controllers/argocd/route_test.go
/kind bug
Currently, there is a race condition when users upgrade from v1.12.x to v1.13. This occurs when the TLS secret gets created before updating the default policy. Because of this, the Route stays in the Passthrough policy assuming that the user created this TLS secret. In this PR, we check if the TLS secret has the OpenShift service CA annotations to verify if the secret was created by the user or by the OpenShift Service CA. 
We remove the check to find the previous Route's policy since it can change if the user manually deletes the secret. Instead, we rely on the existence of the TLS secret to determine the previous policy. …
> fix: race condition when the TLS secret is created before setting the default policy

- controllers/argocd/policyrule.go
> Fix appset policy for argocd controller

- build/util/Dockerfile
- common/defaults.go
- controllers/argocd/custommapper.go
- controllers/argocd/util.go
- go.mod
- go.sum
> /kind bug
> /kind chore
Fixes #?
> chore: upgrade argocd to 1.12.3

- docs/reference/argocd.md
- Updates documentation for init and sidecar containers support
> docs: update documentation for init and sidecar containers support

- build/util/Dockerfile
- common/defaults.go
> Updated argocd image in Dockerfile to use 2.11.7

- deploy/olm-catalog/argocd-operator/0.12.0/argocd-operator.v0.12.0.clusterserviceversion.yaml
> fix: correct incorrect sha in 0.12 branch

- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- deploy/catalog_source.yaml
- deploy/olm-catalog/argocd-operator/0.12.0/argocd-operator.v0.12.0.clusterserviceversion.yaml
https://github.com/argoproj-labs/argocd-operator/issues/1548 
Fixes #?
> fix: correct the registry image

- .github/workflows/lint.yaml
- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
/kind chore
PR updates argocd version to 2.11.11
Fixes #?
> update argocd version to 2.11.11

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
/kind chore
This PR update the argo-cd version to 2.12.6
Fixes #?
> update argocd version to 2.12.6

- docs/reference/argocd.md
/kind chore
Update dynamic scaling docs for argocd-controller
Cherry-pick to `release-0.12`, `release-0.11` and `release-0.10`
> Update dynamic scaling docs for argocd-controller

- docs/reference/argocd.md
> Update dynamic scaling docs for argocd-controller (#1581)

- .github/workflows/ci-build.yaml
- .github/workflows/codegen.yaml
- .github/workflows/go.yml
- .github/workflows/lint.yaml
/kind chore
Skip CI for argocd
Fixes #?
> skip CI for docs PR

- build/util/Dockerfile
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- bundle/manifests/argoproj.io_applications.yaml
- bundle/manifests/argoproj.io_applicationsets.yaml
- bundle/manifests/argoproj.io_appprojects.yaml
- common/defaults.go
- config/crd/bases/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applicationsets.yaml
- config/crd/bases/argoproj.io_appprojects.yaml
- deploy/olm-catalog/argocd-operator/0.13.0/argocd-operator.v0.13.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.13.0/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.13.0/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.13.0/argoproj.io_appprojects.yaml
- go.mod
/kind chore 
Update Argo CD to v2.13.1
NOTE: argocd dependency is not update in go.mod file due to https://github.com/argoproj-labs/argocd-operator/pull/1606#issuecomment-2490948356
Fixes #?
> chore: Update Argo CD to v2.13.1

- controllers/notificationsconfiguration/configmap.go
- controllers/notificationsconfiguration/configmap_test.go
* fix: broken check for context in notificationController
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
* add unit tests
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
* update test
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
---------
Signed-off-by: Anand Kumar Singh <anandrkskd@gmail.com>
(cherry picked from commit eace21cb8c21c2c3024da5c4485b99646aed7dc2)
> fix: broken check for context in notificationController (#1626)

- controllers/argocd/notifications_util.go
/kind bug
Pick upstream https://github.com/argoproj/argo-cd/pull/21944 fix into operator
Fixes #?
> fix: On deployed trigger must consider race between last transition time & sync finished time

- build/util/Dockerfile
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- bundle/manifests/argoproj.io_applications.yaml
- bundle/manifests/argoproj.io_applicationsets.yaml
- common/defaults.go
- config/crd/bases/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.14.0/argocd-operator.v0.14.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.14.0/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.14.0/argoproj.io_applicationsets.yaml
> Updated Argo CD CRDs and Argo CD image shas for v2.14.4

- build/util/Dockerfile
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- bundle/manifests/argoproj.io_applications.yaml
- bundle/manifests/argoproj.io_applicationsets.yaml
- common/defaults.go
- config/crd/bases/argoproj.io_applications.yaml
- config/crd/bases/argoproj.io_applicationsets.yaml
- deploy/olm-catalog/argocd-operator/0.14.0/argocd-operator.v0.14.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.14.0/argoproj.io_applications.yaml
- deploy/olm-catalog/argocd-operator/0.14.0/argoproj.io_applicationsets.yaml
* Updated Argo CD CRDs and Argo CD image shas
* Updated CRDs in config/crd/bases
* Updated the ArgoCD base image pinned to 2.13.5
* Ran make bundle and make generate
---------
Fixes #?
> Updated Argo CD CRDs and Argo CD image shas for v2.14.4 (#1680)

- Makefile
- controllers/argocd/applicationset_test.go
- controllers/argocd/deployment_test.go
- controllers/argocd/keycloak_client.go
- controllers/argocd/networkpolicies.go
- controllers/argocd/notifications_test.go
- controllers/argocd/role.go
- controllers/argocd/role_test.go
- controllers/argocd/sso.go
- controllers/argocd/statefulset_test.go
- controllers/argocd/util_test.go
Fixed few warnings and removed duplicate imports and updated make bundle with sed -i.bak as sed -i was not compatible in mac
> Remove duplicate imports and fix warnings

- api/v1alpha1/argocd_conversion.go
- api/v1alpha1/argocd_types.go
- api/v1beta1/argocd_types.go
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- bundle/manifests/argoproj.io_argocds.yaml
- config/crd/bases/argoproj.io_argocds.yaml
- controllers/argocd/applicationset.go
- controllers/argocd/applicationset_test.go
- controllers/argocd/notifications.go
- controllers/argocd/notifications_test.go
- deploy/olm-catalog/argocd-operator/0.14.0/argocd-operator.v0.14.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.14.0/argoproj.io_argocds.yaml
- tests/k8s/1-029_validate_applicationset_extra_command_args/02-assert.yaml
- tests/k8s/1-033_validate_applicationset_tls_scm_volume_mount/01-assert.yaml
JIRA - https://issues.redhat.com/browse/GITOPS-6669
logFormat is not supported for redis and dex
> Enable JSON logging option for all GitOps components

- docs/install/manual.md
/kind chore
Small update to documentation regarding manual installation regarding cluster and namespace scoped instances.
Fixes #?
> (chore): manual installation doc update

- controllers/argocd/deployment.go
- controllers/argocd/deployment_test.go
- tests/k8s/1-044_validate_rollout_extension/01-assert.yaml
https://issues.redhat.com/browse/GITOPS-6662 - JIRA
> Rename the volume name from 'extensions' to 'rollout-extension'

- docs/reference/api.html.md
This PR removes deprecated field from `api` document
> update doc, removing deprecated fields documentation

- controllers/argocd/deployment.go
- tests/ha/1-020_validate_redis_ha_nonha/02-assert.yaml
- tests/ha/1-020_validate_redis_ha_nonha/03-assert.yaml
JIRA - https://issues.redhat.com/browse/GITOPS-6806
> Update redis-ha-haproxy replicas similar to redis

- api/v1alpha1/argocd_types.go
- bundle/manifests/argoproj.io_argocds.yaml
- config/crd/bases/argoproj.io_argocds.yaml
- controllers/argocd/configmap.go
- controllers/argocd/sso.go
- controllers/argocd/status.go
- deploy/olm-catalog/argocd-operator/0.14.0/argoproj.io_argocds.yaml
JIRA - https://issues.redhat.com/browse/GITOPS-7070
> Add deprecation message for Keycloak

- docs/usage/insights.md
I found a small typo in the docs regarding insights.
Fix a typo in the docs.
> docs: Fix typo

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
/kind chore
Update Argo CD to latest v3.0.11
Fixes #?
> chore: Update Argo CD to v3.0.11

- api/v1alpha1/argocd_types.go
- api/v1beta1/argocd_types.go
- bundle/manifests/argocd-operator.clusterserviceversion.yaml
- bundle/manifests/argoproj.io_argocds.yaml
- common/keys.go
- config/crd/bases/argoproj.io_argocds.yaml
- controllers/argocd/configmap.go
- controllers/argocd/configmap_test.go
- deploy/olm-catalog/argocd-operator/0.15.0/argocd-operator.v0.15.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.15.0/argoproj.io_argocds.yaml
- deploy/olm-catalog/argocd-operator/0.16.0/argocd-operator.v0.16.0.clusterserviceversion.yaml
- deploy/olm-catalog/argocd-operator/0.16.0/argoproj.io_argocds.yaml
- docs/reference/argocd.md
GITOPS-7207: Add position and permanent properties to Banner
Fixes #? GITOPS-7207
> feat: Add position and permanent properties to Banner

- controllers/argocd/deployment.go
- tests/k8s/1-044_validate_rollout_extension/01-assert.yaml
JIRA - https://issues.redhat.com/browse/GITOPS-7383
> Remove 999 user from initContainer to fix server pod failure

- controllers/argocd/applicationset.go
- controllers/argocd/configmap.go
- controllers/argocd/deployment.go
- controllers/argocd/notifications.go
- controllers/argocd/role.go
- controllers/argocd/statefulset.go
- controllers/argocd/util.go
- controllers/argocd/util_test.go
Reverts argoproj-labs/argocd-operator#1737
> Revert "GITOPS-6285: reconcile operator owned labels for configMap and ignore non operator labels"

- common/defaults.go
/kind chore
- Old image is out of date, new image is the same as the corresponding version from Argo CD
Fixes #?
> chore: update redis image to latest from upstream Argo CD

- docs/usage/dex.md
- docs/usage/extra-config.md
- docs/usage/ha/repo-server.md
- docs/usage/insights.md
- docs/usage/notifications.md
- docs/usage/resource_management.md
Minor changes in style and formatting
* [n/a] Documentation update is required by this PR.
Fixes #?
> fix(docs): Minor changes in style and formatting

- docs/usage/export.md
This rearranges and amends the doc.
/kind documentation 
Add opening paragraph explaining the concept of exports before diving to the details...
* [n/a] Documentation update is required by this PR.
Fixes #?
> feat(docs): Describe purpose of docs/usage/export.md

- build/util/Dockerfile
- common/defaults.go
- controllers/argocd/dex_test.go
- go.mod
- go.sum
/kind chore
- Update to latest upstream dependencies
- There were no CRD changes from upstream (since we last updated), thus there are none in the PR.
> chore: update to latest upstream dependencies

- controllers/argocd/deployment.go
> bug: fix redis fails after upgrade

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
Bump Argo CD to remediate  CVE-2025-55190
Fixes #?
> chore: Bump argocd

- controllers/argocd/deployment.go
Cherry pick #1860 #1841
Fixes #?
> fix: Redis SCC fix

- build/util/Dockerfile
- common/defaults.go
- go.mod
- go.sum
Bump Argo CD to 3.1.5
Fixes #?
> Bump Argo CD to 3.1.5

- controllers/argocd/util.go
- controllers/argocdagent/deployment.go
- controllers/argocdagent/deployment_test.go
- controllers/argocdagent/scripts/create-agent-config.sh
- controllers/argocdagent/service.go
- controllers/argocdagent/service_test.go
- tests/ginkgo/sequential/1-051_validate_argocd_agent_principal_test.go
- tests/k8s/1-051_validate_argocd_agent_principal/01-assert.yaml
- tests/k8s/1-051_validate_argocd_agent_principal/06-assert.yaml
This PR is to create missing resource proxy service in operator when Principal is enabled.
/kind bug
Fixes https://issues.redhat.com/browse/GITOPS-7730
> fix: Add missing services required by principal

- controllers/argocd/deployment.go
/kind bug 
Cherry pick https://github.com/argoproj-labs/argocd-operator/pull/1860 https://github.com/argoproj-labs/argocd-operator/pull/1841
Fixes #?
> fix: Fix SCC in redis deployments

- Dockerfile
- build/util/Dockerfile
Fixes: `FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)`
Avoid the warning
/kind bug
* [no] Documentation update is required by this PR.
* [no] Documentation has been updated.
None
> nit: Fix dockerfile FROM/AS casing
